### ISSUE TITLE
Random segfault in linbox charpoly

### ISSUE THREAD

**Issue by vbraun** [sagemath/sage#20116]
<div id="comment:0"></div>

Random failure on the buildbot (Ubuntu 14.04 32 bit)

```
sage -t --long src/sage/calculus/wester.py
**********************************************************************
File "src/sage/calculus/wester.py", line 483, in sage.calculus.wester
Failed example:
    m.eigenspaces_left()
Exception raised:
    Traceback (most recent call last):
      File "/mnt/highperf/buildbot/slave/sage_git/build/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 496, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/mnt/highperf/buildbot/slave/sage_git/build/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 858, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.calculus.wester[161]>", line 1, in <module>
        m.eigenspaces_left()
      File "sage/matrix/matrix2.pyx", line 5474, in sage.matrix.matrix2.Matrix.eigenspaces_left (/mnt/highperf/buildbot/slave/sage_git/build/src/build/cythonized/sage/matrix/matrix2.c:40098)
        G = self.fcp()   # factored characteristic polynomial
      File "sage/matrix/matrix2.pyx", line 2431, in sage.matrix.matrix2.Matrix.fcp (/mnt/highperf/buildbot/slave/sage_git/build/src/build/cythonized/sage/matrix/matrix2.c:20985)
        return self.charpoly(var).factor()
      File "sage/matrix/matrix_rational_dense.pyx", line 946, in sage.matrix.matrix_rational_dense.Matrix_rational_dense.charpoly (/mnt/highperf/buildbot/slave/sage_git/build/src/build/cythonized/sage/matrix/matrix_rational_dense.c:11037)
        f = A.charpoly(var, algorithm='linbox')
      File "sage/matrix/matrix_integer_dense.pyx", line 1252, in sage.matrix.matrix_integer_dense.Matrix_integer_dense.charpoly (/mnt/highperf/buildbot/slave/sage_git/build/src/build/cythonized/sage/matrix/matrix_integer_dense.c:12798)
        g = self._charpoly_linbox(var)
      File "sage/matrix/matrix_integer_dense.pyx", line 1305, in sage.matrix.matrix_integer_dense.Matrix_integer_dense._charpoly_linbox (/mnt/highperf/buildbot/slave/sage_git/build/src/build/cythonized/sage/matrix/matrix_integer_dense.c:13598)
        return self._poly_linbox(var=var, typ='charpoly')
      File "sage/matrix/matrix_integer_dense.pyx", line 1328, in sage.matrix.matrix_integer_dense.Matrix_integer_dense._poly_linbox (/mnt/highperf/buildbot/slave/sage_git/build/src/build/cythonized/sage/matrix/matrix_integer_dense.c:13957)
        sig_on()
      File "src/cysignals/signals.pyx", line 115, in cysignals.signals.sig_raise_exception (build/src/cysignals/signals.c:1400)
    SignalError: Segmentation fault
**********************************************************************
1 item had failures:
   1 of 199 in sage.calculus.wester
    [198 tests, 1 failure, 2.79 s]
```

CC:  @malb @jdemeyer @videlec @kiwifb @ClementPernet

Component: **packages: standard**

Keywords: **random_fail**

_Issue created by migration from https://trac.sagemath.org/ticket/20116_

**Comment by mkoeppe** [comment]
outdated
