### ISSUE TITLE
Cython fails its test suite on OS X

### ISSUE THREAD

**Issue by jhpalmieri** [sagemath/sage#22166]
<div id="comment:0"></div>

On OS X 10.12 with Sage 7.5.rc3 built from scratch:

```
Doctest: cppwrap.__test__.voidfunc (line 36) ... ok
test_embed (__main__.EmbedTest) ... ok

======================================================================
ERROR: runTest (__main__.CythonRunTestCase)
compiling (cpp) and running cpdef_extern_func
----------------------------------------------------------------------
Traceback (most recent call last):
  File "runtests.py", line 995, in run
    ext_so_path = self.runCompileTest()
  File "runtests.py", line 705, in runCompileTest
    self.test_directory, self.expect_errors, self.annotate)
  File "runtests.py", line 949, in compile
    so_path = self.run_distutils(test_directory, module, workdir, incdir)
  File "runtests.py", line 874, in run_distutils
    build_extension.run()
  File "/Users/palmieri/Desktop/Sage_stuff/sage_builds/TESTING/sage-7.5.rc3/local/lib/python/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/Users/palmieri/Desktop/Sage_stuff/sage_builds/TESTING/sage-7.5.rc3/local/lib/python/distutils/command/build_ext.py", line 449, in build_extensions
    self.build_extension(ext)
  File "runtests.py", line 432, in build_extension
    _build_ext.build_extension(self, ext)
  File "/Users/palmieri/Desktop/Sage_stuff/sage_builds/TESTING/sage-7.5.rc3/local/lib/python/distutils/command/build_ext.py", line 499, in build_extension
    depends=ext.depends)
  File "/Users/palmieri/Desktop/Sage_stuff/sage_builds/TESTING/sage-7.5.rc3/local/lib/python/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/Users/palmieri/Desktop/Sage_stuff/sage_builds/TESTING/sage-7.5.rc3/local/lib/python/distutils/unixccompiler.py", line 126, in _compile
    raise CompileError, msg
CompileError: command 'gcc' failed with exit status 1
```

Build logs:

- OS X 10.11: http://www.math.washington.edu/~palmieri/Sage/cython-0.25.2-10.11.log

- OS X 10.12: http://www.math.washington.edu/~palmieri/Sage/cython-0.25.2-10.12.log

Component: **packages: standard**

_Issue created by migration from https://trac.sagemath.org/ticket/22166_

**Comment by mkoeppe** [comment]
Closing as outdated
