### ISSUE TITLE
More user friendly error message if pip package fails to install

### ISSUE THREAD

**Issue by koffie** [sagemath/sage#23999]
<div id="comment:0"></div>

With #23985 if one tries to install rst2ipynb without having pandoc installed one gets the following error

```
...
...
...
[rst2ipynb-0.2.2.p0] Installing collected packages: rst2ipynb
[rst2ipynb-0.2.2.p0]   Running setup.py install for rst2ipynb: started
[rst2ipynb-0.2.2.p0]     Running command /Applications/sagedev/local/bin/python2 -u -c "import setuptools, tokenize;__file__='/private/var/folders/36/zx43_ll10r1dt47nqpbgmrs80000gn/T/pip-DMBGQ3-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" --no-user-cfg install --record /var/folders/36/zx43_ll10r1dt47nqpbgmrs80000gn/T/pip-zR3Z5F-record/install-record.txt --single-version-externally-managed --compile
[rst2ipynb-0.2.2.p0]     running install
[rst2ipynb-0.2.2.p0]     error: rst2ipynb requires the Haskell program 'pandoc'. You need to install it on your system.
[rst2ipynb-0.2.2.p0]     Running setup.py install for rst2ipynb: finished with status 'error'
[rst2ipynb-0.2.2.p0] Cleaning up...
[rst2ipynb-0.2.2.p0]   Removing source in /private/var/folders/36/zx43_ll10r1dt47nqpbgmrs80000gn/T/pip-DMBGQ3-build
[rst2ipynb-0.2.2.p0] Command "/Applications/sagedev/local/bin/python2 -u -c "import setuptools, tokenize;__file__='/private/var/folders/36/zx43_ll10r1dt47nqpbgmrs80000gn/T/pip-DMBGQ3-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" --no-user-cfg install --record /var/folders/36/zx43_ll10r1dt47nqpbgmrs80000gn/T/pip-zR3Z5F-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/36/zx43_ll10r1dt47nqpbgmrs80000gn/T/pip-DMBGQ3-build/
[rst2ipynb-0.2.2.p0] Exception information:
[rst2ipynb-0.2.2.p0] Traceback (most recent call last):
[rst2ipynb-0.2.2.p0]   File "/Applications/sagedev/local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
[rst2ipynb-0.2.2.p0]     status = self.run(options, args)
[rst2ipynb-0.2.2.p0]   File "/Applications/sagedev/local/lib/python2.7/site-packages/pip/commands/install.py", line 342, in run
[rst2ipynb-0.2.2.p0]     prefix=options.prefix_path,
[rst2ipynb-0.2.2.p0]   File "/Applications/sagedev/local/lib/python2.7/site-packages/pip/req/req_set.py", line 784, in install
[rst2ipynb-0.2.2.p0]     **kwargs
[rst2ipynb-0.2.2.p0]   File "/Applications/sagedev/local/lib/python2.7/site-packages/pip/req/req_install.py", line 878, in install
[rst2ipynb-0.2.2.p0]     spinner=spinner,
[rst2ipynb-0.2.2.p0]   File "/Applications/sagedev/local/lib/python2.7/site-packages/pip/utils/__init__.py", line 707, in call_subprocess
[rst2ipynb-0.2.2.p0]     % (command_desc, proc.returncode, cwd))
[rst2ipynb-0.2.2.p0] InstallationError: Command "/Applications/sagedev/local/bin/python2 -u -c "import setuptools, tokenize;__file__='/private/var/folders/36/zx43_ll10r1dt47nqpbgmrs80000gn/T/pip-DMBGQ3-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" --no-user-cfg install --record /var/folders/36/zx43_ll10r1dt47nqpbgmrs80000gn/T/pip-zR3Z5F-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/36/zx43_ll10r1dt47nqpbgmrs80000gn/T/pip-DMBGQ3-build/
[rst2ipynb-0.2.2.p0] Error: installing with pip2 failed
[rst2ipynb-0.2.2.p0] 
[rst2ipynb-0.2.2.p0] real	0m3.995s
[rst2ipynb-0.2.2.p0] user	0m3.273s
[rst2ipynb-0.2.2.p0] sys	0m0.619s
[rst2ipynb-0.2.2.p0] ************************************************************************
[rst2ipynb-0.2.2.p0] Error installing package rst2ipynb-0.2.2.p0
[rst2ipynb-0.2.2.p0] ************************************************************************
[rst2ipynb-0.2.2.p0] Please email sage-devel (http://groups.google.com/group/sage-devel)
[rst2ipynb-0.2.2.p0] explaining the problem and including the log file
[rst2ipynb-0.2.2.p0]   /Applications/sagedev/logs/pkgs/rst2ipynb-0.2.2.p0.log
[rst2ipynb-0.2.2.p0] Describe your computer, operating system, etc.
[rst2ipynb-0.2.2.p0] If you want to try to fix the problem yourself, *don't* just cd to
[rst2ipynb-0.2.2.p0] /Applications/sagedev/local/var/tmp/sage/build/rst2ipynb-0.2.2.p0 and type 'make' or whatever is appropriate.
[rst2ipynb-0.2.2.p0] Instead, the following commands setup all environment variables
[rst2ipynb-0.2.2.p0] correctly and load a subshell for you to debug the error:
[rst2ipynb-0.2.2.p0]   (cd '/Applications/sagedev/local/var/tmp/sage/build/rst2ipynb-0.2.2.p0' && '/Applications/sagedev/sage' --sh)
[rst2ipynb-0.2.2.p0] When you are done debugging, you can type "exit" to leave the subshell.
[rst2ipynb-0.2.2.p0] ************************************************************************
make[1]: *** [/Applications/sagedev/local/var/lib/sage/installed/rst2ipynb-0.2.2.p0] Error 1

real	0m4.407s
user	0m3.504s
sys	0m0.751s
***************************************************************
Error building Sage.

The following package(s) may have failed to build (not necessarily
during this run of 'make rst2ipynb'):

* package: rst2ipynb-0.2.2.p0
  log file: /Applications/sagedev/logs/pkgs/rst2ipynb-0.2.2.p0.log
  build directory: /Applications/sagedev/local/var/tmp/sage/build/rst2ipynb-0.2.2.p0

The build directory may contain configuration files and other potentially
helpful information. WARNING: if you now run 'make' again, the build
directory will, by default, be deleted. Set the environment variable
SAGE_KEEP_BUILT_SPKGS to 'yes' to prevent this.

make: *** [rst2ipynb] Error 1
```

The actual relevant part of this output is:

```
error: rst2ipynb requires the Haskell program 'pandoc'. You need to install it on your system.
```

but users will not be likely to see it since it is so far from the end of the error message.

Depends on #23985

CC:  @jdemeyer @embray

Component: **build**

_Issue created by migration from https://trac.sagemath.org/ticket/23999_

**Comment by koffie** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1,6 +1,9 @@
 With #23985 if one tries to install rst2ipynb without having pandoc installed one gets the following error
 
 ```
+...
+...
+...
 [rst2ipynb-0.2.2.p0] Installing collected packages: rst2ipynb
 [rst2ipynb-0.2.2.p0]   Running setup.py install for rst2ipynb: started
 [rst2ipynb-0.2.2.p0]     Running command /Applications/sagedev/local/bin/python2 -u -c "import setuptools, tokenize;__file__='/private/var/folders/36/zx43_ll10r1dt47nqpbgmrs80000gn/T/pip-DMBGQ3-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" --no-user-cfg install --record /var/folders/36/zx43_ll10r1dt47nqpbgmrs80000gn/T/pip-zR3Z5F-record/install-record.txt --single-version-externally-managed --compile
``````

**Comment by jdemeyer** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -70,6 +70,8 @@
 
 The actual relevant part of this output is:
 
-" error: rst2ipynb requires the Haskell program 'pandoc'. You need to install it on your system. "
+```
+error: rst2ipynb requires the Haskell program 'pandoc'. You need to install it on your system.
+```
 
 but users will not be likely to see it since it is so far from the end of the error message.
``````

**Comment by mkoeppe** [comment]
Closing as outdated.
