### ISSUE TITLE
random failure in src/sage/schemes/elliptic_curves/isogeny_small_degree.py

### ISSUE THREAD

**Issue by mwageringel** [sagemath/sage#29107]
<div id="comment:0"></div>

With Sage 9.1.beta2 on CentOS 7.7:

```
File "src/sage/schemes/elliptic_curves/isogeny_small_degree.py", line 2173, in sage.schemes.elliptic_curves.isogeny_small_degree.isogenies_prime_degree_general
Failed example:
    len(E.change_ring(GF(3^2,'a')).isogenies_prime_degree(13))
Exception raised:
    Traceback (most recent call last):
      File "/amd/compute/sagebot/sage/local/lib/python3.7/site-packages/sage/doctest/forker.py", line 681, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/amd/compute/sagebot/sage/local/lib/python3.7/site-packages/sage/doctest/forker.py", line 1123, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.schemes.elliptic_curves.isogeny_small_degree.isogenies_prime_degree_general[22]>", line 1, in <module>
        len(E.change_ring(GF(Integer(3)**Integer(2),'a')).isogenies_prime_degree(Integer(13)))
      File "/amd/compute/sagebot/sage/local/lib/python3.7/site-packages/sage/schemes/elliptic_curves/ell_field.py", line 1092, in isogenies_prime_degree
        return sum([isogenies_prime_degree(self, d) for d in L], [])
      File "/amd/compute/sagebot/sage/local/lib/python3.7/site-packages/sage/schemes/elliptic_curves/ell_field.py", line 1092, in <listcomp>
        return sum([isogenies_prime_degree(self, d) for d in L], [])
      File "/amd/compute/sagebot/sage/local/lib/python3.7/site-packages/sage/schemes/elliptic_curves/isogeny_small_degree.py", line 2360, in isogenies_prime_degree
        return isogenies_prime_degree_general(E,l, minimal_models=minimal_models)
      File "/amd/compute/sagebot/sage/local/lib/python3.7/site-packages/sage/schemes/elliptic_curves/isogeny_small_degree.py", line 2249, in isogenies_prime_degree_general
        factors.remove(f)
    ValueError: list.remove(x): x not in list
```

This fails frequently on the patchbot, but only rarely when testing the file standalone.

Component: **elliptic curves**

Keywords: **random_fail**

_Issue created by migration from https://trac.sagemath.org/ticket/29107_

**Comment by yyyyx4** [comment]
The code where the error happened was replaced as part of #37125, so I assume this issue has become obsolete.
