### ISSUE TITLE
Remove broken experimental package gambit

### ISSUE THREAD

**Issue by mkoeppe** [sagemath/sage#30156]
<div id="comment:0"></div>

It is not compatible with python 3.

https://github.com/mkoeppe/sage/runs/876312037

```
  [gambit-15.1.1.p0]   make[2]: Leaving directory '/sage/local/var/tmp/sage/build/gambit-15.1.1.p0/src'
  [gambit-15.1.1.p0]   Traceback (most recent call last):
  [gambit-15.1.1.p0]     File "setup.py", line 32, in <module>
  [gambit-15.1.1.p0]       m.Extension.__dict__ = m._Extension.__dict__
  [gambit-15.1.1.p0]   AttributeError: attribute '__dict__' of 'type' objects is not writable
  [gambit-15.1.1.p0]   Error installing Python API
  [gambit-15.1.1.p0]   
```

Another failure report: `cygwin` linking trouble - https://groups.google.com/g/sage-devel/c/HisDSCo7zlk/m/dAs5K5OrBwAJ

Upstream looks unattended. The last releases are from 2017.

https://github.com/gambitproject/gambit/issues

http://www.gambit-project.org/

https://github.com/gambitproject/gambit/pull/242

https://repology.org/project/gambit-game-theory/versions

Previous tickets: #24840, #24012

CC:  @dimpase @theref @kcrisman @nathanncohen @drvinceknight @tscrim @jhpalmieri

Component: **packages: experimental**

_Issue created by migration from https://trac.sagemath.org/ticket/30156_

**Comment by mkoeppe** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1,6 +1,11 @@
 It is not compatible with python 3.
 
-Upstream looks unattended. https://github.com/gambitproject/gambit/issues
+Upstream looks unattended. The last releases are from 2017.
+
+https://github.com/gambitproject/gambit/issues
+
+http://www.gambit-project.org/
+
 
 https://github.com/gambitproject/gambit/pull/242
 
``````

**Comment by mkoeppe** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1,4 +1,17 @@
 It is not compatible with python 3.
+
+https://github.com/mkoeppe/sage/runs/876312037
+
+```
+  [gambit-15.1.1.p0]   make[2]: Leaving directory '/sage/local/var/tmp/sage/build/gambit-15.1.1.p0/src'
+  [gambit-15.1.1.p0]   Traceback (most recent call last):
+  [gambit-15.1.1.p0]     File "setup.py", line 32, in <module>
+  [gambit-15.1.1.p0]       m.Extension.__dict__ = m._Extension.__dict__
+  [gambit-15.1.1.p0]   AttributeError: attribute '__dict__' of 'type' objects is not writable
+  [gambit-15.1.1.p0]   Error installing Python API
+  [gambit-15.1.1.p0]   
+```
+
 
 Upstream looks unattended. The last releases are from 2017.
 
``````

**Comment by mkoeppe** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -12,6 +12,7 @@
   [gambit-15.1.1.p0]   
 ```
 
+Another failure report: `cygwin` linking trouble - https://groups.google.com/g/sage-devel/c/HisDSCo7zlk/m/dAs5K5OrBwAJ
 
 Upstream looks unattended. The last releases are from 2017.
 
``````

**Comment by mkoeppe** [comment]
It's 2024 and gambit is back: http://www.gambit-project.org/, including `pygambit`, supporting Python >= 3.8 - https://pypi.org/project/pygambit/#history

**Comment by mkoeppe** [comment]
Closing in favor of:
- #37809
