### ISSUE TITLE
Update mistune to 2.0

### ISSUE THREAD

**Issue by tobihan** [sagemath/sage#33018]
<div id="comment:0"></div>

In Debian with mistune 2.0 when trying to start a notebook with sagemath kernel I am getting "500 : Internal Server Error" and the following error in the terminal:

```
Uncaught exception GET /notebooks/Untitled.ipynb?kernel_name=sagemath (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/notebooks/Untitled.ipynb?kernel_name=sagemath', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/tornado/web.py", line 1704, in _execute
        result = await result
      File "/usr/lib/python3/dist-packages/tornado/gen.py", line 775, in run
        yielded = self.gen.send(value)
      File "/usr/lib/python3/dist-packages/notebook/notebook/handlers.py", line 95, in get
        self.write(self.render_template('notebook.html',
      File "/usr/lib/python3/dist-packages/notebook/base/handlers.py", line 516, in render_template
        return template.render(**ns)
      File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1304, in render
        self.environment.handle_exception()
      File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 925, in handle_exception
        raise rewrite_traceback_stack(source=source)
      File "/usr/lib/python3/dist-packages/notebook/templates/notebook.html", line 1, in top-level template code
        {% extends "page.html" %}
      File "/usr/lib/python3/dist-packages/notebook/templates/page.html", line 153, in top-level template code
        {% block header %}
      File "/usr/lib/python3/dist-packages/notebook/templates/notebook.html", line 115, in block 'header'
        {% for exporter in get_frontend_exporters() %}
      File "/usr/lib/python3/dist-packages/notebook/notebook/handlers.py", line 23, in get_frontend_exporters
        from nbconvert.exporters.base import get_export_names, get_exporter
      File "/usr/lib/python3/dist-packages/nbconvert/__init__.py", line 4, in <module>
        from .exporters import *
      File "/usr/lib/python3/dist-packages/nbconvert/exporters/__init__.py", line 3, in <module>
        from .html import HTMLExporter
      File "/usr/lib/python3/dist-packages/nbconvert/exporters/html.py", line 18, in <module>
        from nbconvert.filters.highlight import Highlight2HTML
      File "/usr/lib/python3/dist-packages/nbconvert/filters/__init__.py", line 6, in <module>
        from .markdown import *
      File "/usr/lib/python3/dist-packages/nbconvert/filters/markdown.py", line 13, in <module>
        from .markdown_mistune import markdown2html_mistune
      File "/usr/lib/python3/dist-packages/nbconvert/filters/markdown_mistune.py", line 31, in <module>
        class MathBlockGrammar(mistune.BlockGrammar):
    AttributeError: module 'mistune' has no attribute 'BlockGrammar'
```

Upstream: **Reported upstream. No feedback yet.**

CC:  @kiwifb @antonio-rojas

Component: **packages: standard**

Reviewer: **François Bissey**

_Issue created by migration from https://trac.sagemath.org/ticket/33018_

**Comment by tobihan** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1,4 +1,4 @@
-In Debian with mistune 2.0 I am getting the following error when trying to start a notebook with sagemath kernel I am getting "500 : Internal Server Error" and the following error in the terminal:
+In Debian with mistune 2.0 when trying to start a notebook with sagemath kernel I am getting "500 : Internal Server Error" and the following error in the terminal:
 
 ```
 Uncaught exception GET /notebooks/Untitled.ipynb?kernel_name=sagemath (127.0.0.1)
``````

**Comment by mkoeppe** [comment]
<div id="comment:7" align="right">comment:7</div>

Outdated. Our current version of mistune is already 2.0.4

**Comment by kiwifb** [comment]
Reviewer: **François Bissey**
