### ISSUE TITLE
ipython/SQLite errors when running multiple sessions

### ISSUE THREAD

**Issue by orlitzky** [sagemath/sage#33025]
<div id="comment:0"></div>

I pretty regularly run multiple sage instances. Today I tried it with 9.5.beta8 for the first time and got,

```
$ sage
┌────────────────────────────────────────────────────────────────────┐
│ SageMath version 9.5.beta8, Release Date: 2021-12-12               │
│ Using Python 3.9.9. Type "help()" for help.                        │
└────────────────────────────────────────────────────────────────────┘
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Warning: this is a prerelease version, and it may be unstable.     ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
[SageTerminalApp] ERROR | Failed to create history session in /home/mjo/.sage/ipython-5.0.0/profile_default/history.sqlite. History will not be saved.
Traceback (most recent call last):
  File "/home/mjo/src/sage.git/local/var/lib/sage/venv-python3.9/lib/python3.9/site-packages/IPython/core/history.py", line 543, in __init__
    self.new_session()
  File "<decorator-gen-15>", line 2, in new_session
  File "/home/mjo/src/sage.git/local/var/lib/sage/venv-python3.9/lib/python3.9/site-packages/IPython/core/history.py", line 58, in needs_sqlite
    return f(self, *a, **kw)
  File "/home/mjo/src/sage.git/local/var/lib/sage/venv-python3.9/lib/python3.9/site-packages/IPython/core/history.py", line 568, in new_session
    cur = conn.execute("""INSERT INTO sessions VALUES (NULL, ?, NULL,
sqlite3.OperationalError: database is locked
```

Then upon exiting,

```
sage: exit
Exiting Sage (CPU time 0m0.41s, Wall time 0m1.44s).
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/mjo/src/sage.git/local/var/lib/sage/venv-python3.9/lib/python3.9/site-packages/IPython/core/history.py", line 576, in end_session
    self.db.execute("""UPDATE sessions SET end=?, num_cmds=? WHERE
sqlite3.OperationalError: database is locked
```

I don't think we need to display that. Running multiple instances of something (like bash itself) that accesses a single history file has always been caveat emptor.

Component: **user interface**

_Issue created by migration from https://trac.sagemath.org/ticket/33025_

**Comment by orlitzky** [comment]
This went away at some point :shrug:
