### ISSUE TITLE
Random failure in cycliccover_finite_field.py

### ISSUE THREAD

**Issue by vbraun** [sagemath/sage#33304]
<div id="comment:0"></div>

Non-reproducible random failures with the following traceback:

```
**********************************************************************
File "src/sage/schemes/cyclic_covers/cycliccover_finite_field.py", line 1138, in sage.schemes.cyclic_covers.cycliccover_finite_field.CyclicCover_finite_field.frobenius_polynomial
Failed example:
    CyclicCover(11, PolynomialRing(GF(1129), 'x')([-1] + [0]*(5-1) + [1])).frobenius_polynomial() # long time
Exception raised:
    Traceback (most recent call last):
      File "sage/misc/cachefunc.pyx", line 1943, in sage.misc.cachefunc.CachedMethodCaller.__call__ (build/cythonized/sage/misc/cachefunc.c:10410)
        return cache[k]
    KeyError: ((11,), ())
    During handling of the above exception, another exception occurred:
    Traceback (most recent call last):
      File "/Users/buildbot-sage/worker/sage_git/build/local/var/lib/sage/venv-python3.9.9/lib/python3.9/site-packages/sage/doctest/forker.py", line 694, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/Users/buildbot-sage/worker/sage_git/build/local/var/lib/sage/venv-python3.9.9/lib/python3.9/site-packages/sage/doctest/forker.py", line 1088, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.schemes.cyclic_covers.cycliccover_finite_field.CyclicCover_finite_field.frobenius_polynomial[23]>", line 1, in <module>
        CyclicCover(Integer(11), PolynomialRing(GF(Integer(1129)), 'x')([-Integer(1)] + [Integer(0)]*(Integer(5)-Integer(1)) + [Integer(1)])).frobenius_polynomial() # long time
      File "sage/misc/cachefunc.pyx", line 2310, in sage.misc.cachefunc.CachedMethodCallerNoArgs.__call__ (build/cythonized/sage/misc/cachefunc.c:13020)
        self.cache = f(self._instance)
      File "/Users/buildbot-sage/worker/sage_git/build/local/var/lib/sage/venv-python3.9.9/lib/python3.9/site-packages/sage/schemes/cyclic_covers/cycliccover_finite_field.py", line 1233, in frobenius_polynomial
        F = self.frobenius_matrix(self._N0)
      File "sage/misc/cachefunc.pyx", line 1948, in sage.misc.cachefunc.CachedMethodCaller.__call__ (build/cythonized/sage/misc/cachefunc.c:10546)
        w = self._instance_call(*args, **kwds)
      File "sage/misc/cachefunc.pyx", line 1824, in sage.misc.cachefunc.CachedMethodCaller._instance_call (build/cythonized/sage/misc/cachefunc.c:10012)
        return self.f(self._instance, *args, **kwds)
      File "/Users/buildbot-sage/worker/sage_git/build/local/var/lib/sage/venv-python3.9.9/lib/python3.9/site-packages/sage/schemes/cyclic_covers/cycliccover_finite_field.py", line 1071, in frobenius_matrix
        FrobP = _frobenius_matrix_p(self._N0)
      File "/Users/buildbot-sage/worker/sage_git/build/local/var/lib/sage/venv-python3.9.9/lib/python3.9/site-packages/sage/schemes/cyclic_covers/cycliccover_finite_field.py", line 1067, in _frobenius_matrix_p
        ] = self._frob(i, j + self._epsilon * self._r, N0)
      File "/Users/buildbot-sage/worker/sage_git/build/local/var/lib/sage/venv-python3.9.9/lib/python3.9/site-packages/sage/schemes/cyclic_covers/cycliccover_finite_field.py", line 993, in _frob
        self._initialize_fat_horizontal(
      File "/Users/buildbot-sage/worker/sage_git/build/local/var/lib/sage/venv-python3.9.9/lib/python3.9/site-packages/sage/schemes/cyclic_covers/cycliccover_finite_field.py", line 737, in _initialize_fat_horizontal
        DH = [elt[0, 0] for elt in interval_products(D0, D1, targets)]
      File "sage/schemes/hyperelliptic_curves/hypellfrob.pyx", line 140, in sage.schemes.hyperelliptic_curves.hypellfrob.interval_products (build/cythonized/sage/schemes/hyperelliptic_curves/hypellfrob.cpp:3997)
        sig_on()
    SystemError: calling remove_from_pari_stack() inside sig_on()
**********************************************************************
1 item had failures:
   1 of  60 in sage.schemes.cyclic_covers.cycliccover_finite_field.CyclicCover_finite_field.frobenius_polynomial
    [168 tests, 1 failure, 64.56 s]
----------------------------------------------------------------------
sage -t --long --random-seed=0 src/sage/schemes/cyclic_covers/cycliccover_finite_field.py  # 1 doctest failed
----------------------------------------------------------------------
```

CC:  @kiwifb

Component: **geometry**

Keywords: **random_fail**

_Issue created by migration from https://trac.sagemath.org/ticket/33304_

**Comment by vbraun** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1,6 +1,7 @@
 Non-reproducible random failures with the following traceback:
 
 ```
+**********************************************************************
 File "src/sage/schemes/cyclic_covers/cycliccover_finite_field.py", line 1138, in sage.schemes.cyclic_covers.cycliccover_finite_field.CyclicCover_finite_field.frobenius_polynomial
 Failed example:
     CyclicCover(11, PolynomialRing(GF(1129), 'x')([-1] + [0]*(5-1) + [1])).frobenius_polynomial() # long time
@@ -24,4 +25,23 @@
       File "sage/misc/cachefunc.pyx", line 1948, in sage.misc.cachefunc.CachedMethodCaller.__call__ (build/cythonized/sage/misc/cachefunc.c:10546)
         w = self._instance_call(*args, **kwds)
       File "sage/misc/cachefunc.pyx", line 1824, in sage.misc.cachefunc.CachedMethodCaller._instance_call (build/cythonized/sage/misc/cachefunc.c:10012)
+        return self.f(self._instance, *args, **kwds)
+      File "/Users/buildbot-sage/worker/sage_git/build/local/var/lib/sage/venv-python3.9.9/lib/python3.9/site-packages/sage/schemes/cyclic_covers/cycliccover_finite_field.py", line 1071, in frobenius_matrix
+        FrobP = _frobenius_matrix_p(self._N0)
+      File "/Users/buildbot-sage/worker/sage_git/build/local/var/lib/sage/venv-python3.9.9/lib/python3.9/site-packages/sage/schemes/cyclic_covers/cycliccover_finite_field.py", line 1067, in _frobenius_matrix_p
+        ] = self._frob(i, j + self._epsilon * self._r, N0)
+      File "/Users/buildbot-sage/worker/sage_git/build/local/var/lib/sage/venv-python3.9.9/lib/python3.9/site-packages/sage/schemes/cyclic_covers/cycliccover_finite_field.py", line 993, in _frob
+        self._initialize_fat_horizontal(
+      File "/Users/buildbot-sage/worker/sage_git/build/local/var/lib/sage/venv-python3.9.9/lib/python3.9/site-packages/sage/schemes/cyclic_covers/cycliccover_finite_field.py", line 737, in _initialize_fat_horizontal
+        DH = [elt[0, 0] for elt in interval_products(D0, D1, targets)]
+      File "sage/schemes/hyperelliptic_curves/hypellfrob.pyx", line 140, in sage.schemes.hyperelliptic_curves.hypellfrob.interval_products (build/cythonized/sage/schemes/hyperelliptic_curves/hypellfrob.cpp:3997)
+        sig_on()
+    SystemError: calling remove_from_pari_stack() inside sig_on()
+**********************************************************************
+1 item had failures:
+   1 of  60 in sage.schemes.cyclic_covers.cycliccover_finite_field.CyclicCover_finite_field.frobenius_polynomial
+    [168 tests, 1 failure, 64.56 s]
+----------------------------------------------------------------------
+sage -t --long --random-seed=0 src/sage/schemes/cyclic_covers/cycliccover_finite_field.py  # 1 doctest failed
+----------------------------------------------------------------------
 ```
``````
