### ISSUE TITLE
search functionality of doc.sagemath.org is broken

### ISSUE THREAD

**Issue by williamstein** [sagemath/sage#33832]
<div id="comment:0"></div>

Click here to see -- https://doc.sagemath.org/html/en/reference/search.html?q=plot

The console.log shows:

```
Uncaught ReferenceError: Stemmer is not defined
    at Object.query (searchtools.js:158:19)
    at Object.setIndex (searchtools.js:98:14)
    at <anonymous>:1:8
    at b (jquery.js:2:839)
    at Function.globalEval (jquery.js:2:2878)
    at text script (jquery.js:2:82979)
    at jquery.js:2:79369
    at l (jquery.js:2:79486)
    at XMLHttpRequest.<anonymous> (jquery.js:2:82254)
```

CC:  @haraldschilly

Component: **documentation**

_Issue created by migration from https://trac.sagemath.org/ticket/33832_

**Comment by mkoeppe** [comment]
worksforme
