### ISSUE TITLE
cygwin: ECL says: The function SET-LOCALE-SUBDIR is undefined

### ISSUE THREAD

**Issue by mkoeppe** [sagemath/sage#34127]
<div id="comment:0"></div>

In a run with #34088:

https://github.com/mkoeppe/sage/runs/7230043805?check_suite_focus=true

```
      File "sage/misc/lazy_import.pyx", line 253, in sage.misc.lazy_import.LazyImport._get_object (build/cythonized/sage/misc/lazy_import.c:2942)
        self._object = getattr(__import__(self._module, {}, {}, [self._name]), self._name)
      File "/opt/sage-f37e7774f3c3239a8411c8e418e1dd59a32a462e/lib/python3.9/site-packages/sage/interfaces/maxima_lib.py", line 118, in <module>
        ecl_eval("(set-locale-subdir)")
      File "sage/libs/ecl.pyx", line 1352, in sage.libs.ecl.ecl_eval (build/cythonized/sage/libs/ecl.c:10870)
        cpdef EclObject ecl_eval(str s):
      File "sage/libs/ecl.pyx", line 1375, in sage.libs.ecl.ecl_eval (build/cythonized/sage/libs/ecl.c:10803)
        o=ecl_safe_eval(python_to_ecl(s, True))
      File "sage/libs/ecl.pyx", line 321, in sage.libs.ecl.ecl_safe_eval (build/cythonized/sage/libs/ecl.c:5585)
        raise RuntimeError("ECL says: {}".format(message))
    RuntimeError: ECL says: The function SET-LOCALE-SUBDIR is undefined.
```

And other errors:

```
File "src/doc/de/thematische_anleitungen/sage_gymnasium.rst", line 386, in doc.de.thematische_anleitungen.sage_gymnasium
Failed example:
    (sin(x)^2 + cos(x)^2).simplify_full()
Exception raised:
    Traceback (most recent call last):
      File "/opt/sage-f37e7774f3c3239a8411c8e418e1dd59a32a462e/lib/python3.9/site-packages/sage/doctest/forker.py", line 695, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/opt/sage-f37e7774f3c3239a8411c8e418e1dd59a32a462e/lib/python3.9/site-packages/sage/doctest/forker.py", line 1093, in compile_and_execute
        exec(compiled, globs)
      File "<doctest doc.de.thematische_anleitungen.sage_gymnasium[0]>", line 1, in <module>
        (sin(x)**Integer(2) + cos(x)**Integer(2)).simplify_full()
      File "sage/symbolic/expression.pyx", line 10694, in sage.symbolic.expression.Expression.simplify_full (build/cythonized/sage/symbolic/expression.cpp:82459)
        x = x.simplify_factorial()
      File "sage/symbolic/expression.pyx", line 11174, in sage.symbolic.expression.Expression.simplify_factorial (build/cythonized/sage/symbolic/expression.cpp:85545)
        return self.parent()(self._maxima_().makefact().factcomb().minfactorial())
      File "sage/symbolic/expression.pyx", line 1234, in sage.symbolic.expression.Expression._maxima_ (build/cythonized/sage/symbolic/expression.cpp:35978)
        return super(Expression, self)._interface_(maxima)
      File "sage/structure/sage_object.pyx", line 683, in sage.structure.sage_object.SageObject._interface_ (build/cythonized/sage/structure/sage_object.c:5661)
        nm = I.name()
      File "sage/misc/lazy_import.pyx", line 359, in sage.misc.lazy_import.LazyImport.__getattr__ (build/cythonized/sage/misc/lazy_import.c:4086)
        return getattr(self.get_object(), attr)
      File "sage/misc/lazy_import.pyx", line 217, in sage.misc.lazy_import.LazyImport.get_object (build/cythonized/sage/misc/lazy_import.c:2619)
        return self._get_object()
      File "sage/misc/lazy_import.pyx", line 253, in sage.misc.lazy_import.LazyImport._get_object (build/cythonized/sage/misc/lazy_import.c:2942)
        self._object = getattr(__import__(self._module, {}, {}, [self._name]), self._name)
      File "/opt/sage-f37e7774f3c3239a8411c8e418e1dd59a32a462e/lib/python3.9/site-packages/sage/interfaces/maxima_lib.py", line 112, in <module>
        ecl_eval("(require 'maxima \"{}\")".format(MAXIMA_FAS))
      File "sage/libs/ecl.pyx", line 1352, in sage.libs.ecl.ecl_eval (build/cythonized/sage/libs/ecl.c:10870)
        cpdef EclObject ecl_eval(str s):
      File "sage/libs/ecl.pyx", line 1375, in sage.libs.ecl.ecl_eval (build/cythonized/sage/libs/ecl.c:10803)
        o=ecl_safe_eval(python_to_ecl(s, True))
      File "sage/libs/ecl.pyx", line 321, in sage.libs.ecl.ecl_safe_eval (build/cythonized/sage/libs/ecl.c:5585)
        raise RuntimeError("ECL says: {}".format(message))
    RuntimeError: ECL says: When trying to rename "/tmp/eclHTISno", "/tmp/eclHTISno.dll" already exists
```

```
sage -t --random-seed=11839607223460551261423219577271154635 src/sage/interfaces/giac.py
**********************************************************************
File "src/sage/interfaces/giac.py", line 584, in sage.interfaces.giac.Giac.cputime
Failed example:
    t = giac.cputime()
Exception raised:
    Traceback (most recent call last):
      File "/opt/sage-f37e7774f3c3239a8411c8e418e1dd59a32a462e/lib/python3.9/site-packages/sage/doctest/forker.py", line 695, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/opt/sage-f37e7774f3c3239a8411c8e418e1dd59a32a462e/lib/python3.9/site-packages/sage/doctest/forker.py", line 1093, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.interfaces.giac.Giac.cputime[0]>", line 1, in <module>
        t = giac.cputime()
      File "/opt/sage-f37e7774f3c3239a8411c8e418e1dd59a32a462e/lib/python3.9/site-packages/sage/interfaces/giac.py", line 594, in cputime
        return float(self('time()'))
      File "/opt/sage-f37e7774f3c3239a8411c8e418e1dd59a32a462e/lib/python3.9/site-packages/sage/interfaces/giac.py", line 858, in __float__
        return float(giac.eval('evalf(%s)' % self.name()))
      File "/opt/sage-f37e7774f3c3239a8411c8e418e1dd59a32a462e/lib/python3.9/site-packages/sage/interfaces/giac.py", line 652, in eval
        return Expect.eval(self, code, strip=strip, **kwds).strip()
      File "/opt/sage-f37e7774f3c3239a8411c8e418e1dd59a32a462e/lib/python3.9/site-packages/sage/interfaces/expect.py", line 1387, in eval
        return '\n'.join([self._eval_line(L, allow_use_file=allow_use_file, **kwds)
      File "/opt/sage-f37e7774f3c3239a8411c8e418e1dd59a32a462e/lib/python3.9/site-packages/sage/interfaces/expect.py", line 1387, in <listcomp>
        return '\n'.join([self._eval_line(L, allow_use_file=allow_use_file, **kwds)
      File "/opt/sage-f37e7774f3c3239a8411c8e418e1dd59a32a462e/lib/python3.9/site-packages/sage/interfaces/giac.py", line 620, in _eval_line
        raise RuntimeError("an error occurred running a Giac command:\nINPUT:\n%s\nOUTPUT:\n%s" % (line, z))
    RuntimeError: an error occurred running a Giac command:
    INPUT:
    evalf(sage117)
    OUTPUT:
    :3: syntax error  at end of input
    :3: syntax error  at end of input
    undef
```

Component: **porting: Cygwin**

_Issue created by migration from https://trac.sagemath.org/ticket/34127_

**Comment by mkoeppe** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -14,3 +14,42 @@
     RuntimeError: ECL says: The function SET-LOCALE-SUBDIR is undefined.
 ```
 
+And other errors:
+
+```
+File "src/doc/de/thematische_anleitungen/sage_gymnasium.rst", line 386, in doc.de.thematische_anleitungen.sage_gymnasium
+Failed example:
+    (sin(x)^2 + cos(x)^2).simplify_full()
+Exception raised:
+    Traceback (most recent call last):
+      File "/opt/sage-f37e7774f3c3239a8411c8e418e1dd59a32a462e/lib/python3.9/site-packages/sage/doctest/forker.py", line 695, in _run
+        self.compile_and_execute(example, compiler, test.globs)
+      File "/opt/sage-f37e7774f3c3239a8411c8e418e1dd59a32a462e/lib/python3.9/site-packages/sage/doctest/forker.py", line 1093, in compile_and_execute
+        exec(compiled, globs)
+      File "<doctest doc.de.thematische_anleitungen.sage_gymnasium[0]>", line 1, in <module>
+        (sin(x)**Integer(2) + cos(x)**Integer(2)).simplify_full()
+      File "sage/symbolic/expression.pyx", line 10694, in sage.symbolic.expression.Expression.simplify_full (build/cythonized/sage/symbolic/expression.cpp:82459)
+        x = x.simplify_factorial()
+      File "sage/symbolic/expression.pyx", line 11174, in sage.symbolic.expression.Expression.simplify_factorial (build/cythonized/sage/symbolic/expression.cpp:85545)
+        return self.parent()(self._maxima_().makefact().factcomb().minfactorial())
+      File "sage/symbolic/expression.pyx", line 1234, in sage.symbolic.expression.Expression._maxima_ (build/cythonized/sage/symbolic/expression.cpp:35978)
+        return super(Expression, self)._interface_(maxima)
+      File "sage/structure/sage_object.pyx", line 683, in sage.structure.sage_object.SageObject._interface_ (build/cythonized/sage/structure/sage_object.c:5661)
+        nm = I.name()
+      File "sage/misc/lazy_import.pyx", line 359, in sage.misc.lazy_import.LazyImport.__getattr__ (build/cythonized/sage/misc/lazy_import.c:4086)
+        return getattr(self.get_object(), attr)
+      File "sage/misc/lazy_import.pyx", line 217, in sage.misc.lazy_import.LazyImport.get_object (build/cythonized/sage/misc/lazy_import.c:2619)
+        return self._get_object()
+      File "sage/misc/lazy_import.pyx", line 253, in sage.misc.lazy_import.LazyImport._get_object (build/cythonized/sage/misc/lazy_import.c:2942)
+        self._object = getattr(__import__(self._module, {}, {}, [self._name]), self._name)
+      File "/opt/sage-f37e7774f3c3239a8411c8e418e1dd59a32a462e/lib/python3.9/site-packages/sage/interfaces/maxima_lib.py", line 112, in <module>
+        ecl_eval("(require 'maxima \"{}\")".format(MAXIMA_FAS))
+      File "sage/libs/ecl.pyx", line 1352, in sage.libs.ecl.ecl_eval (build/cythonized/sage/libs/ecl.c:10870)
+        cpdef EclObject ecl_eval(str s):
+      File "sage/libs/ecl.pyx", line 1375, in sage.libs.ecl.ecl_eval (build/cythonized/sage/libs/ecl.c:10803)
+        o=ecl_safe_eval(python_to_ecl(s, True))
+      File "sage/libs/ecl.pyx", line 321, in sage.libs.ecl.ecl_safe_eval (build/cythonized/sage/libs/ecl.c:5585)
+        raise RuntimeError("ECL says: {}".format(message))
+    RuntimeError: ECL says: When trying to rename "/tmp/eclHTISno", "/tmp/eclHTISno.dll" already exists
+```
+
``````

**Comment by mkoeppe** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1,3 +1,5 @@
+In a run with #34088:
+
 https://github.com/mkoeppe/sage/runs/7230043805?check_suite_focus=true
 
 ```
``````

**Comment by mkoeppe** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -55,3 +55,37 @@
     RuntimeError: ECL says: When trying to rename "/tmp/eclHTISno", "/tmp/eclHTISno.dll" already exists
 ```
 
+```
+sage -t --random-seed=11839607223460551261423219577271154635 src/sage/interfaces/giac.py
+**********************************************************************
+File "src/sage/interfaces/giac.py", line 584, in sage.interfaces.giac.Giac.cputime
+Failed example:
+    t = giac.cputime()
+Exception raised:
+    Traceback (most recent call last):
+      File "/opt/sage-f37e7774f3c3239a8411c8e418e1dd59a32a462e/lib/python3.9/site-packages/sage/doctest/forker.py", line 695, in _run
+        self.compile_and_execute(example, compiler, test.globs)
+      File "/opt/sage-f37e7774f3c3239a8411c8e418e1dd59a32a462e/lib/python3.9/site-packages/sage/doctest/forker.py", line 1093, in compile_and_execute
+        exec(compiled, globs)
+      File "<doctest sage.interfaces.giac.Giac.cputime[0]>", line 1, in <module>
+        t = giac.cputime()
+      File "/opt/sage-f37e7774f3c3239a8411c8e418e1dd59a32a462e/lib/python3.9/site-packages/sage/interfaces/giac.py", line 594, in cputime
+        return float(self('time()'))
+      File "/opt/sage-f37e7774f3c3239a8411c8e418e1dd59a32a462e/lib/python3.9/site-packages/sage/interfaces/giac.py", line 858, in __float__
+        return float(giac.eval('evalf(%s)' % self.name()))
+      File "/opt/sage-f37e7774f3c3239a8411c8e418e1dd59a32a462e/lib/python3.9/site-packages/sage/interfaces/giac.py", line 652, in eval
+        return Expect.eval(self, code, strip=strip, **kwds).strip()
+      File "/opt/sage-f37e7774f3c3239a8411c8e418e1dd59a32a462e/lib/python3.9/site-packages/sage/interfaces/expect.py", line 1387, in eval
+        return '\n'.join([self._eval_line(L, allow_use_file=allow_use_file, **kwds)
+      File "/opt/sage-f37e7774f3c3239a8411c8e418e1dd59a32a462e/lib/python3.9/site-packages/sage/interfaces/expect.py", line 1387, in <listcomp>
+        return '\n'.join([self._eval_line(L, allow_use_file=allow_use_file, **kwds)
+      File "/opt/sage-f37e7774f3c3239a8411c8e418e1dd59a32a462e/lib/python3.9/site-packages/sage/interfaces/giac.py", line 620, in _eval_line
+        raise RuntimeError("an error occurred running a Giac command:\nINPUT:\n%s\nOUTPUT:\n%s" % (line, z))
+    RuntimeError: an error occurred running a Giac command:
+    INPUT:
+    evalf(sage117)
+    OUTPUT:
+    :3: syntax error  at end of input
+    :3: syntax error  at end of input
+    undef
+```
``````
