### ISSUE TITLE
Support matplotlib 3.6

### ISSUE THREAD

**Issue by tornaria** [sagemath/sage#34668]
<div id="comment:0"></div>

Currently there are a number of doctest failures when running sage with matplotlib 3.6, mostly deprecation warnings.

The current ticket is small and simple, it will make all tests pass with matplotlib 3.6, and it is backwards compatible.

Component: **packages: standard**

Author: **Gonzalo Tornaría**

Branch: **[`5501e0d`](https://github.com/sagemath/sagetrac-mirror/commit/5501e0de0dca1cff0355326dd42bd8c7e5749568)**

Reviewer: **Matthias Koeppe**

_Issue created by migration from https://trac.sagemath.org/ticket/34668_

**Comment by tornaria** [comment]
Commit: **[`5501e0d`](https://github.com/sagemath/sagetrac-mirror/commit/5501e0de0dca1cff0355326dd42bd8c7e5749568)**

**Comment by tornaria** [comment]
<div id="comment:1"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/5501e0de0dca1cff0355326dd42bd8c7e5749568"><code>5501e0d</code></a></td><td><code>Support matplotlib 3.6</code></td></tr></table>

**Comment by tornaria** [comment]
Branch: **[u/tornaria/matplotlib-3.6](https://github.com/sagemath/sagetrac-mirror/tree/u/tornaria/matplotlib-3.6)**

**Comment by mkoeppe** [comment]
Reviewer: **Matthias Koeppe**

**Comment by vbraun** [comment]
Changed branch from **[u/tornaria/matplotlib-3.6](https://github.com/sagemath/sagetrac-mirror/tree/u/tornaria/matplotlib-3.6)** to **[`5501e0d`](https://github.com/sagemath/sagetrac-mirror/commit/5501e0de0dca1cff0355326dd42bd8c7e5749568)**

**Comment by kiwifb** [comment]
Changed commit from **[`5501e0d`](https://github.com/sagemath/sagetrac-mirror/commit/5501e0de0dca1cff0355326dd42bd8c7e5749568)** to none

**Comment by kiwifb** [comment]
<div id="comment:4" align="right">comment:4</div>

Those changes are not enough to build the documentation with matplotlib 3.6.1, unless I miss another needed element

```
[plotting ]  from /home/portage/sci-mathematics/sage-doc-9999/work/sage-doc-9999/src/doc/en/reference/plotting/sage/plot/plot.rst:
[plotting ] Traceback (most recent call last):
[plotting ]   File "/usr/lib/python3.10/site-packages/matplotlib/artist.py", line 1378, in _get_tightbbox_for_layout_only
[plotting ]     return obj.get_tightbbox(*args, **{**kwargs, "for_layout_only": True})
[plotting ]   File "/usr/lib/python3.10/site-packages/matplotlib/axis.py", line 1251, in get_tightbbox
[plotting ]     ticks_to_draw = self._update_ticks()
[plotting ]   File "/usr/lib/python3.10/site-packages/matplotlib/axis.py", line 1198, in _update_ticks
[plotting ]     minor_locs = self.get_minorticklocs()
[plotting ]   File "/usr/lib/python3.10/site-packages/matplotlib/axis.py", line 1431, in get_minorticklocs
[plotting ]     mask = np.isclose(tr_minor_locs[:, None], tr_major_locs[None, :],
[plotting ]   File "<__array_function__ internals>", line 180, in isclose
[plotting ]   File "/usr/lib/python3.10/site-packages/numpy/core/numeric.py", line 2373, in isclose
[plotting ]     yfin = isfinite(y)
[plotting ] TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
[plotting ] During handling of the above exception, another exception occurred:
[plotting ] Traceback (most recent call last):
[plotting ]   File "/usr/lib/python3.10/site-packages/matplotlib/artist.py", line 1378, in _get_tightbbox_for_layout_only
[plotting ]     return obj.get_tightbbox(*args, **{**kwargs, "for_layout_only": True})
[plotting ]   File "/usr/lib/python3.10/site-packages/matplotlib/axes/_base.py", line 4428, in get_tightbbox
[plotting ]     ba = martist._get_tightbbox_for_layout_only(axis, renderer)
[plotting ]   File "/usr/lib/python3.10/site-packages/matplotlib/artist.py", line 1380, in _get_tightbbox_for_layout_only
[plotting ]     return obj.get_tightbbox(*args, **kwargs)
[plotting ]   File "/usr/lib/python3.10/site-packages/matplotlib/axis.py", line 1251, in get_tightbbox
[plotting ]     ticks_to_draw = self._update_ticks()
[plotting ]   File "/usr/lib/python3.10/site-packages/matplotlib/axis.py", line 1198, in _update_ticks
[plotting ]     minor_locs = self.get_minorticklocs()
[plotting ]   File "/usr/lib/python3.10/site-packages/matplotlib/axis.py", line 1431, in get_minorticklocs
[plotting ]     mask = np.isclose(tr_minor_locs[:, None], tr_major_locs[None, :],
[plotting ]   File "<__array_function__ internals>", line 180, in isclose
[plotting ]   File "/usr/lib/python3.10/site-packages/numpy/core/numeric.py", line 2373, in isclose
[plotting ]     yfin = isfinite(y)
[plotting ] TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
[plotting ] During handling of the above exception, another exception occurred:
[plotting ] Traceback (most recent call last):
[plotting ]   File "/usr/lib/python3.10/site-packages/matplotlib/artist.py", line 1378, in _get_tightbbox_for_layout_only
[plotting ]     return obj.get_tightbbox(*args, **{**kwargs, "for_layout_only": True})
[plotting ]   File "/usr/lib/python3.10/site-packages/matplotlib/axis.py", line 1251, in get_tightbbox
[plotting ]     ticks_to_draw = self._update_ticks()
[plotting ]   File "/usr/lib/python3.10/site-packages/matplotlib/axis.py", line 1198, in _update_ticks
[plotting ]     minor_locs = self.get_minorticklocs()
[plotting ]   File "/usr/lib/python3.10/site-packages/matplotlib/axis.py", line 1431, in get_minorticklocs
[plotting ]     mask = np.isclose(tr_minor_locs[:, None], tr_major_locs[None, :],
[plotting ]   File "<__array_function__ internals>", line 180, in isclose
[plotting ]   File "/usr/lib/python3.10/site-packages/numpy/core/numeric.py", line 2373, in isclose
[plotting ]     yfin = isfinite(y)
[plotting ] TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
[plotting ] During handling of the above exception, another exception occurred:
[plotting ] Traceback (most recent call last):
[plotting ]   File "/usr/lib/python3.10/site-packages/matplotlib/sphinxext/plot_directive.py", line 515, in _run_code
[plotting ]     exec(code, ns)
[plotting ]   File "<string>", line 2, in <module>
[plotting ]   File "<string>", line 37, in sphinx_plot
[plotting ]   File "/usr/lib/python3.10/site-packages/matplotlib/figure.py", line 3448, in tight_layout
[plotting ]     engine.execute(self)
[plotting ]   File "/usr/lib/python3.10/site-packages/matplotlib/layout_engine.py", line 180, in execute
[plotting ]     kwargs = get_tight_layout_figure(
[plotting ]   File "/usr/lib/python3.10/site-packages/matplotlib/_tight_layout.py", line 305, in get_tight_layout_figure
[plotting ]     kwargs = _auto_adjust_subplotpars(fig, renderer,
[plotting ]   File "/usr/lib/python3.10/site-packages/matplotlib/_tight_layout.py", line 82, in _auto_adjust_subplotpars
[plotting ]     bb += [martist._get_tightbbox_for_layout_only(ax, renderer)]
[plotting ]   File "/usr/lib/python3.10/site-packages/matplotlib/artist.py", line 1380, in _get_tightbbox_for_layout_only
[plotting ]     return obj.get_tightbbox(*args, **kwargs)
[plotting ]   File "/usr/lib/python3.10/site-packages/matplotlib/axes/_base.py", line 4428, in get_tightbbox
[plotting ]     ba = martist._get_tightbbox_for_layout_only(axis, renderer)
[plotting ]   File "/usr/lib/python3.10/site-packages/matplotlib/artist.py", line 1380, in _get_tightbbox_for_layout_only
[plotting ]     return obj.get_tightbbox(*args, **kwargs)
[plotting ]   File "/usr/lib/python3.10/site-packages/matplotlib/axis.py", line 1251, in get_tightbbox
[plotting ]     ticks_to_draw = self._update_ticks()
[plotting ]   File "/usr/lib/python3.10/site-packages/matplotlib/axis.py", line 1198, in _update_ticks
[plotting ]     minor_locs = self.get_minorticklocs()
[plotting ]   File "/usr/lib/python3.10/site-packages/matplotlib/axis.py", line 1431, in get_minorticklocs
[plotting ]     mask = np.isclose(tr_minor_locs[:, None], tr_major_locs[None, :],
[plotting ]   File "<__array_function__ internals>", line 180, in isclose
[plotting ]   File "/usr/lib/python3.10/site-packages/numpy/core/numeric.py", line 2373, in isclose
[plotting ]     yfin = isfinite(y)
[plotting ] TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```

**Comment by kiwifb** [comment]
<div id="comment:5" align="right">comment:5</div>

It looks like 

```
plot(2*x+1,(x,0,5),ticks=[[0,1,e,pi,sqrt(20)],2],tick_formatter="latex")
```
in both `src/sage/plot/graphics.py` and `src/sage/plot/plot.py` may be the root cause of the problem

```
┌────────────────────────────────────────────────────────────────────┐
│ SageMath version 9.8.beta2, Release Date: 2022-10-16               │
│ Using Python 3.10.8. Type "help()" for help.                       │
└────────────────────────────────────────────────────────────────────┘
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Warning: this is a prerelease version, and it may be unstable.     ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
sage: plot(2*x+1,(x,0,5),ticks=[[0,1,e,pi,sqrt(20)],2],tick_formatter="latex")
/usr/lib/python3.10/site-packages/sage/repl/rich_output/display_manager.py:610: RichReprWarning: Exception in _rich_repr_ while displaying object: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
  warnings.warn(
Graphics object consisting of 1 graphics primitive
```
Not testing them is not enough for doc building.

**Comment by tornaria** [comment]
<div id="comment:6" align="right">comment:6</div>

Replying to [François Bissey](#comment%3A4):
> Those changes are not enough to build the documentation with matplotlib 3.6.1, unless I miss another needed element

I didn't try to build documentation. The error looks like an error I "fixed" with this

```diff
diff --git a/src/sage/plot/plot.py b/src/sage/plot/plot.py
index b36ee57..5301a05 100644
--- a/src/sage/plot/plot.py
+++ b/src/sage/plot/plot.py
@@ -1741,7 +1741,7 @@ def plot(funcs, *args, **kwds):
 
     ::
 
-        sage: plot(2*x+1,(x,0,5),ticks=[[0,1,e,pi,sqrt(20)],2],tick_formatter="latex")
+        sage: plot(2*x+1,(x,0,5),ticks=[[0,1,e,pi,sqrt(20)],2],tick_formatter="latex") # not tested (broken with matplotlib 3.6)
         Graphics object consisting of 1 graphics primitive
 
     .. PLOT::
```

There is a `.. PLOT::` section after, and since I don't know how that works I didn't touch it, but I think the same code might be repeated.

The point is, the following code is broken, possibly forever:

```sage
sage: plot(2*x+1,(x,0,5),ticks=[[0,1,e,pi,sqrt(20)],2],tick_formatter="latex")
```
I looked at it a little bit and my conclusion is that there is *nothing* in sage to make it work. It just did by accident; a happy hack. In fact, matplotlib is expecting numpy objects in there, and SR expressions are not. Unless I'm missing something, making this work would require a new feature.

**Comment by kiwifb** [comment]
<div id="comment:7" align="right">comment:7</div>

I think the section in `plot.py` should be removed, I am trying it right now. I think that will be enough for the doc. But you are right that stuff should be replaced. I am not quite sure of the intent of that plot was in the first place.

**Comment by kiwifb** [comment]
<div id="comment:8" align="right">comment:8</div>

In the end, it looks like they both need to go :(

**Comment by kiwifb** [comment]
<div id="comment:9" align="right">comment:9</div>

I had not noticed 

```
    .. PLOT::

        g = plot(2*x+1,(x,0,5),ticks=[[0,1,e,pi,sqrt(20)],2],tick_formatter="latex")
        sphinx_plot(g)

```
in `plot.py`, this is likely my only culprit.

**Comment by kiwifb** [comment]
<div id="comment:10" align="right">comment:10</div>

Moved to a follow up ticket, #34693. We have some way forward.
