### ISSUE TITLE
elliptic_curves/hom_velusqrt.py: random test failure

### ISSUE THREAD

**Issue by collares** [sagemath/sage#34723]
<div id="comment:0"></div>

Sage 9.7 on x86_64:

```
sage -t --long --random-seed=190440690778015682984135421278300846991 /nix/store/jv3l7isa1hf4bjvf40lmrflzmyd696kz-sage-src-9.7/src/sage/schemes/elliptic_curves/hom_velusqrt.py
**********************************************************************
File "/nix/store/jv3l7isa1hf4bjvf40lmrflzmyd696kz-sage-src-9.7/src/sage/schemes/elliptic_curves/hom_velusqrt.py", line 1089, in sage.schemes.elliptic_curves.hom_velusqrt.EllipticCurveHom_velusqrt._eval
Failed example:
    E, K = _random_example_for_testing()
Exception raised:
    Traceback (most recent call last):
      File "/nix/store/g4h4aagj23nf3br90zn0545s8aqgbvxd-python3-3.10.8-env/lib/python3.10/site-packages/sage/doctest/forker.py", line 695, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/nix/store/g4h4aagj23nf3br90zn0545s8aqgbvxd-python3-3.10.8-env/lib/python3.10/site-packages/sage/doctest/forker.py", line 1101, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.schemes.elliptic_curves.hom_velusqrt.EllipticCurveHom_velusqrt._eval[16]>", line 1, in <module>
        E, K = _random_example_for_testing()
      File "/nix/store/g4h4aagj23nf3br90zn0545s8aqgbvxd-python3-3.10.8-env/lib/python3.10/site-packages/sage/schemes/elliptic_curves/hom_velusqrt.py", line 1225, in _random_example_for_testing
        assert K.order() == deg
    AssertionError
```

CC:  @yyyyx4

Component: **elliptic curves**

Author: **Lorenz Panny**

Branch/Commit: **[`2402ce0`](https://github.com/sagemath/sagetrac-mirror/commit/2402ce0ea87028ef58a59e87a3855fa588316bb9)**

Reviewer: **Frédéric Chapoton**

_Issue created by migration from https://trac.sagemath.org/ticket/34723_

**Comment by fchapoton** [comment]
<div id="comment:1" align="right">comment:1</div>

duplicate of #34467 ?

**Comment by yyyyx4** [comment]
<div id="comment:2" align="right">comment:2</div>

Nope, this is different and it can still happen on the latest beta, just not with this specific random seed. I'll work on a fix, thanks for the bug report!

**Comment by yyyyx4** [comment]
<div id="comment:3" align="right">comment:3</div>

Here you go, just a silly group theory mistake. I'm not sure how one would write a doctest for this.

**Comment by yyyyx4** [comment]
Author: **Lorenz Panny**

**Comment by yyyyx4** [comment]
Commit: **[`2402ce0`](https://github.com/sagemath/sagetrac-mirror/commit/2402ce0ea87028ef58a59e87a3855fa588316bb9)**

**Comment by yyyyx4** [comment]
Branch: **[public/34723](https://github.com/sagemath/sagetrac-mirror/tree/public/34723)**

**Comment by fchapoton** [comment]
<div id="comment:4" align="right">comment:4</div>

setting to positive, assuming you understand your own code

**Comment by fchapoton** [comment]
Reviewer: **Frédéric Chapoton**

**Comment by vbraun** [comment]
Changed branch from **[public/34723](https://github.com/sagemath/sagetrac-mirror/tree/public/34723)** to **[`2402ce0`](https://github.com/sagemath/sagetrac-mirror/commit/2402ce0ea87028ef58a59e87a3855fa588316bb9)**
