### ISSUE TITLE
Elliptic curves isogeny:  test failing randomly

### ISSUE THREAD

**Issue by GMS103** [sagemath/sage#34934]
<div id="comment:0"></div>

For this particular seed, the following test

```
sage -t --long --warn-long 34.2 --random-seed=152197772011569013238342510928576188390 src/sage/schemes/elliptic_curves/ell_curve_isogeny.py
```
fails on [SageMath](../wiki/SageMath) 9.8.beta7 as follows:

```
**********************************************************************
File "src/sage/schemes/elliptic_curves/ell_curve_isogeny.py", line 2962, in sage.schemes.elliptic_curves.ell_curve_isogeny.EllipticCurveIsogeny.dual
Failed example:
    E.isogeny(3*E.lift_x(0)).dual()
Exception raised:
    Traceback (most recent call last):
      File "/Users/gms/SageMath/Git/sage/src/sage/doctest/forker.py", line 695, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/Users/gms/SageMath/Git/sage/src/sage/doctest/forker.py", line 1093, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.schemes.elliptic_curves.ell_curve_isogeny.EllipticCurveIsogeny.dual[38]>", line 1, in <module>
        E.isogeny(Integer(3)*E.lift_x(Integer(0))).dual()
      File "/Users/gms/SageMath/Git/sage/src/sage/schemes/elliptic_curves/ell_curve_isogeny.py", line 3076, in dual
        corr = find_post_isomorphism(mult, rhs)
      File "/Users/gms/SageMath/Git/sage/src/sage/schemes/elliptic_curves/hom.py", line 856, in find_post_isomorphism
        isos = [iso for iso in isos if iso._eval(im_phi) == im_psi]
      File "/Users/gms/SageMath/Git/sage/src/sage/schemes/elliptic_curves/hom.py", line 856, in <listcomp>
        isos = [iso for iso in isos if iso._eval(im_phi) == im_psi]
      File "/Users/gms/SageMath/Git/sage/src/sage/schemes/elliptic_curves/weierstrass_morphism.py", line 586, in _eval
        return self._codomain.base_extend(k).point(Q)
      File "/Users/gms/SageMath/Git/sage/src/sage/schemes/elliptic_curves/ell_generic.py", line 1352, in base_extend
        E = constructor.EllipticCurve([R(a) for a in self.a_invariants()])
      File "/Users/gms/SageMath/Git/sage/src/sage/schemes/elliptic_curves/ell_generic.py", line 1352, in <listcomp>
        E = constructor.EllipticCurve([R(a) for a in self.a_invariants()])
      File "sage/rings/finite_rings/element_givaro.pyx", line 1355, in sage.rings.finite_rings.element_givaro.FiniteField_givaroElement.__int__
        raise TypeError("Cannot coerce element to an integer.")
    TypeError: Cannot coerce element to an integer.
**********************************************************************
1 item had failures:
   1 of  69 in sage.schemes.elliptic_curves.ell_curve_isogeny.EllipticCurveIsogeny.dual
    [871 tests, 1 failure, 8.94 s]
----------------------------------------------------------------------
sage -t --long --warn-long 34.2 --random-seed=152197772011569013238342510928576188390 src/sage/schemes/elliptic_curves/ell_curve_isogeny.py  # 1 doctest failed
----------------------------------------------------------------------
```
I would be curious to know how (un)lucky I am...

CC:  @yyyyx4

Component: **elliptic curves**

_Issue created by migration from https://trac.sagemath.org/ticket/34934_

**Comment by JohnCremona** [comment]
Looking at the code, specifically line 586 of weierstrass_morphism.py in the method _val which is tagged "Less strict evaluation method for internal use.":   self is a WeierstrassIsomorphism and the problem arises when base_extending the codomain of self to k which is the universe of the sequence of coordinates.  The point in question is found as a random point (in line 854 of hom.py).  Looking at the random point code over F_q, with probability 1/(2q+1) it returns the 0 point (point at infinity).  That construction comes from line 264 of ell_point.py -- and here is the problem!  The coordinates are set in the line

    v = (0,1,0)

and not coerced into the curve's base ring -- the code to do that is commented out saying " some of the code assumes that E(0) has integral entries regardless of the base ring..."

I suggest changing that, so that E(0)'s coordinates are -- as they properly should be -- in the base ring, seeing if anything breaks as a result, and if so fixing those places.

I will try this.

**Comment by JohnCremona** [comment]
No need - that change was already made in 9.8 (in commit 64cfac567e67ccfbf by @yyyyx4 ).


@GMS103 do you still see the problem?  If not, you can close this as already fixed.

**Comment by yyyyx4** [comment]
Oops, I forgot that this issue existed when I applied the fix. Sorry for wasting your time.

**Comment by JohnCremona** [comment]
> Oops, I forgot that this issue (or maybe this one is still a _ticket_) existed when I applied the fix. Sorry for wasting your time.

No problem!

**Comment by GMS103** [comment]
Thanks!
