### ISSUE TITLE
Fix doctest in sage/schemes/elliptic_curves/ell_number_field.py

### ISSUE THREAD

**Issue by mkoeppe** [sagemath/sage#34959]
<div id="comment:0"></div>

A "long" annotation is missing in a doctest introduced in #34537, causing:

```
sage -t --random-seed=257591867899933130420640722238032668369 sage/schemes/elliptic_curves/ell_number_field.py
**********************************************************************
File "sage/schemes/elliptic_curves/ell_number_field.py", line 2304, in sage.schemes.elliptic_curves.ell_number_field.EllipticCurve_number_field.gens
Failed example:
    P=gg[0]; P.order()
Exception raised:
    Traceback (most recent call last):
      File "/__w/sagetrac-mirror/sagetrac-mirror/src/sage/doctest/forker.py", line 695, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/__w/sagetrac-mirror/sagetrac-mirror/src/sage/doctest/forker.py", line 1093, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.schemes.elliptic_curves.ell_number_field.EllipticCurve_number_field.gens[7]>", line 1, in <module>
        P=gg[Integer(0)]; P.order()
    NameError: name 'gg' is not defined
```

CC:  @dimpase

Component: **doctest coverage**

_Issue created by migration from https://trac.sagemath.org/ticket/34959_

**Comment by JohnCremona** [comment]
I came across this too while working on #22697.  I think that all the automated testing is done with --long so this sort of thing gets missed.

Although I have a fix i my branch, I will make a PR for this now.

**Comment by JohnCremona** [comment]
#34989  fixes this (and more)
