### ISSUE TITLE
random doctest failure in src/sage/schemes/elliptic_curves/ell_curve_isogeny.py

### ISSUE THREAD

**Issue by yyyyx4** [sagemath/sage#35017]
From [here](https://github.com/sagemath/sage/actions/runs/4120247207/jobs/7114774719#step:11:8032):

```
sage -t --random-seed=190067076934214534085190334889366968176 sage/schemes/elliptic_curves/ell_curve_isogeny.py
**********************************************************************
File "sage/schemes/elliptic_curves/ell_curve_isogeny.py", line 2966, in sage.schemes.elliptic_curves.ell_curve_isogeny.EllipticCurveIsogeny.dual
Failed example:
    E.isogeny(E.lift_x(0)).dual()
Exception raised:
    Traceback (most recent call last):
      File "/__w/sage/sage/src/sage/doctest/forker.py", line 695, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/__w/sage/sage/src/sage/doctest/forker.py", line 1093, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.schemes.elliptic_curves.ell_curve_isogeny.EllipticCurveIsogeny.dual[39]>", line 1, in <module>
        E.isogeny(E.lift_x(Integer(0))).dual()
      File "/__w/sage/sage/src/sage/schemes/elliptic_curves/ell_curve_isogeny.py", line 3076, in dual
        corr = find_post_isomorphism(mult, rhs)
      File "/__w/sage/sage/src/sage/schemes/elliptic_curves/hom.py", line 856, in find_post_isomorphism
        isos = [iso for iso in isos if iso._eval(im_phi) == im_psi]
      File "/__w/sage/sage/src/sage/schemes/elliptic_curves/hom.py", line 856, in <listcomp>
        isos = [iso for iso in isos if iso._eval(im_phi) == im_psi]
      File "/__w/sage/sage/src/sage/schemes/elliptic_curves/weierstrass_morphism.py", line 607, in _eval
        return self._codomain.base_extend(k).point(Q)
      File "/__w/sage/sage/src/sage/schemes/elliptic_curves/ell_generic.py", line 1352, in base_extend
        E = constructor.EllipticCurve([R(a) for a in self.a_invariants()])
      File "/__w/sage/sage/src/sage/schemes/elliptic_curves/ell_generic.py", line 1352, in <listcomp>
        E = constructor.EllipticCurve([R(a) for a in self.a_invariants()])
      File "sage/rings/finite_rings/element_givaro.pyx", line 1355, in sage.rings.finite_rings.element_givaro.FiniteField_givaroElement.__int__
        raise TypeError("Cannot coerce element to an integer.")
    TypeError: Cannot coerce element to an integer.
**********************************************************************
```

Another [test failure](https://github.com/sagemath/sage/actions/runs/4120251276/jobs/7114783333#step:11:8066) is due to the same issue.

**Comment by yyyyx4** [comment]
This seems to occur rather frequently. It would be good to get the fix into the 9.8 release.
