### ISSUE TITLE
Multivariable polynomial ring claims division by zero when not

### ISSUE THREAD

**Issue by ghseeli** [sagemath/sage#35428]
### Is there an existing issue for this?

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.

### Did you read the documentation and troubleshoot guide?

- [X] I have read the documentation and troubleshoot guide

### Environment

```markdown
- **OS**: Multiple: OS X 12.6.3, Ubuntu 20.4 (Cocalc)
- **Sage Version**: 9.8

Fraction field claims division by zero, even when expression is not dividing by zero, depending simply on how the same function is written.
```

### Steps To Reproduce

sage: K = Frac(QQ['q'])
sage: R = Frac(K['x1,x2'])
sage: q = R('q')
sage: x1 = R('x1')
sage: (1-x1)/(1-x1)
1
sage: q*(1-x1)/(1-x1)
q
sage: (1-x1)/(q*(1-x1))
1/q
sage: q^(-1)*(1-x1)/(1-x1)
Error in lines 1-1
Traceback (most recent call last):
  File "/cocalc/lib/python3.10/site-packages/smc_sagews/sage_server.py", line 1244, in execute
    exec(
  File "", line 1, in <module>
  File "sage/structure/element.pyx", line 1736, in sage.structure.element.Element.__truediv__
    return (<Element>left)._div_(right)
  File "sage/rings/fraction_field_element.pyx", line 732, in sage.rings.fraction_field_element.FractionFieldElement._div_
    return self._mul_(rightinv)
  File "sage/rings/fraction_field_element.pyx", line 686, in sage.rings.fraction_field_element.FractionFieldElement._mul_
    return self.__class__(self._parent, tnum, tden,
  File "sage/rings/fraction_field_element.pyx", line 125, in sage.rings.fraction_field_element.FractionFieldElement.__init__
    raise ZeroDivisionError("fraction field element division by zero")
ZeroDivisionError: fraction field element division by zero

### Expected Behavior

There should be no difference between expressions (1-x1)/(q*(1-x1)) and q^(-1)*(1-x1)/(1-x1) in a ring of rational functions.

### Actual Behavior

(1-x1)/(q*(1-x1)) evaluates to 1/q (correct) and q^(-1)*(1-x1)/(1-x1) throws an error.

### Additional Information

Note, this does not seem to be an issue in a ring of rational functions with one variable. 

sage: K = Frac(QQ['q'])
sage: R = Frac(K['x1'])
sage: q = R('q')
sage: x1 = R('x1')
sage: q^(-1)*(1-x1)/(1-x1)
1/q

**Comment by Cobord** [comment]
sage: (q^(-1)*(1-x1)).gcd(1-x1)
0

happening around line 668

**Comment by PotatoK123** [comment]
After several hours of debugging, I think I found the problem. When the following is called in `multi_polynomial_libsingular.pyx`,
```sage
        if count >= 15:  # note that _right._poly must be of shorter length than self._poly for us to care about this call
            sig_on()
        quo = p_Divide(p_Copy(self._poly, r), p_Copy(_right._poly, r), r)
        if count >= 15:
            sig_off()

        if quo == NULL:
            if r.cf.type == n_Z:
                P = parent.change_ring(QQ)
                f = (<MPolynomial_libsingular>P(self))._floordiv_(P(right))
                return parent(sum([c.floor() * m for c, m in f]))
            else:
                sig_on()
                quo = singclap_pdivide(self._poly, _right._poly, r)
                sig_off()
```
Singular errors when `r` does not meet any of the if conditions and `quo` is returned as a null pointer as well as calling...
```cpp
WerrorS( feNotImplemented );
```  
[(see Singular docs)](https://niptailaq.pasahome.org/~gpasa/SingularManual/clapsing_8h.html#a83765b0fe68dcda9ee551abe1ff6d051) which can be confirmed by reading `errorreported` before and after. However since `quo` is not checked for being a null pointer again, I suspect it mistakenly gets returned as a polynomial (the number 0) which leads to the `ZeroDivisionError` seen. I also suspect the following `gcd` becoming 0 is a result of Singular failing after the initial error and continuously returning null pointers which get interpreted as 0.

I've discovered #35886 also suffers from this problem and confirmed this with reading `errorreported`.

I'm not sure how this would be fixed. Perhaps further investigation would be needed to why the if checks are failing for `r`?

**Comment by ghseeli** [comment]
Perhaps a related issue, but it seems like evaluating the same sufficiently complicated expression too many times also causes issues. First, it returns an incorrect result, then gives an error. Here is an I tested example on my computer.
```
sage: K = Frac(QQ['q'])
sage: A = Frac(K['x1,x2'])
sage: q = K('q')
sage: x1 = A('x1')
sage: x2 = A('x2')
sage: pol1 = 1/q*x1
sage: pol2 = 1/q*x2
sage: (q*x1-x2)/(x1-x2)*(pol2-pol1) # Not zero
0
sage: (q*x1-x2)/(x1-x2)*(pol2-pol1)
---------------------------------------------------------------------------
ZeroDivisionError                         Traceback (most recent call last)
Input In [11], in <cell line: 1>()
----> 1 (q*x1-x2)/(x1-x2)*(pol2-pol1)

File ~/SageMath/src/sage/structure/element.pyx:1737, in sage.structure.element.Element.__truediv__()
   1735 cdef int cl = classify_elements(left, right)
   1736 if HAVE_SAME_PARENT(cl):
-> 1737     return (<Element>left)._div_(right)
   1738 if BOTH_ARE_ELEMENT(cl):
   1739     return coercion_model.bin_op(left, right, truediv)

File ~/SageMath/src/sage/rings/fraction_field_element.pyx:732, in sage.rings.fraction_field_element.FractionFieldElement._div_()
    730         coerce=True, reduce=False)
    731 
--> 732     return self._mul_(rightinv)
    733 
    734 def __int__(self):

File ~/SageMath/src/sage/rings/fraction_field_element.pyx:671, in sage.rings.fraction_field_element.FractionFieldElement._mul_()
    669 d2 = snum.gcd(rden)
    670 if not d1.is_unit():
--> 671     rnum = rnum // d1
    672     sden = sden // d1
    673 if not d2.is_unit():

File ~/SageMath/src/sage/structure/element.pyx:1838, in sage.structure.element.Element.__floordiv__()
   1836 cdef int cl = classify_elements(left, right)
   1837 if HAVE_SAME_PARENT(cl):
-> 1838     return (<Element>left)._floordiv_(right)
   1839 if BOTH_ARE_ELEMENT(cl):
   1840     return coercion_model.bin_op(left, right, floordiv)

File ~/SageMath/src/sage/rings/polynomial/multi_polynomial_libsingular.pyx:4134, in sage.rings.polynomial.multi_polynomial_libsingular.MPolynomial_libsingular._floordiv_()
   4132 
   4133         if _right._poly == NULL:
-> 4134             raise ZeroDivisionError
   4135         elif p_IsOne(_right._poly, r):
   4136             return self

ZeroDivisionError: 
```
