### ISSUE TITLE
Parallelism() on MacOS

### ISSUE THREAD

**Issue by jaborthwick** [sagemath/sage#35580]
### Is there an existing issue for this?

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.

### Did you read the documentation and troubleshoot guide?

- [X] I have read the documentation and troubleshoot guide

### Environment

```markdown
- **OS**: MacOS 13.3.1
- **Sage Version**: 9.8
```

### Steps To Reproduce

Below is an example of code that leads to the problem. The problem occurs even in this very simple case where the computations are simple:
```
Parallelism().set(nproc=2) # Setting this to anything other than 1 leads to a problem
var('m')
M=Manifold(4,'M')
X.<t,r,th,ph>=M.chart(r't r:(0,oo) th:(0,pi):\theta ph:(0,2*pi):cyclic:\phi')
Y.<rho,t1,th,ph>=M.chart(r'rho:(0,oo) t1:\tilde{t} th:(0,pi):\theta ph:(0,2*pi):cyclic:\phi')
X_to_Y=X.transition_map(Y,[1/sqrt(r^2-t^2),t/sqrt(r^2-t^2),th,ph])
X_to_Y.inverse()
g=M.metric('g')
g[0,0]=-(1-2*m/r)
g[1,1]=(1-2*m/r)^(-1)
g[2,2]=r^2
g[3,3]=r^2*sin(th)^2
g.display()
g.display(Y) # Problem occurs at this point, when some computation must happen in the background to calculate the components of the metric in the chart Y
```

### Expected Behavior

The code should display the expression of the metric in the chart Y. 

### Actual Behavior

If nproc is set to anything other than 1, Sage prints the attached text and hangs on the command.

[SageErrorMessage.txt](https://github.com/sagemath/sage/files/11355305/SageErrorMessage.txt)

**Comment by egourgoulhon** [comment]
There is no such issue with Sage 9.8 and Sage 10.0.rc0 running on Ubuntu 22.04, so this must be a problem specific to MacOS...

Do you get any error if you run 
```
sage -t --long src/sage/tensor/modules/free_module_tensor.py
```
from the Sage root directory?

**Comment by jaborthwick** [comment]
Hi @egourgoulhon, Thanks for your reply. No errors upon running the command you suggested

**Comment by egourgoulhon** [comment]
> No errors upon running the command you suggested

Thanks for trying. This means that on macOS parallelization works well in the doctest framework, but not in a user session...

**Comment by dcoudert** [comment]
I tried with sagemath 10.0.rc1, M1,  macOS 12.6.5 and I see many times this error: 
```py
sage: g.display(Y)
Process SpawnPoolWorker-10:
Process SpawnPoolWorker-11:
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
  File "/Users/dcoudert/sage/src/sage/manifolds/differentiable/scalarfield_algebra.py", line 35, in <module>
    from sage.symbolic.ring import SymbolicRing
  File "sage/symbolic/ring.pyx", line 1, in init sage.symbolic.ring
    # -*- coding: utf-8 -*-
  File "sage/symbolic/pynac_impl.pxi", line 2613, in init sage.symbolic.expression
    init_pynac_I()
  File "sage/symbolic/pynac_impl.pxi", line 2516, in sage.symbolic.expression.init_pynac_I
    from .ring import SR
ImportError: cannot import name SR
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
  File "/Users/dcoudert/sage/src/sage/manifolds/differentiable/scalarfield_algebra.py", line 35, in <module>
    from sage.symbolic.ring import SymbolicRing
  File "sage/symbolic/ring.pyx", line 1, in init sage.symbolic.ring
    # -*- coding: utf-8 -*-
  File "sage/symbolic/pynac_impl.pxi", line 2613, in init sage.symbolic.expression
    init_pynac_I()
  File "sage/symbolic/pynac_impl.pxi", line 2516, in sage.symbolic.expression.init_pynac_I
    from .ring import SR
ImportError: cannot import name SR
...
```

**Comment by egourgoulhon** [comment]
> I tried with sagemath 10.0.rc1, M1, macOS 12.6.5 and I see many times this error:

Thanks for this report, which confirms the parallelization issue on another macOS system. Interestingly,  the `ImportError` you get is different from that got by @jaborthwick , which is
```
ImportError: cannot import name 'AlgebraicReal' from partially initialized module 'sage.rings.qqbar' 
(most likely due to a circular import) 
(/private/var/tmp/sage-9.8-current/local/var/lib/sage/venv-python3.11.1/lib/python3.11/site-packages/sage/rings/qqbar.py)
```
Can you confirm that 
```
sage -t --long src/sage/tensor/modules/free_module_tensor.py
```
work for you as well?

**Comment by dcoudert** [comment]
all tests passed.

**Comment by mkoeppe** [comment]
This is an instance of 
- #33580

**Comment by egourgoulhon** [comment]
Thank you Matthias for finding the explanation of this!

Just for my understanding, could you please tell why 
- there is no issue while performing a parallelized  computation within the doctest framework?
- in a standard (i.e. not doctest)  Sage session, the issue shows up for macOS, but not for Ubuntu?

**Comment by mkoeppe** [comment]
The doctester sets up the global environment explicitly (by importing `sage.all` in each parallel task), which is why it is not affected.

**Comment by mkoeppe** [comment]
I'm working on a fix that removes the cyclic import between `sage.symbolic.expression` and `sage.symbolic.ring`.

**Comment by egourgoulhon** [comment]
Thanks for your explanations!

**Comment by dcoudert** [comment]
When trying the example of #35592, I get another issue:
```py
sage: def f(H):
....:     print('H:', H.is_immutable(),flush=True)
....:     print('H.copy():', H.copy().is_immutable(),flush=True)
....: 
....: 
....: G = Graph(immutable=True)
....: f(G)
....: 
....: import multiprocessing
....: multiprocessing.Pool().imap_unordered(f,[G])
....: 
H: True
H.copy(): True
<multiprocessing.pool.IMapUnorderedIterator object at 0x15f19ee60>
sage: Process SpawnPoolWorker-4:
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'f' on <module '__main__' (built-in)>
```

**Comment by jaborthwick** [comment]
I just downloaded the latest version of Sage and tried to run [this notebook](https://nbviewer.org/github/sagemanifolds/SageManifolds/blob/master/Notebooks/SM_Kerr.ipynb). Unfortunately, it would seem that there still seems to be an issue with parallelisation and cyclic imports. Sage gets stuck on cell [26] and reports the following error for each worker:

`Process SpawnPoolWorker-37:
Traceback (most recent call last):
  File "/private/var/tmp/sage-10.0-current/local/var/lib/sage/venv-python3.11.1/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/private/var/tmp/sage-10.0-current/local/var/lib/sage/venv-python3.11.1/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/private/var/tmp/sage-10.0-current/local/var/lib/sage/venv-python3.11.1/lib/python3.11/multiprocessing/pool.py", line 114, in worker
    task = get()
           ^^^^^
  File "/private/var/tmp/sage-10.0-current/local/var/lib/sage/venv-python3.11.1/lib/python3.11/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/var/tmp/sage-10.0-current/local/var/lib/sage/venv-python3.11.1/lib/python3.11/site-packages/sage/manifolds/differentiable/vectorframe.py", line 220, in <module>
    from sage.tensor.modules.free_module_basis import (FreeModuleBasis,
  File "/private/var/tmp/sage-10.0-current/local/var/lib/sage/venv-python3.11.1/lib/python3.11/site-packages/sage/tensor/modules/free_module_basis.py", line 35, in <module>
    from sage.rings.integer_ring import ZZ
  File "sage/rings/integer_ring.pyx", line 1, in init sage.rings.integer_ring (build/cythonized/sage/rings/integer_ring.c:18206)
    r"""
  File "sage/rings/integer.pyx", line 1, in init sage.rings.integer (build/cythonized/sage/rings/integer.c:55136)
    r"""
  File "sage/rings/rational.pyx", line 79, in init sage.rings.rational (build/cythonized/sage/rings/rational.cpp:40466)
    from .integer_ring import ZZ
ImportError: cannot import name ZZ`

**Comment by egourgoulhon** [comment]
@dcoudert, may I ask if you had the occasion to try parallelization with Sage 10.0 on macOS?

**Comment by dcoudert** [comment]
with 10.1.beta1, macOS 12.6.6: the example of #35592 ([see above comment](https://github.com/sagemath/sage/issues/35580#issuecomment-1532548028)) now works correctly. However, the example given at the [top](https://github.com/sagemath/sage/issues/35580#issue-1688800009) of this discussion is still failing:
```py
sage: Parallelism().set(nproc=2) # Setting this to anything other than 1 leads to a problem
....: var('m')
....: M=Manifold(4,'M')
....: X.<t,r,th,ph>=M.chart(r't r:(0,oo) th:(0,pi):\theta ph:(0,2*pi):cyclic:\phi')
....: Y.<rho,t1,th,ph>=M.chart(r'rho:(0,oo) t1:\tilde{t} th:(0,pi):\theta ph:(0,2*pi):cyclic:\phi')
....: X_to_Y=X.transition_map(Y,[1/sqrt(r^2-t^2),t/sqrt(r^2-t^2),th,ph])
....: X_to_Y.inverse()
....: g=M.metric('g')
....: g[0,0]=-(1-2*m/r)
....: g[1,1]=(1-2*m/r)^(-1)
....: g[2,2]=r^2
....: g[3,3]=r^2*sin(th)^2
....: g.display()
....: g.display(Y) # Problem occurs at this point, when some computation must happen in the background to calculate the components of the metric in the chart Y
m
Change of coordinates from Chart (M, (rho, t1, th, ph)) to Chart (M, (t, r, th, ph))
g = (2*m/r - 1) dt⊗dt - 1/(2*m/r - 1) dr⊗dr + r^2 dth⊗dth + r^2*sin(th)^2 dph⊗dph
---------------------------------------------------------------------------
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "sage/misc/fpickle.pyx", line 115, in sage.misc.fpickle.call_pickled_function
    res = eval("f(*args, **kwds)",sage.all.__dict__, {'args':args, 'kwds':kwds, 'f':f})
  File "<string>", line 1, in <module>
  File "/Users/dcoudert/sage/src/sage/tensor/modules/free_module_tensor.py", line 1147, in paral_newcomp
    res += t
  File "sage/structure/element.pyx", line 1514, in sage.structure.element.Element.__mul__
    return (<Element>left)._mul_(right)
  File "sage/structure/element.pyx", line 1560, in sage.structure.element.Element._mul_
    return python_op(other)
  File "/Users/dcoudert/sage/src/sage/manifolds/scalarfield.py", line 2806, in _mul_
    raise ValueError("no common chart for the multiplication")
ValueError: no common chart for the multiplication
"""

The above exception was the direct cause of the following exception:

ValueError                                Traceback (most recent call last)
Cell In [1], line 14
     12 g[Integer(3),Integer(3)]=r**Integer(2)*sin(th)**Integer(2)
     13 g.display()
---> 14 g.display(Y) # Problem occurs at this point, when some computation must happen in the background to calculate the components of the metric in the chart Y

File ~/sage/src/sage/tensor/modules/free_module_tensor.py:696, in FreeModuleTensor.display(self, basis, format_spec)
    693 basis, format_spec = self._preparse_display(basis=basis,
    694                                             format_spec=format_spec)
    695 cobasis = basis.dual_basis()
--> 696 comp = self.comp(basis)
    697 terms_txt = []
    698 terms_latex = []

File ~/sage/src/sage/manifolds/differentiable/tensorfield_paral.py:1180, in TensorFieldParal.comp(self, basis, from_basis)
   1176     basis = self._fmodule._def_basis
   1178 if basis._domain == self._domain:
   1179     # components on the tensor field domain:
-> 1180     return FreeModuleTensor.comp(self, basis=basis,
   1181                                  from_basis=from_basis)
   1183 # components on a subdomain:
   1184 rst = self.restrict(basis._domain, dest_map=basis._dest_map)

File ~/sage/src/sage/tensor/modules/free_module_tensor.py:1151, in FreeModuleTensor.components(self, basis, from_basis)
   1148         partial.append([ind,res])
   1149     return partial
-> 1151 for ii,val in paral_newcomp(listParalInput):
   1152     for jj in val:
   1153         new_comp[[jj[0]]] = jj[1]

File ~/sage/src/sage/parallel/multiprocessing_sage.py:77, in parallel_iter(processes, f, inputs)
     73 fp = pickle_function(f)
     75 result = p.imap_unordered(call_pickled_function,
     76                           [(fp, t) for t in inputs])
---> 77 for res in result:
     78     yield res
     79 p.close()

File /opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/pool.py:873, in IMapIterator.next(self, timeout)
    871 if success:
    872     return value
--> 873 raise value

ValueError: no common chart for the multiplication
```

**Comment by jaborthwick** [comment]
I confirm that I get the same error as @dcoudert when running the example at the [top](https://github.com/sagemath/sage/issues/35580#issue-1688800009) of this discussion. 

However, if I run this code then the command Parallelism().set(nproc=1) followed by g.display(Y), the error disappears. 
Could it be that somehow the information about the change of chart is not being passed to workers ?

**Comment by egourgoulhon** [comment]
Thanks @dcoudert ahd @jaborthwick for your feedbacks. I am reopening the issue.

**Comment by vbraun** [comment]
Maybe `Parallelism()` could `import sage.all` after creating an new process on MacOS? 

I'm going to remove the blocker status since using Parallelism on a platform without fork is probably of limited use.

**Comment by dimpase** [comment]
Please see #41267 for a very unpleasant `Parallelism` bug affecting the stable Sage 10.x for x<7.
