### ISSUE TITLE
Build "sagemath_doc_html-none" failed when "import lrcalc"

### ISSUE THREAD

**Issue by geoffreysxu** [sagemath/sage#35708]
### Is there an existing issue for this?

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.

### Did you read the documentation and troubleshoot guide?

- [X] I have read the documentation and troubleshoot guide

### Environment

```markdown
- **OS**:Ubuntu 20.04
- **Sage Version**: 10.0
```

### Steps To Reproduce

1. Pull sage 10.0
2. Build from the source (./bootstrap; ./configure; MAKE="make -j8" & make)
3. Build failed at "sagemath_doc_html-none" 
4. I need to comment out the line "import lrcalc" in "src/sage/libs/lrcalc/lrcalc.py"
5. Then build succeeded

### Config log

[config.log](https://github.com/sagemath/sage/files/11631685/config.log)

**Comment by mkoeppe** [comment]
We would have to see the error messages in step 3.

**Comment by diagprov** [comment]
I'm not the OP but `sagemath_doc_html-none` fails to build for me also. In my case, environment is Fedora 38 rather than Ubuntu.

The error I get is

```
[sagemath_doc_html-none] Error building the documentation.
[sagemath_doc_html-none] Traceback (most recent call last):
[sagemath_doc_html-none]   File "<frozen runpy>", line 198, in _run_module_as_main
[sagemath_doc_html-none]   File "<frozen runpy>", line 88, in _run_code
[sagemath_doc_html-none]   File "/<path>/sage-src/src/sage_docbuild/__main__.py", line 498, in <module>
[sagemath_doc_html-none]     sys.exit(main())
[sagemath_doc_html-none]              ^^^^^^
[sagemath_doc_html-none]   File "/<path>/sage-src/src/sage_docbuild/__main__.py", line 495, in main
[sagemath_doc_html-none]     builder()
[sagemath_doc_html-none]   File "/<path>/sage-src/src/sage_docbuild/builders.py", line 819, in _wrapper
[sagemath_doc_html-none]     getattr(DocBuilder, build_type)(self, *args, **kwds)
[sagemath_doc_html-none]   File "/<path>/sage-src/src/sage_docbuild/builders.py", line 163, in f
[sagemath_doc_html-none]     runsphinx()
[sagemath_doc_html-none]   File "/<path>/sage-src/src/sage_docbuild/sphinxbuild.py", line 327, in runsphinx
[sagemath_doc_html-none]     sys.stderr.raise_errors()
[sagemath_doc_html-none]   File "/<path>/sage-src/src/sage_docbuild/sphinxbuild.py", line 263, in raise_errors
[sagemath_doc_html-none]     raise OSError(self._error)
[sagemath_doc_html-none] OSError: WARNING: error while formatting arguments for sage.geometry.integral_points.InequalityCollection.are_satisfied: 'NoneType' object has no attribute 'find'
[sagemath_doc_html-none]
[sagemath_doc_html-none]     Note: incremental documentation builds sometimes cause spurious
[sagemath_doc_html-none]     error messages. To be certain that these are real errors, run
[sagemath_doc_html-none]     "make doc-clean doc-uninstall" first and try again.
[sagemath_doc_html-none] make[6]: *** [Makefile:28: doc-inventory--reference-discrete_geometry] Error 1
[sagemath_doc_html-none] make[6]: *** Waiting for unfinished jobs...
```

I'm building on multiple architectures and I suspect this may be a timing issue - I tried to reproduce the issue with a second `make -j$(nproc)` and at this point the build succeeds, in all cases.

I'm running `./configure --prefix=/opt/sage --libdir=/opt/sage/lib64 --no-create --no-recursion` if that helps.

**Comment by mkoeppe** [comment]
Try if this goes away if you do `make lrcalc-uninstall; make build`
