### ISSUE TITLE
Random doctest failure in structure/coerce_actions.pyx

### ISSUE THREAD

**Issue by jhpalmieri** [sagemath/sage#35973]
### Steps To Reproduce

OS X 13.4.1 on Apple M1. `./sage -t --long src/sage/structure/coerce_actions.pyx` typically passes, but with a specific random seed, I get failures:
```
./sage -t --long --random-seed=59996678553091503109319269785176095170 src/sage/structure/coerce_actions.pyx
```
fails as described below.

### Expected Behavior

Doctests should pass.

### Actual Behavior

```
./sage -t --long --random-seed=59996678553091503109319269785176095170 src/sage/structure/coerce_actions.pyx
```
fails:
```
**********************************************************************
File "src/sage/structure/coerce_actions.pyx", line 777, in sage.structure.coerce_actions.IntegerMulAction._act_
Failed example:
    alarm(0.001); 2^(10^7) * P
Expected:
    Traceback (most recent call last):
    ...
    AlarmInterrupt
Got:
    (0 : 1 : 0)
**********************************************************************
File "src/sage/structure/coerce_actions.pyx", line 785, in sage.structure.coerce_actions.IntegerMulAction._act_
Failed example:
    from cysignals.tests import print_sig_occurred
Exception raised:
    Traceback (most recent call last):
      File "/Users/jpalmier/Desktop/Sage/TESTING/sage-10.1.beta6/src/sage/doctest/forker.py", line 696, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/Users/jpalmier/Desktop/Sage/TESTING/sage-10.1.beta6/src/sage/doctest/forker.py", line 1106, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.structure.coerce_actions.IntegerMulAction._act_[12]>", line 1, in <module>
        from cysignals.tests import print_sig_occurred
      File "<frozen importlib._bootstrap>", line 405, in parent
      File "src/cysignals/signals.pyx", line 310, in cysignals.signals.python_check_interrupt
    cysignals.signals.AlarmInterrupt
**********************************************************************
File "src/sage/structure/coerce_actions.pyx", line 786, in sage.structure.coerce_actions.IntegerMulAction._act_
Failed example:
    print_sig_occurred()
Exception raised:
    Traceback (most recent call last):
      File "/Users/jpalmier/Desktop/Sage/TESTING/sage-10.1.beta6/src/sage/doctest/forker.py", line 696, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/Users/jpalmier/Desktop/Sage/TESTING/sage-10.1.beta6/src/sage/doctest/forker.py", line 1106, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.structure.coerce_actions.IntegerMulAction._act_[13]>", line 1, in <module>
        print_sig_occurred()
        ^^^^^^^^^^^^^^^^^^
    NameError: name 'print_sig_occurred' is not defined
**********************************************************************
1 item had failures:
   3 of  15 in sage.structure.coerce_actions.IntegerMulAction._act_
    [150 tests, 3 failures, 0.10 s]
----------------------------------------------------------------------
sage -t --long --warn-long 32.2 --random-seed=59996678553091503109319269785176095170 src/sage/structure/coerce_actions.pyx  # 3 doctests failed
```

### Environment

```markdown
- **OS**: Mac OS 13.4.1, Apple M1 Max chip
- **Sage Version**: 10.1.beta6, built with `./configure --with-system-singular=no`, otherwise using as many Homebrew packages as possible.
```

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

**Comment by jhpalmieri** [comment]
If others can confirm the failure, this is an instance of #32544.
