### ISSUE TITLE
RecursionError in MPolynomialRing_libsingular._element_constructor_

### ISSUE THREAD

**Issue by bjodah** [sagemath/sage#36004]
### Steps To Reproduce

```shell-session
$ sage --version
SageMath version 9.5, Release Date: 2022-01-30
```
The follwing invocation takes ~1 minute on my machine (computation of the basis) before it fails (when converting back to sage):
```shell-session
$  sage tmpxd7el17t.sage
Traceback (most recent call last):
  File "/tmp/tmpxd7el17t.sage.py", line 18, in <module>
    main()
  File "/tmp/tmpxd7el17t.sage.py", line 15, in main
    print([{k: str(v) for k, v in _._sage_().dict().items()} for _ in gbasis])
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/tmpxd7el17t.sage.py", line 15, in <listcomp>
    print([{k: str(v) for k, v in _._sage_().dict().items()} for _ in gbasis])
                                  ^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/sage/interfaces/singular.py", line 2002, in _sage_
    return self.sage_poly(R)
           ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/sage/interfaces/singular.py", line 1807, in sage_poly
    return R(self)
           ^^^^^^^
  File "sage/structure/parent.pyx", line 898, in sage.structure.parent.Parent.__call__ (build/cythonized/sage/structure/parent.c:9522)
  File "sage/structure/coerce_maps.pyx", line 161, in sage.structure.coerce_maps.DefaultConvertMap_unique._call_ (build/cythonized/sage/structure/coerce_maps.c:4799)
  File "sage/structure/coerce_maps.pyx", line 156, in sage.structure.coerce_maps.DefaultConvertMap_unique._call_ (build/cythonized/sage/structure/coerce_maps.c:4691)
  File "sage/rings/polynomial/multi_polynomial_libsingular.pyx", line 985, in sage.rings.polynomial.multi_polynomial_libsingular.MPolynomialRing_libsingular._element_constructor_ (build/cythonized/sage/rings/polynomial/multi_polynomial_libsingular.cpp:11535)
RecursionError: maximum recursion depth exceeded during compilation
```
contents of tmpxd7el17t.sage
```sage
def main():

    R = singular.ring('(0, p0, p1, p2, p3, p4, p5, p6, p7, p8, p9)', '(z0, z1, z2, z3, z4, z5, z6, z7)', 'dp')
    I = singular.ideal('-z2*z3 + p0*z1*z0', 'p1*z4 - z5*z3', '-z6 + p2*z1*z5', '-p3 - p4 - p5 + z4 + z5 + z6', '-p5 - p6 - p7 + z0 + z3 + z4', '-p3 - p8 - p9 + z1 + z2 + z6', '-p7 - p8 + z0 + z2', '-z4 + z7')
    singular.option('redSB')
    gb = singular.std(I)
    S = singular.ring('(0, p0, p1, p2, p3, p4, p5, p6, p7, p8, p9)', '(z0, z1, z2, z3, z4, z5, z6, z7)', 'lp')
    gbasis = singular.ideal('fglm({}, {})'.format(R.name(), gb.name()))
    print([{k: str(v) for k, v in _._sage_().dict().items()} for _ in gbasis])
    return

main()
```

### Expected Behavior

I expected a call to `._sage_()` not to fail.

### Actual Behavior

RecursionError

### Additional Information

I was guided by the kind Ricardo Buring in his answer to my question on ask sage [here](https://ask.sagemath.org/question/71213/trouble-transforming-a-groebner-basis/?answer=71223#post-id-71223).

For now I think I will work around this problem by printing the singular object and parsing the polynomials by other means.

### Environment

```markdown
- **OS**: Debian Bookworm
- **Sage Version**: 9.5
```

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

**Comment by bjodah** [comment]
Is there perhaps a way to get singular to print to equivalent of `str(_sage_.dict())`? (without having to invoke `_sage_` that is..)
