### ISSUE TITLE
attrs depends on hatchling

### ISSUE THREAD

**Issue by vbraun** [sagemath/sage#36428]
### Steps To Reproduce

Might be related to update to attrs 23.1.0 565dddb6b226773588fa4e028802f158d11064c6
```
[attrs-23.1.0]   Preparing metadata (pyproject.toml): finished with status 'done'
[attrs-23.1.0] ERROR: Exception:
[attrs-23.1.0] Traceback (most recent call last):
[attrs-23.1.0]   File "/home/release/Sage/local/var/lib/sage/venv-python3.11.1/lib/python3.11/site-packages/pip/_internal/cli/base_command.py", line 180, in exc_logging_wrapper
[attrs-23.1.0]     status = run_func(*args)
[attrs-23.1.0]              ^^^^^^^^^^^^^^^
[attrs-23.1.0]   File "/home/release/Sage/local/var/lib/sage/venv-python3.11.1/lib/python3.11/site-packages/pip/_internal/cli/req_command.py", line 248, in wrapper
[attrs-23.1.0]     return func(self, options, args)
[attrs-23.1.0]            ^^^^^^^^^^^^^^^^^^^^^^^^^
[attrs-23.1.0]   File "/home/release/Sage/local/var/lib/sage/venv-python3.11.1/lib/python3.11/site-packages/pip/_internal/commands/wheel.py", line 147, in run
[attrs-23.1.0]     requirement_set = resolver.resolve(reqs, check_supported_wheels=True)
[attrs-23.1.0]                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[attrs-23.1.0]   File "/home/release/Sage/local/var/lib/sage/venv-python3.11.1/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 73, in resolve
[attrs-23.1.0]     collected = self.factory.collect_root_requirements(root_reqs)
[attrs-23.1.0]                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[attrs-23.1.0]   File "/home/release/Sage/local/var/lib/sage/venv-python3.11.1/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 491, in collect_root_requirements
[attrs-23.1.0]     req = self._make_requirement_from_install_req(
[attrs-23.1.0]           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[attrs-23.1.0]   File "/home/release/Sage/local/var/lib/sage/venv-python3.11.1/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 453, in _make_requirement_from_install_req
[attrs-23.1.0]     cand = self._make_candidate_from_link(
[attrs-23.1.0]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[attrs-23.1.0]   File "/home/release/Sage/local/var/lib/sage/venv-python3.11.1/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 206, in _make_candidate_from_link
[attrs-23.1.0]     self._link_candidate_cache[link] = LinkCandidate(
[attrs-23.1.0]                                        ^^^^^^^^^^^^^^
[attrs-23.1.0]   File "/home/release/Sage/local/var/lib/sage/venv-python3.11.1/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 293, in __init__
[attrs-23.1.0]     super().__init__(
[attrs-23.1.0]   File "/home/release/Sage/local/var/lib/sage/venv-python3.11.1/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 156, in __init__
[attrs-23.1.0]     self.dist = self._prepare()
[attrs-23.1.0]                 ^^^^^^^^^^^^^^^
[attrs-23.1.0]   File "/home/release/Sage/local/var/lib/sage/venv-python3.11.1/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 225, in _prepare
[attrs-23.1.0]     dist = self._prepare_distribution()
[attrs-23.1.0]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[attrs-23.1.0]   File "/home/release/Sage/local/var/lib/sage/venv-python3.11.1/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 304, in _prepare_distribution
[attrs-23.1.0]     return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
[attrs-23.1.0]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[attrs-23.1.0]   File "/home/release/Sage/local/var/lib/sage/venv-python3.11.1/lib/python3.11/site-packages/pip/_internal/operations/prepare.py", line 538, in prepare_linked_requirement
[attrs-23.1.0]     return self._prepare_linked_requirement(req, parallel_builds)
[attrs-23.1.0]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[attrs-23.1.0]   File "/home/release/Sage/local/var/lib/sage/venv-python3.11.1/lib/python3.11/site-packages/pip/_internal/operations/prepare.py", line 653, in _prepare_linked_requirement
[attrs-23.1.0]     dist = _get_prepared_distribution(
[attrs-23.1.0]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[attrs-23.1.0]   File "/home/release/Sage/local/var/lib/sage/venv-python3.11.1/lib/python3.11/site-packages/pip/_internal/operations/prepare.py", line 69, in _get_prepared_distribution
[attrs-23.1.0]     abstract_dist.prepare_distribution_metadata(
[attrs-23.1.0]   File "/home/release/Sage/local/var/lib/sage/venv-python3.11.1/lib/python3.11/site-packages/pip/_internal/distributions/sdist.py", line 61, in prepare_distribution_metadata
[attrs-23.1.0]     self.req.prepare_metadata()
[attrs-23.1.0]   File "/home/release/Sage/local/var/lib/sage/venv-python3.11.1/lib/python3.11/site-packages/pip/_internal/req/req_install.py", line 562, in prepare_metadata
[attrs-23.1.0]     self.metadata_directory = generate_metadata(
[attrs-23.1.0]                               ^^^^^^^^^^^^^^^^^^
[attrs-23.1.0]   File "/home/release/Sage/local/var/lib/sage/venv-python3.11.1/lib/python3.11/site-packages/pip/_internal/operations/build/metadata.py", line 35, in generate_metadata
[attrs-23.1.0]     distinfo_dir = backend.prepare_metadata_for_build_wheel(metadata_dir)
[attrs-23.1.0]                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[attrs-23.1.0]   File "/home/release/Sage/local/var/lib/sage/venv-python3.11.1/lib/python3.11/site-packages/pip/_internal/utils/misc.py", line 718, in prepare_metadata_for_build_wheel
[attrs-23.1.0]     return super().prepare_metadata_for_build_wheel(
[attrs-23.1.0]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[attrs-23.1.0]   File "/home/release/Sage/local/var/lib/sage/venv-python3.11.1/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_impl.py", line 186, in prepare_metadata_for_build_wheel
[attrs-23.1.0]     return self._call_hook('prepare_metadata_for_build_wheel', {
[attrs-23.1.0]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[attrs-23.1.0]   File "/home/release/Sage/local/var/lib/sage/venv-python3.11.1/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_impl.py", line 321, in _call_hook
[attrs-23.1.0]     raise BackendUnavailable(data.get('traceback', ''))
[attrs-23.1.0] pip._vendor.pyproject_hooks._impl.BackendUnavailable: Traceback (most recent call last):
[attrs-23.1.0]   File "/home/release/Sage/local/var/lib/sage/venv-python3.11.1/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 77, in _build_backend
[attrs-23.1.0]     obj = import_module(mod_path)
[attrs-23.1.0]           ^^^^^^^^^^^^^^^^^^^^^^^
[attrs-23.1.0]   File "/home/release/Sage/local/var/lib/sage/venv-python3.11.1/lib/python3.11/importlib/__init__.py", line 126, in import_module
[attrs-23.1.0]     return _bootstrap._gcd_import(name[level:], package, level)
[attrs-23.1.0]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[attrs-23.1.0]   File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
[attrs-23.1.0]   File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
[attrs-23.1.0]   File "<frozen importlib._bootstrap>", line 1128, in _find_and_load_unlocked
[attrs-23.1.0]   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
[attrs-23.1.0]   File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
[attrs-23.1.0]   File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
[attrs-23.1.0]   File "<frozen importlib._bootstrap>", line 1142, in _find_and_load_unlocked
[attrs-23.1.0] ModuleNotFoundError: No module named 'hatchling'
[attrs-23.1.0] 
```

### Expected Behavior

attrs depends on hatchling

### Actual Behavior

Parallel build fails

### Environment

```markdown
- Linux 
- Sage Version 10.2.beta6
```

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

**Comment by vbraun** [comment]
@mkoeppe probably from #36381
