### ISSUE TITLE
Docker 9.8 unable to log in, missing module argon2-cffi-bindings

### ISSUE THREAD

**Issue by admalledd** [sagemath/sage#36615]
### Steps To Reproduce

1. `docker run -it --rm sagemath/sagemath:9.8` 
2. `sage: from notebook.auth import passwd; print(passwd('SomePassword'))`
```
---> 1 from notebook.auth import passwd; print(passwd('cSomePassword))

File ~/sage/local/var/lib/sage/venv-python3.11.1/lib/python3.11/site-packages/notebook/auth/security.py:62, in passwd(passphrase, algorithm)
     59         raise ValueError('No matching passwords found. Giving up.')
     61 if algorithm == 'argon2':
---> 62     from argon2 import PasswordHasher
     63     ph = PasswordHasher(
     64         memory_cost=10240,
     65         time_cost=10,
     66         parallelism=8,
     67     )
     68     h = ph.hash(passphrase)

File ~/sage/local/var/lib/sage/venv-python3.11.1/lib/python3.11/site-packages/argon2/__init__.py:7
      1 # SPDX-License-Identifier: MIT
      3 """
      4 The secure Argon2 password hashing algorithm.
      5 """
----> 7 from . import exceptions, low_level, profiles
      8 from ._legacy import hash_password, hash_password_raw, verify_password
      9 from ._password_hasher import (
     10     DEFAULT_HASH_LENGTH,
     11     DEFAULT_MEMORY_COST,
   (...)
     15     PasswordHasher,
     16 )

File ~/sage/local/var/lib/sage/venv-python3.11.1/lib/python3.11/site-packages/argon2/low_level.py:15
     12 from enum import Enum
     13 from typing import Any
---> 15 from _argon2_cffi_bindings import ffi, lib
     17 from ._typing import Literal
     18 from .exceptions import HashingError, VerificationError, VerifyMismatchError

ModuleNotFoundError: No module named '_argon2_cffi_bindings'

```

That is just the minimal reproducible, my actual case is from me updating a existing docker setup and `jupyter_notebook_config.py` with pre-existing password exploding in my face with a not dissimilar traceback. 

I was able to temporarily resolve via `/sage-python -Im pip install argon2-cffi-bindings` but having it properly in the container would be best.

### Expected Behavior

Login or password generation successful

### Actual Behavior

```
Traceback (most recent call last):
      File "/home/sage/sage/local/var/lib/sage/venv-python3.11.1/lib/python3.11/site-packages/tornado/web.py", line 1711, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/sage/sage/local/var/lib/sage/venv-python3.11.1/lib/python3.11/site-packages/notebook/auth/login.py", line 84, in post
        if self.passwd_check(self.hashed_password, typed_password) and not new_password:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/sage/sage/local/var/lib/sage/venv-python3.11.1/lib/python3.11/site-packages/notebook/auth/login.py", line 75, in passwd_check
        return passwd_check(a, b)
               ^^^^^^^^^^^^^^^^^^
      File "/home/sage/sage/local/var/lib/sage/venv-python3.11.1/lib/python3.11/site-packages/notebook/auth/security.py", line 108, in passwd_check
        import argon2
      File "/home/sage/sage/local/var/lib/sage/venv-python3.11.1/lib/python3.11/site-packages/argon2/__init__.py", line 7, in <module>
        from . import exceptions, low_level, profiles
      File "/home/sage/sage/local/var/lib/sage/venv-python3.11.1/lib/python3.11/site-packages/argon2/low_level.py", line 15, in <module>
        from _argon2_cffi_bindings import ffi, lib
    ModuleNotFoundError: No module named '_argon2_cffi_bindings'

```

### Environment

```markdown
- **OS**: Docker
- **Sage Version**: https://hub.docker.com/layers/sagemath/sagemath/9.8/images/sha256-1dca662086a58ea620c54af578ee1d2ee5d0dbad01efed442a58ebf99c09fea9?context=explore tag 9.8
```

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

**Comment by srujan0404** [comment]
Try the old version of Docker, It may be a error in the new version @admalledd

**Comment by mkoeppe** [comment]
Closing as outdated. Newer versions have been available for a while
