### ISSUE TITLE
Compilation issues with newer compiler versions (v.16/17)

### ISSUE THREAD

**Issue by tobiasdiez** [sagemath/sage#36840]
### Steps To Reproduce

https://github.com/sagemath/sage/actions/runs/7122476648/job/19393562399
(which uses clang v16)

### Expected Behavior

Compiles fine

### Actual Behavior

Compilation stuck at `symbolic/expression`:
```
x86_64-apple-darwin13.4.0-clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/runner/miniconda3/envs/sage/include -fPIC -O2 -isystem /Users/runner/miniconda3/envs/sage/include -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem /Users/runner/miniconda3/envs/sage/include -D_FORTIFY_SOURCE=2 -isystem /Users/runner/miniconda3/envs/sage/include -I/Users/runner/miniconda3/envs/sage/include -I/Users/runner/miniconda3/envs/sage/include/singular -I/Users/runner/miniconda3/envs/sage/include -I/Users/runner/miniconda3/envs/sage/include/singular -I/Users/runner/miniconda3/envs/sage/include/ -I/Users/runner/miniconda3/envs/sage/include -I/Users/runner/miniconda3/envs/sage/include/ -I/Users/runner/miniconda3/envs/sage/include -Isage/symbolic -I/Users/runner/miniconda3/envs/sage/lib/python3.9/site-packages/cysignals -Isage/cpython -Isage/ext -I/Users/runner/miniconda3/envs/sage/include -I/Users/runner/miniconda3/envs/sage/lib/python3.9/site-packages/cypari2 -I/Users/runner/work/sage/sage/src -I/Users/runner/miniconda3/envs/sage/lib/python3.9/site-packages/numpy/core/include -I/Users/runner/miniconda3/envs/sage/include/python3.9 -I/Users/runner/miniconda3/envs/sage/include/python3.9 -c sage/symbolic/ginac/wildcard.cpp -o /var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/tmp53fmtkf5.build-temp/sage/symbolic/ginac/wildcard.o -std=c++11 -DSING_NDEBUG -DOM_NDEBUG -DSING_NDEBUG -DOM_NDEBUG -DSING_NDEBUG -DOM_NDEBUG -DSING_NDEBUG -DOM_NDEBUG -I/Users/runner/miniconda3/envs/sage/include -I/Users/runner/miniconda3/envs/sage/include/singular -I/Users/runner/miniconda3/envs/sage/include -I/Users/runner/miniconda3/envs/sage/include/singular -I/Users/runner/miniconda3/envs/sage/include/ -I/Users/runner/miniconda3/envs/sage/include -I/Users/runner/miniconda3/envs/sage/include/ -I/Users/runner/miniconda3/envs/sage/include
  x86_64-apple-darwin13.4.0-clang++ -bundle -undefined dynamic_lookup -Wl,-rpath,/Users/runner/miniconda3/envs/sage/lib -L/Users/runner/miniconda3/envs/sage/lib -Wl,-rpath,/Users/runner/miniconda3/envs/sage/lib -L/Users/runner/miniconda3/envs/sage/lib -Wl,-pie -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs -Wl,-rpath,/Users/runner/miniconda3/envs/sage/lib -L/Users/runner/miniconda3/envs/sage/lib -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem /Users/runner/miniconda3/envs/sage/include -D_FORTIFY_SOURCE=2 -isystem /Users/runner/miniconda3/envs/sage/include /var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/tmp53fmtkf5.build-temp/sage/symbolic/expression.o /var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/tmp53fmtkf5.build-temp/sage/symbolic/ginac/add.o /var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/tmp53fmtkf5.build-temp/sage/symbolic/ginac/archive.o /var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/tmp53fmtkf5.build-temp/sage/symbolic/ginac/assume.o /var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/tmp53fmtkf5.build-temp/sage/symbolic/ginac/basic.o /var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/tmp53fmtkf5.build-temp/sage/symbolic/ginac/cmatcher.o /var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/tmp53fmtkf5.build-temp/sage/symbolic/ginac/constant.o /var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/tmp53fmtkf5.build-temp/sage/symbolic/ginac/context.o /var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/tmp53fmtkf5.build-temp/sage/symbolic/ginac/ex.o /var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/tmp53fmtkf5.build-temp/sage/symbolic/ginac/expair.o /var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/tmp53fmtkf5.build-temp/sage/symbolic/ginac/expairseq.o /var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/tmp53fmtkf5.build-temp/sage/symbolic/ginac/exprseq.o /var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/tmp53fmtkf5.build-temp/sage/symbolic/ginac/fderivative.o /var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/tmp53fmtkf5.build-temp/sage/symbolic/ginac/function.o /var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/tmp53fmtkf5.build-temp/sage/symbolic/ginac/function_info.o /var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/tmp53fmtkf5.build-temp/sage/symbolic/ginac/infinity.o /var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/tmp53fmtkf5.build-temp/sage/symbolic/ginac/infoflagbase.o /var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/tmp53fmtkf5.build-temp/sage/symbolic/ginac/inifcns.o /var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/tmp53fmtkf5.build-temp/sage/symbolic/ginac/inifcns_comb.o /var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/tmp53fmtkf5.build-temp/sage/symbolic/ginac/inifcns_gamma.o /var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/tmp53fmtkf5.build-temp/sage/symbolic/ginac/inifcns_hyperb.o /var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/tmp53fmtkf5.build-temp/sage/symbolic/ginac/inifcns_hyperg.o /var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/tmp53fmtkf5.build-temp/sage/symbolic/ginac/inifcns_nstdsums.o /var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/tmp53fmtkf5.build-temp/sage/symbolic/ginac/inifcns_orthopoly.o /var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/tmp53fmtkf5.build-temp/sage/symbolic/ginac/inifcns_trans.o /var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/tmp53fmtkf5.build-temp/sage/symbolic/ginac/inifcns_trig.o /var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/tmp53fmtkf5.build-temp/sage/symbolic/ginac/inifcns_zeta.o /var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/tmp53fmtkf5.build-temp/sage/symbolic/ginac/lst.o /var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/tmp53fmtkf5.build-temp/sage/symbolic/ginac/matrix.o /var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/tmp53fmtkf5.build-temp/sage/symbolic/ginac/mpoly-giac.o /var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/tmp53fmtkf5.build-temp/sage/symbolic/ginac/mpoly-ginac.o /var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/tmp53fmtkf5.build-temp/sage/symbolic/ginac/mpoly-singular.o /var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/tmp53fmtkf5.build-temp/sage/symbolic/ginac/mpoly.o /var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/tmp53fmtkf5.build-temp/sage/symbolic/ginac/mul.o /var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/tmp53fmtkf5.build-temp/sage/symbolic/ginac/normal.o /var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/tmp53fmtkf5.build-temp/sage/symbolic/ginac/numeric.o /var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/tmp53fmtkf5.build-temp/sage/symbolic/ginac/operators.o /var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/tmp53fmtkf5.build-temp/sage/symbolic/ginac/order.o /var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/tmp53fmtkf5.build-temp/sage/symbolic/ginac/power.o /var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/tmp53fmtkf5.build-temp/sage/symbolic/ginac/print.o /var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/tmp53fmtkf5.build-temp/sage/symbolic/ginac/pseries.o /var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/tmp53fmtkf5.build-temp/sage/symbolic/ginac/py_funcs.o /var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/tmp53fmtkf5.build-temp/sage/symbolic/ginac/registrar.o /var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/tmp53fmtkf5.build-temp/sage/symbolic/ginac/relational.o /var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/tmp53fmtkf5.build-temp/sage/symbolic/ginac/remember.o /var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/tmp53fmtkf5.build-temp/sage/symbolic/ginac/sum.o /var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/tmp53fmtkf5.build-temp/sage/symbolic/ginac/symbol.o /var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/tmp53fmtkf5.build-temp/sage/symbolic/ginac/templates.o /var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/tmp53fmtkf5.build-temp/sage/symbolic/ginac/upoly-ginac.o /var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/tmp53fmtkf5.build-temp/sage/symbolic/ginac/useries.o /var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/tmp53fmtkf5.build-temp/sage/symbolic/ginac/utils.o /var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/tmp53fmtkf5.build-temp/sage/symbolic/ginac/wildcard.o -L/Users/runner/miniconda3/envs/sage/lib -lflint -lgmp -lSingular -lpolys -lflint -lmpfr -lgmp -lgmp -lfactory -lflint -lmpfr -lgmp -lntl -lgmp -lomalloc -lsingular_resources -lgsl -lgslcblas -lcblas -lm -o /var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/tmpvjecceif.build-lib/sage/symbolic/expression.cpython-39-darwin.so -lpari
  ld: warning: -pie being ignored. It is only used when linking a main executable
  Traceback (most recent call last):
    File "/Users/runner/miniconda3/envs/sage/lib/python3.9/site-packages/setuptools/_distutils/unixccompiler.py", line 185, in _compile
      self.spawn(compiler_so + cc_args + [src, '-o', obj] + extra_postargs)
    File "/Users/runner/miniconda3/envs/sage/lib/python3.9/site-packages/setuptools/_distutils/ccompiler.py", line 1041, in spawn
      spawn(cmd, dry_run=self.dry_run, **kwargs)
    File "/Users/runner/miniconda3/envs/sage/lib/python3.9/site-packages/setuptools/_distutils/spawn.py", line 70, in spawn
      raise DistutilsExecError(
  distutils.errors.DistutilsExecError: command '/Users/runner/miniconda3/envs/sage/bin/x86_64-apple-darwin13.4.0-clang' failed with exit code 1
```
(not sure how to get the actual error message)

### Additional Information

There is another issue in `bern_rat.cpp` which can be fixed with https://github.com/sagemath/sage/pull/36524/commits/1adecdbb964f6ccae7e681cac76646e7a80b2606

### Environment

```markdown
- **OS**: Macos and Linux
- **Sage Version**: dev
```

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

**Comment by mkoeppe** [comment]
> (not sure how to get the actual error message)

By looking further up in the output.

**Comment by dimpase** [comment]
```
2023-12-07T02:37:57.5656690Z   building 'sage.calculus.ode' extension
2023-12-07T02:37:57.6725070Z   x86_64-apple-darwin13.4.0-clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/runner/miniconda3/envs/sage/include -fPIC -O2 -isystem /Users/runner/miniconda3/envs/sage/include -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem /Users/runner/miniconda3/envs/sage/include -D_FORTIFY_SOURCE=2 -isystem /Users/runner/miniconda3/envs/sage/include -I/Users/runner/miniconda3/envs/sage/lib/python3.9/site-packages/cysignals -I/Users/runner/miniconda3/envs/sage/include -I/Users/runner/work/sage/sage/src -I/Users/runner/miniconda3/envs/sage/lib/python3.9/site-packages/numpy/core/include -I/Users/runner/miniconda3/envs/sage/include/python3.9 -I/Users/runner/miniconda3/envs/sage/include/python3.9 -c sage/calculus/ode.c -o /var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/tmp53fmtkf5.build-temp/sage/calculus/ode.o -DGSL_DISABLE_DEPRECATED
2023-12-07T02:37:58.2721910Z   sage/calculus/ode.c:8798:15: warning: assigning to 'gsl_odeiv_step_type *' from 'const gsl_odeiv_step_type *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
2023-12-07T02:37:58.2751550Z       __pyx_v_T = gsl_odeiv_step_rkf45;
2023-12-07T02:37:58.2756130Z                 ^ ~~~~~~~~~~~~~~~~~~~~
2023-12-07T02:37:58.2765700Z   sage/calculus/ode.c:8830:15: warning: assigning to 'gsl_odeiv_step_type *' from 'const gsl_odeiv_step_type *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
2023-12-07T02:37:58.2771850Z       __pyx_v_T = gsl_odeiv_step_rk2;
2023-12-07T02:37:58.2776250Z                 ^ ~~~~~~~~~~~~~~~~~~
2023-12-07T02:37:58.2783790Z   sage/calculus/ode.c:8862:15: warning: assigning to 'gsl_odeiv_step_type *' from 'const gsl_odeiv_step_type *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
2023-12-07T02:37:58.2789180Z       __pyx_v_T = gsl_odeiv_step_rk4;
2023-12-07T02:37:58.2792520Z                 ^ ~~~~~~~~~~~~~~~~~~
2023-12-07T02:37:58.2799880Z   sage/calculus/ode.c:8894:15: warning: assigning to 'gsl_odeiv_step_type *' from 'const gsl_odeiv_step_type *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
2023-12-07T02:37:58.2804510Z       __pyx_v_T = gsl_odeiv_step_rkck;
2023-12-07T02:37:58.2808540Z                 ^ ~~~~~~~~~~~~~~~~~~~
2023-12-07T02:37:58.2815950Z   sage/calculus/ode.c:8926:15: warning: assigning to 'gsl_odeiv_step_type *' from 'const gsl_odeiv_step_type *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
2023-12-07T02:37:58.2821000Z       __pyx_v_T = gsl_odeiv_step_rk8pd;
2023-12-07T02:37:58.2824300Z                 ^ ~~~~~~~~~~~~~~~~~~~~
2023-12-07T02:37:58.2831720Z   sage/calculus/ode.c:8958:15: warning: assigning to 'gsl_odeiv_step_type *' from 'const gsl_odeiv_step_type *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
2023-12-07T02:37:58.2874060Z       __pyx_v_T = gsl_odeiv_step_rk2imp;
2023-12-07T02:37:58.2880730Z                 ^ ~~~~~~~~~~~~~~~~~~~~~
2023-12-07T02:37:58.2894230Z   sage/calculus/ode.c:8990:15: warning: assigning to 'gsl_odeiv_step_type *' from 'const gsl_odeiv_step_type *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
2023-12-07T02:37:58.2900680Z       __pyx_v_T = gsl_odeiv_step_rk4imp;
2023-12-07T02:37:58.2905070Z                 ^ ~~~~~~~~~~~~~~~~~~~~~
2023-12-07T02:37:58.2915410Z   sage/calculus/ode.c:9022:15: warning: assigning to 'gsl_odeiv_step_type *' from 'const gsl_odeiv_step_type *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
2023-12-07T02:37:58.2921730Z       __pyx_v_T = gsl_odeiv_step_bsimp;
2023-12-07T02:37:58.2926060Z                 ^ ~~~~~~~~~~~~~~~~~~~~
2023-12-07T02:37:58.2936490Z   sage/calculus/ode.c:9097:15: warning: assigning to 'gsl_odeiv_step_type *' from 'const gsl_odeiv_step_type *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
2023-12-07T02:37:58.2943260Z       __pyx_v_T = gsl_odeiv_step_gear1;
2023-12-07T02:37:58.2947840Z                 ^ ~~~~~~~~~~~~~~~~~~~~
2023-12-07T02:37:58.2955280Z   sage/calculus/ode.c:9129:15: warning: assigning to 'gsl_odeiv_step_type *' from 'const gsl_odeiv_step_type *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
2023-12-07T02:37:58.2959800Z       __pyx_v_T = gsl_odeiv_step_gear2;
2023-12-07T02:37:58.2963000Z                 ^ ~~~~~~~~~~~~~~~~~~~~
2023-12-07T02:37:58.2970500Z   sage/calculus/ode.c:9614:26: error: incompatible function pointer types assigning to 'int (*)(double, const double *, double *, void *)' from 'int (double, double *, double *, void *)' [-Wincompatible-function-pointer-types]
2023-12-07T02:37:58.2975590Z       __pyx_v_sys.function = __pyx_f_4sage_8calculus_3ode_c_f_compiled;
2023-12-07T02:37:58.2978550Z                            ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2023-12-07T02:37:58.2988960Z   sage/calculus/ode.c:9623:26: error: incompatible function pointer types assigning to 'int (*)(double, const double *, double *, double *, void *)' from 'int (double, double *, double *, double *, void *)' [-Wincompatible-function-pointer-types]
2023-12-07T02:37:58.2996780Z       __pyx_v_sys.jacobian = __pyx_f_4sage_8calculus_3ode_c_jac_compiled;
2023-12-07T02:37:58.3016390Z                            ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2023-12-07T02:37:58.3028480Z   sage/calculus/ode.c:9655:26: error: incompatible function pointer types assigning to 'int (*)(double, const double *, double *, void *)' from 'int (double, double *, double *, void *)' [-Wincompatible-function-pointer-types]
2023-12-07T02:37:58.3034990Z       __pyx_v_sys.function = __pyx_f_4sage_8calculus_3ode_c_f;
2023-12-07T02:37:58.3039080Z                            ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2023-12-07T02:37:58.3049060Z   sage/calculus/ode.c:9664:26: error: incompatible function pointer types assigning to 'int (*)(double, const double *, double *, double *, void *)' from 'int (double, double *, double *, double *, void *)' [-Wincompatible-function-pointer-types]
2023-12-07T02:37:58.3055370Z       __pyx_v_sys.jacobian = __pyx_f_4sage_8calculus_3ode_c_jac;
2023-12-07T02:37:58.3058220Z                            ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2023-12-07T02:37:58.3662600Z   10 warnings and 4 errors generated.
```

**Comment by mkoeppe** [comment]
After making the obvious fix (#36925), the next error:
```
  sage/combinat/designs/subhypergraph_search.c:5033:64: error: incompatible function pointer types passing 'int (void *, void *)' to parameter of type 'int (* _Nonnull)(const void *, const void *)' [-Wincompatible-function-pointer-types]
    qsort(__pyx_v_tmp1.sets, __pyx_v_h1.m, (sizeof(uint64_t *)), __pyx_f_4sage_8combinat_7designs_20subhypergraph_search_cmp_128_bits);
                                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by mkoeppe** [comment]
Also
```
creating /var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/tmp6dd3b_xd.build-temp/sage/libs/giac
  x86_64-apple-darwin13.4.0-clang -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/runner/miniconda3/envs/sage/include -fPIC -O2 -isystem /Users/runner/miniconda3/envs/sage/include -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem /Users/runner/miniconda3/envs/sage/include -D_FORTIFY_SOURCE=2 -isystem /Users/runner/miniconda3/envs/sage/include -Isage/libs/giac -Isage/cpython -I/Users/runner/miniconda3/envs/sage/lib/python3.11/site-packages/cysignals -I/Users/runner/work/sage/sage/src -I/Users/runner/miniconda3/envs/sage/lib/python3.11/site-packages/numpy/core/include -I/Users/runner/miniconda3/envs/sage/include/python3.11 -I/Users/runner/miniconda3/envs/sage/include/python3.11 -c sage/libs/giac/giac.cpp -o /var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/tmp6dd3b_xd.build-temp/sage/libs/giac/giac.o
  In file included from sage/libs/giac/giac.cpp:1243:
  In file included from /Users/runner/miniconda3/envs/sage/include/giac/giac.h:5:
  In file included from /Users/runner/miniconda3/envs/sage/include/giac/poly.h:26:
  /Users/runner/miniconda3/envs/sage/include/giac/monomial.h:341:10: error: no template named 'pointer_to_binary_function' in namespace 'std'
      std::pointer_to_binary_function < const monomial<T> &, const monomial<T> &, bool> strictly_greater ;
      ~~~~~^
  /Users/runner/miniconda3/envs/sage/include/giac/monomial.h:342:28: error: no template named 'pointer_to_binary_function' in namespace 'std'
      sort_helper(const std::pointer_to_binary_function < const monomial<T> &, const monomial<T> &, bool> is_strictly_greater):strictly_greater(is_strictly_greater) {};
                        ~~~~~^
  /Users/runner/miniconda3/envs/sage/include/giac/monomial.h:343:41: error: no member named 'ptr_fun' in namespace 'std'
      sort_helper():strictly_greater(std::ptr_fun<const monomial<T> &, const monomial<T> &, bool>(m_lex_is_strictly_greater<T>)) {};
                                     ~~~~~^
  /Users/runner/miniconda3/envs/sage/include/giac/monomial.h:343:49: error: expected expression
      sort_helper():strictly_greater(std::ptr_fun<const monomial<T> &, const monomial<T> &, bool>(m_lex_is_strictly_greater<T>)) {};
                                                  ^
  /Users/runner/miniconda3/envs/sage/include/giac/monomial.h:343:70: error: expected expression
      sort_helper():strictly_greater(std::ptr_fun<const monomial<T> &, const monomial<T> &, bool>(m_lex_is_strictly_greater<T>)) {};
                                                                       ^
  /Users/runner/miniconda3/envs/sage/include/giac/monomial.h:343:95: error: expected '(' for function-style cast or type construction
      sort_helper():strictly_greater(std::ptr_fun<const monomial<T> &, const monomial<T> &, bool>(m_lex_is_strictly_greater<T>)) {};
                                                                                            ~~~~^
  /Users/runner/miniconda3/envs/sage/include/giac/monomial.h:680:18: error: no template named 'pointer_to_binary_function' in namespace 'std'
               const std::pointer_to_binary_function < const monomial<T> &, const monomial<T> &, bool> m_is_strictly_greater
                     ~~~~~^
  /Users/runner/miniconda3/envs/sage/include/giac/monomial.h:729:44: error: no template named 'pointer_to_binary_function' in namespace 'std'
      typedef std::map< index_t,T,const std::pointer_to_binary_function < const index_m &, const index_m &, bool> > application;
                                        ~~~~~^
  /Users/runner/miniconda3/envs/sage/include/giac/monomial.h:730:30: error: no type named 'ptr_fun' in namespace 'std'
      application produit(std::ptr_fun(is_strictly_greater));
                          ~~~~~^
```
(https://github.com/sagemath/sage/actions/runs/7267105390/job/19800194676?pr=36925#step:9:13394)

**Comment by mkoeppe** [comment]
And
```
  sage/modular/arithgroup/farey.cpp:740:19: error: use of undeclared identifier 'bind2nd'
                    bind2nd(greater<int>(), 0))/2;
                    ^
```
https://github.com/sagemath/sage/actions/runs/7267105390/job/19800194676?pr=36925#step:9:16824

**Comment by mkoeppe** [comment]
```
  sage/rings/polynomial/hilbert.c:8250:101: error: incompatible function pointer types passing 'int (*)(struct __pyx_obj_4sage_5rings_10polynomial_8polydict_ETuple *, int)' to parameter of type 'int (*)(struct __pyx_obj_4sage_5rings_10polynomial_8polydict_ETuple *)' [-Wincompatible-function-pointer-types]
    __pyx_t_5 = __Pyx_CFunc_int__lParenETuple__comma_int__dunderpyx_skip_dispatch__rParen_to_py_4self(__pyx_vtabptr_4sage_5rings_10polynomial_8polydict_ETuple->unweighted_degree); if (unlikely(!__pyx_t_5)) __PYX_ERR(0, 109, __pyx_L1_error)
                                                                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  sage/rings/polynomial/hilbert.c:5775:110: note: passing argument to parameter '__pyx_v_f' here
  static PyObject *__Pyx_CFunc_int__lParenETuple__comma_int__dunderpyx_skip_dispatch__rParen_to_py_4self(int (*__pyx_v_f)(struct __pyx_obj_4sage_5rings_10polynomial_8polydict_ETuple *)) {
                                                                                                               ^
  1 error generated.
  building 'sage.rings.polynomial.laurent_polynomial' extension
```
  sage/rings/polynomial/hilbert.c:8250:101: error: incompatible function pointer types passing 'int (*)(struct __pyx_obj_4sage_5rings_10polynomial_8polydict_ETuple *, int)' to parameter of type 'int (*)(struct __pyx_obj_4sage_5rings_10polynomial_8polydict_ETuple *)' [-Wincompatible-function-pointer-types]
    __pyx_t_5 = __Pyx_CFunc_int__lParenETuple__comma_int__dunderpyx_skip_dispatch__rParen_to_py_4self(__pyx_vtabptr_4sage_5rings_10polynomial_8polydict_ETuple->unweighted_degree); if (unlikely(!__pyx_t_5)) __PYX_ERR(0, 109, __pyx_L1_error)
                                                                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  sage/rings/polynomial/hilbert.c:5775:110: note: passing argument to parameter '__pyx_v_f' here
  static PyObject *__Pyx_CFunc_int__lParenETuple__comma_int__dunderpyx_skip_dispatch__rParen_to_py_4self(int (*__pyx_v_f)(struct __pyx_obj_4sage_5rings_10polynomial_8polydict_ETuple *)) {
                                                                                                               ^
  1 error generated.
  building 'sage.rings.polynomial.laurent_polynomial' extension

**Comment by Feyorsh** [comment]
> sage/rings/polynomial/hilbert.c:8250:101: error: incompatible function pointer types passing ...

[`unweighted_degree`](https://github.com/sagemath/sage/blob/ab1a517b64b02bf15bbcb8d7c2d4d643bd5eff9b/src/sage/rings/polynomial/polydict.pxd#L17) is declared as `cpdef`, which does not have a suitable function pointer type to pass to C functions ([offending usage](https://github.com/sagemath/sage/blob/ab1a517b64b02bf15bbcb8d7c2d4d643bd5eff9b/src/sage/rings/polynomial/hilbert.pyx#L109)). This can be solved with a separate `cdef` version of `unweighted_degree`, although admittedly I don't know how to do this in an elegant way (I just copied the function definition twice. Yuck!)

> sage/modular/arithgroup/farey.cpp:740:19: error: use of undeclared identifier 'bind2nd'

Pretty easy fix:
```
-                  bind2nd(greater<int>(), 0))/2;
+                  bind(greater<int>(), placeholders::_1, 0))/2;
```

I'm working on getting Giac to compile with Clang, but I'll update when I figure that out.
