### ISSUE TITLE
Failed installation using `pip`

### ISSUE THREAD

**Issue by cybaj** [sagemath/sage#36864]
### Steps To Reproduce

1. created virtual environment using `virtualenv` which of python version is 3.10
2. followed installation steps using `pip`
```
        $ python3 -m pip install sage_conf
        $ ls $(sage-config SAGE_SPKG_WHEELS)
        $ python3 -m pip install $(sage-config SAGE_SPKG_WHEELS)/*.whl 
        $ python3 -m pip install sagemath-standard
```
3. error occurred at last step. `$ python3 -m pip install sagemath-standard`

### Expected Behavior

sage installation success.

### Actual Behavior

```text
✗ pip install sagemath-standard
Collecting sagemath-standard
  Using cached sagemath-standard-10.2.tar.gz (19.4 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
ERROR: Exception:
Traceback (most recent call last):
  File "/Users/~/envs/python/basic_math/venv_310/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 180, in exc_logging_wrapper
    status = run_func(*args)
  File "/Users/~/envs/python/basic_math/venv_310/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 245, in wrapper
    return func(self, options, args)
  File "/Users/~/envs/python/basic_math/venv_310/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 377, in run
    requirement_set = resolver.resolve(
  File "/Users/~/envs/python/basic_math/venv_310/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 95, in resolve
    result = self._result = resolver.resolve(
  File "/Users/~/envs/python/basic_math/venv_310/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/Users/~/envs/python/basic_math/venv_310/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 397, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "/Users/~/envs/python/basic_math/venv_310/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 173, in _add_to_criteria
    if not criterion.candidates:
  File "/Users/~/envs/python/basic_math/venv_310/lib/python3.10/site-packages/pip/_vendor/resolvelib/structs.py", line 156, in __bool__
    return bool(self._sequence)
  File "/Users/~/envs/python/basic_math/venv_310/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 155, in __bool__
    return any(self)
  File "/Users/~/envs/python/basic_math/venv_310/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "/Users/~/envs/python/basic_math/venv_310/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 47, in _iter_built
    candidate = func()
  File "/Users/~/envs/python/basic_math/venv_310/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 211, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "/Users/~/envs/python/basic_math/venv_310/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 293, in __init__
    super().__init__(
  File "/Users/~/envs/python/basic_math/venv_310/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 156, in __init__
    self.dist = self._prepare()
  File "/Users/~/envs/python/basic_math/venv_310/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 225, in _prepare
    dist = self._prepare_distribution()
  File "/Users/~/envs/python/basic_math/venv_310/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 304, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "/Users/~/envs/python/basic_math/venv_310/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 525, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/Users/~/envs/python/basic_math/venv_310/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 640, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
  File "/Users/~/envs/python/basic_math/venv_310/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 71, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(
  File "/Users/~/envs/python/basic_math/venv_310/lib/python3.10/site-packages/pip/_internal/distributions/sdist.py", line 54, in prepare_distribution_metadata
    self._install_build_reqs(finder)
  File "/Users/~/envs/python/basic_math/venv_310/lib/python3.10/site-packages/pip/_internal/distributions/sdist.py", line 124, in _install_build_reqs
    build_reqs = self._get_build_requires_wheel()
  File "/Users/~/envs/python/basic_math/venv_310/lib/python3.10/site-packages/pip/_internal/distributions/sdist.py", line 101, in _get_build_requires_wheel
    return backend.get_requires_for_build_wheel()
  File "/Users/~/envs/python/basic_math/venv_310/lib/python3.10/site-packages/pip/_internal/utils/misc.py", line 751, in get_requires_for_build_wheel
    return super().get_requires_for_build_wheel(config_settings=cs)
  File "/Users/~/envs/python/basic_math/venv_310/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_impl.py", line 166, in get_requires_for_build_wheel
    return self._call_hook('get_requires_for_build_wheel', {
  File "/Users/~/envs/python/basic_math/venv_310/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_impl.py", line 321, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
pip._vendor.pyproject_hooks._impl.BackendUnavailable: Traceback (most recent call last):
  File "/Users/~/envs/python/basic_math/venv_310/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 77, in _build_backend
    obj = import_module(mod_path)
  File "/usr/local/Cellar/python@3.10/3.10.13/Frameworks/Python.framework/Versions/3.10/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'setuptools'
```

### Additional Information

other steps done peacefully.

### Environment

```markdown
- **OS**: MacOS 12.7.1 Monterey
- **Sage Version**: sagemath-standard-10.2
```

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

**Comment by cybaj** [comment]
```
Python 3.10.13 (main, Aug 24 2023, 22:46:18) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import setuptools
packages/setuptools/version.py'>
>>> setuptools.__version__
'69.0.2'
```

**Comment by mkoeppe** [comment]
Try `python3 -m pip install --no-build-isolation sagemath-standard`

**Comment by cybaj** [comment]
> Try `python3 -m pip install --no-build-isolation sagemath-standard`

thank you for the suggestion. but, ...

```text
$ python3 -m pip install --no-build-isolation sagemath-standard
Collecting sagemath-standard
  Using cached sagemath-standard-10.2.tar.gz (19.4 MB)
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [13 lines of output]
      Traceback (most recent call last):
        File "/Users/~/envs/python/basic_math/venv_310/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/~/envs/python/basic_math/venv_310/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/~/envs/python/basic_math/venv_310/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/Users/~/envs/python/basic_math/venv_310/lib/python3.10/site-packages/setuptools/build_meta.py", line 366, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/Users/~/envs/python/basic_math/venv_310/lib/python3.10/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 42, in <module>
      ModuleNotFoundError: No module named 'sage_setup'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned
```

**Comment by mkoeppe** [comment]
OK... run `python3 -m pip install sage_setup` first.

**Comment by mkoeppe** [comment]
Looks like we need to update https://github.com/sagemath/sage#alternative-installation-using-pypi

**Comment by cybaj** [comment]
thank you! it is quite simple...
if the installation done successfully, I would like to make the pull request by your suggestion.
```text
        $ python3 -m pip install sage_conf
        $ ls $(sage-config SAGE_SPKG_WHEELS)
        $ python3 -m pip install $(sage-config SAGE_SPKG_WHEELS)/*.whl sage_setup
        $ python3 -m pip install --no-build-isolation sagemath-standard 
```

**Comment by cybaj** [comment]
sorry for the failure. would you like to help me, @mkoeppe ?

during the installation, build command(using clang)'s options, actually '-I` flag need to be update.

```text
      [557/557] creating build/temp.macosx-12-x86_64-cpython-310/build/cythonized/sage/monoids
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -Isage/cpython -I/Users/~/envs/python/basic_math/venv_310/lib/python3.10/site-packages/cysignals -I/private/var/folders/l1/q639k2md3mv1brq7b3_p_g1h0000gn/T/pip-install-q9lnc2tw/sagemath-standard_d86efec5f7b0489990e0551c16850faa -I/Users/~/envs/python/basic_math/venv_310/lib/python3.10/site-packages/numpy/core/include -I/usr/local/opt/python@3.10/Frameworks/Python.framework/Versions/3.10/include/python3.10 -Ibuild/cythonized -I/Users/~/envs/python/basic_math/venv_310/include -I/usr/local/opt/python@3.10/Frameworks/Python.framework/Versions/3.10/include/python3.10 -c build/cythonized/sage/monoids/free_abelian_monoid_element.c -o build/temp.macosx-12-x86_64-cpython-310/build/cythonized/sage/monoids/free_abelian_monoid_element.o -fno-strict-aliasing -DCYTHON_CLINE_IN_TRACEBACK=1
      build/cythonized/sage/monoids/free_abelian_monoid_element.c:1215:10: fatal error: 'gmp.h' file not found
      #include "gmp.h"
               ^~~~~~~
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for sagemath-standard
Failed to build sagemath-standard
ERROR: Could not build wheels for sagemath-standard, which is required to install pyproject.toml-based projects
```

```
✗ find /usr /opt -name "gmp.h"
find: /usr/sbin/authserver: Permission denied
/usr/local/include/gmp.h
find: /usr/local/var/run/watchman/root-state: Permission denied
/usr/local/Cellar/gmp/6.3.0/include/gmp.h
```

if you make some suggestion to fix this, I would like to make pull request. I would like to add option `-I/usr/local/include/` to the build command creation. is it okay to add this to [config.rpath](https://github.com/sagemath/sage/blob/develop/config/config.rpath) or [Makefile](https://github.com/sagemath/sage/blob/develop/build/make/Makefile.in)?

**Comment by mkoeppe** [comment]
Use `. ./.homebrew-build-env` and then try the previous command again
