### ISSUE TITLE
Random test failure in drinfeld modules

### ISSUE THREAD

**Issue by tobiasdiez** [sagemath/sage#37071]
### Expected Behavior

Tests pass

### Actual Behavior

```
File "src/sage/rings/function_field/drinfeld_modules/morphism.py", line 543, in sage.rings.function_field.drinfeld_modules.morphism.?.__invert__
Failed example:
    f = phi.hom(K.random_element())  # known bug: macos (sporadic ValueError: the input does not define an isogeny)
Exception raised:
    Traceback (most recent call last):
      File "/home/runner/work/sage/sage/src/sage/doctest/forker.py", line 712, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/home/runner/work/sage/sage/src/sage/doctest/forker.py", line 1147, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.rings.function_field.drinfeld_modules.morphism.?.__invert__[5]>", line 1, in <module>
        f = phi.hom(K.random_element())  # known bug: macos (sporadic ValueError: the input does not define an isogeny)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/runner/work/sage/sage/src/sage/rings/function_field/drinfeld_modules/drinfeld_module.py", line 2024, in hom
        codomain = self.velu(x)
                   ^^^^^^^^^^^^
      File "/home/runner/work/sage/sage/src/sage/rings/function_field/drinfeld_modules/drinfeld_module.py", line 1930, in velu
        raise e
    ValueError: the input does not define an isogeny
```

### Additional Information

https://github.com/sagemath/sage/actions/runs/7506353535/job/20437594453#step:11:7266

### Environment

```markdown
Conda? Happens on linux as well on macos
```

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

**Comment by mkoeppe** [comment]
fedora-30-standard
https://github.com/sagemath/sage/actions/runs/7852863047/job/21431835935?pr=37277#step:11:11020

**Comment by antonio-rojas** [comment]
Can reproduce on Arch with `--random-seed=43242167682185424856181660049496597050`

**Comment by mkoeppe** [comment]
Also linuxmint-21-minimal https://github.com/mkoeppe/sage/actions/runs/8761823524/job/24053539634#step:11:10622
```
sage -t --random-seed=289169991370280275942346929889231818874 src/sage/rings/function_field/drinfeld_modules/morphism.py
```
