### ISSUE TITLE
AssertionError when doctesting sage/groups/perm_gps/partn_ref/data_structures.pyx

### ISSUE THREAD

**Issue by tornaria** [sagemath/sage#37248]
I discovered this on 10.3.beta7, but it also happens on 10.2 for the same random seed.

```
$ sage --version
SageMath version 10.2, Release Date: 2023-12-03
$ sage -t --long --warn-long 60.0 --random-seed=160014493591975964239419823603106997115 /usr/lib/python3.12/site-packages/sage/groups/perm_gps/partn_ref/data_structures.pyx
Running doctests with ID 2024-02-06-15-01-32-15f21002.
Running with SAGE_LOCAL='/usr' and SAGE_VENV='/usr'
Using --optional=pip,sage
Features to be detected: 4ti2,benzene,bliss,buckygen,conway_polynomials,csdp,cvxopt,cvxopt,database_cremona_ellcurve,database_cremona_mini_ellcurve,database_cubic_hecke,database_jones_numfield,database_knotinfo,dvipng,fpylll,gap_package_atlasrep,gap_package_design,gap_package_grape,gap_package_guava,gap_package_hap,gap_package_polycyclic,gap_package_qpa,gap_package_quagroup,gfan,graphviz,imagemagick,ipython,jupymake,kenzo,latte_int,lrcalc_python,lrslib,mcqd,meataxe,mpmath,msolve,nauty,networkx,numpy,palp,pandoc,pdf2svg,pdftocairo,pexpect,phitigra,pillow,plantri,polytopes_db,polytopes_db_4d,pplpy,primecountpy,ptyprocess,pynormaliz,pyparsing,python_igraph,requests,rubiks,sage.combinat,sage.geometry.polyhedron,sage.graphs,sage.groups,sage.libs.ecl,sage.libs.flint,sage.libs.gap,sage.libs.linbox,sage.libs.m4ri,sage.libs.ntl,sage.libs.pari,sage.libs.singular,sage.misc.cython,sage.modular,sage.modules,sage.numerical.mip,sage.plot,sage.rings.complex_double,sage.rings.finite_rings,sage.rings.function_field,sage.rings.number_field,sage.rings.padics,sage.rings.polynomial.pbori,sage.rings.real_double,sage.rings.real_mpfr,sage.sat,sage.schemes,sage.symbolic,sage_numerical_backends_coin,sagemath_doc_html,scipy,singular,sphinx,sympy,tdlib
Doctesting 1 file.
sage -t --long --warn-long 60.0 --random-seed=160014493591975964239419823603106997115 /usr/lib/python3.12/site-packages/sage/groups/perm_gps/partn_ref/data_structures.pyx
**********************************************************************
File "/usr/lib/python3.12/site-packages/sage/groups/perm_gps/partn_ref/data_structures.pyx", line 1276, in sage.groups.perm_gps.partn_ref.data_structures.SC_test_list_perms
Failed example:
    for n in range(4,9):              # long time
        test_stab_chain_fns_4(n, 1, 1, 0)
        test_stab_chain_fns_4(n, 2, 1, 0)
        test_stab_chain_fns_4(n, 2, 1, 0)
        test_stab_chain_fns_4(n, 2, 1, 0)
        test_stab_chain_fns_4(n, 2, 1, 0)
        test_stab_chain_fns_4(n, 3, 1, 0)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python3.12/site-packages/sage/doctest/forker.py", line 709, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/usr/lib/python3.12/site-packages/sage/doctest/forker.py", line 1144, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.groups.perm_gps.partn_ref.data_structures.SC_test_list_perms[23]>", line 7, in <module>
        test_stab_chain_fns_4(n, Integer(3), Integer(1), Integer(0))
      File "<doctest sage.groups.perm_gps.partn_ref.data_structures.SC_test_list_perms[22]>", line 7, in test_stab_chain_fns_4
        SC_test_list_perms(perms, n, limit, gap, Integer(0), contains)
      File "sage/groups/perm_gps/partn_ref/data_structures.pyx", line 1606, in sage.groups.perm_gps.partn_ref.data_structures.SC_test_list_perms (build/cythonized/sage/groups/perm_gps/partn_ref/data_structures.c:35412)
        raise
      File "sage/groups/perm_gps/partn_ref/data_structures.pyx", line 1551, in sage.groups.perm_gps.partn_ref.data_structures.SC_test_list_perms (build/cythonized/sage/groups/perm_gps/partn_ref/data_structures.c:34119)
        raise AssertionError
    AssertionError
**********************************************************************
1 item had failures:
   1 of  46 in sage.groups.perm_gps.partn_ref.data_structures.SC_test_list_perms
    [49 tests, 1 failure, 4.20 s]
----------------------------------------------------------------------
sage -t --long --warn-long 60.0 --random-seed=160014493591975964239419823603106997115 /usr/lib/python3.12/site-packages/sage/groups/perm_gps/partn_ref/data_structures.pyx  # 1 doctest failed
----------------------------------------------------------------------
Total time for all tests: 9.3 seconds
    cpu time: 3.9 seconds
    cumulative wall time: 4.2 seconds
Features detected for doctesting: sage.groups
```

**Comment by DaveWitteMorris** [comment]
Presumably this is closely related to #32187.

**Comment by tornaria** [comment]
Thanks, #32187 looks very much the same. Closing as duplicate.
