### ISSUE TITLE
Segfaults in `sage.libs.gap.element`

### ISSUE THREAD

**Issue by mkoeppe** [sagemath/sage#37289]
On [test / linux (ubuntu-jammy, minimal)](https://github.com/sagemath/sage/actions/runs/7852863047/job/21431835442?pr=37277#logs)
```
sage -t --random-seed=16825356534323926666935235918487534724 src/sage/libs/gap/element.pyx
**********************************************************************
File "src/sage/libs/gap/element.pyx", line 1152, in sage.libs.gap.element.GapElement.noexcept
Failed example:
    libgap.CyclicGroup(2) ^ 2
Expected:
    Traceback (most recent call last):
    ...
    GAPError: Error, no method found!
    Error, no 1st choice method found for `^' on 2 arguments
Got:
    <BLANKLINE>
    Traceback (most recent call last):
      File "/sage/src/sage/doctest/forker.py", line 712, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/sage/src/sage/doctest/forker.py", line 1147, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.libs.gap.element.GapElement.noexcept[8]>", line 1, in <module>
        libgap.CyclicGroup(Integer(2)) ** Integer(2)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "sage/libs/gap/element.pyx", line 2510, in sage.libs.gap.element.GapElement_Function.__call__
        a = [x if isinstance(x, GapElement) else libgap(x) for x in args]
      File "sage/structure/parent.pyx", line 901, in sage.structure.parent.Parent.__call__
        return mor._call_(x)
      File "sage/structure/coerce_maps.pyx", line 158, in sage.structure.coerce_maps.DefaultConvertMap_unique._call_
        return C._element_constructor(x)
      File "sage/libs/gap/libgap.pyx", line 319, in sage.libs.gap.libgap.Gap._element_constructor_
        return x._libgap_()
      File "sage/structure/sage_object.pyx", line 758, in sage.structure.sage_object.SageObject._libgap_
        return libgap.eval(self)
      File "sage/libs/gap/libgap.pyx", line 406, in sage.libs.gap.libgap.Gap.eval
        elem = make_any_gap_element(self, gap_eval(gap_command))
      File "sage/libs/gap/util.pyx", line 361, in sage.libs.gap.util.gap_eval
        sig_on()
    cysignals.signals.SignalError: Segmentation fault
```
(https://github.com/sagemath/sage/actions/runs/7852863047/job/21431835442?pr=37277#step:11:8409)

**Comment by tornaria** [comment]
I think this is the same issue I mentioned in passing in #37263.

Can you try `sage -c 'gap(1)'` or `sage -c 'libgap(1)'` ? Both fail really bad.

Then try setting `GAP_ROOT_PATHS=/usr/lib/gap;/usr/share/gap`. The problem for me is that gap is installed in the system prefix (/usr) but the default search path uses SAGE_LOCAL as prefix.

**Comment by tornaria** [comment]
Actually, this looks different since it's not using system gap afaict.

Maybe it is related to #37026.

**Comment by orlitzky** [comment]
This is the error-handling case of a libgap function call and is very probably https://github.com/sagemath/sage/issues/37026 (which was just fixed).
