### ISSUE TITLE
Random ValueError in `ell_finite_field`

### ISSUE THREAD

**Issue by tobiasdiez** [sagemath/sage#37294]
### Steps To Reproduce

https://github.com/sagemath/sage/actions/runs/7762393207/job/21172760911
https://github.com/sagemath/sage/actions/runs/7683999853/job/20939981290

### Expected Behavior

Test pass

### Actual Behavior

```
sage -t --random-seed=294816239965159080305344493013552438917 src/sage/schemes/elliptic_curves/ell_finite_field.py
**********************************************************************
File "src/sage/schemes/elliptic_curves/ell_finite_field.py", line 1790, in sage.schemes.elliptic_curves.ell_finite_field.EllipticCurve_finite_field.twists
Failed example:
    for _ in range(10):
        V = Ideal([eq, A + B - F.random_element()]).variety()
        if not V:
            continue
        sol = choice(V)
        a, b = sol[A], sol[B]
        try:
            twists2.append(EllipticCurve([a, b]))
        except ArithmeticError:
            pass
Exception raised:
    Traceback (most recent call last):
      File "/Users/runner/work/sage/sage/src/sage/doctest/forker.py", line 712, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/Users/runner/work/sage/sage/src/sage/doctest/forker.py", line 1147, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.schemes.elliptic_curves.ell_finite_field.EllipticCurve_finite_field.twists[38]>", line 2, in <module>
        V = Ideal([eq, A + B - F.random_element()]).variety()
      File "/Users/runner/work/sage/sage/src/sage/rings/polynomial/multi_polynomial_ideal.py", line 305, in __call__
        return self.f(self._instance, *args, **kwds)
      File "/Users/runner/work/sage/sage/src/sage/rings/polynomial/multi_polynomial_ideal.py", line 2685, in variety
        return self._variety_triangular_decomposition(ring)
      File "/Users/runner/work/sage/sage/src/sage/rings/polynomial/multi_polynomial_ideal.py", line 2833, in _variety_triangular_decomposition
        raise ValueError("The dimension of the ideal is %s, but it should be 0" % d)
    ValueError: The dimension of the ideal is 1, but it should be 0
```

### Environment

```markdown
macos?
```

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

**Comment by GiacomoPope** [comment]
Was this not fixed in: https://github.com/sagemath/sage/pull/37202

**Comment by yyyyx4** [comment]
Agreed; this appears to be a duplicate.
