### ISSUE TITLE
Random RuntimeError in `ell_rational_field`/`lfunctions`

### ISSUE THREAD

**Issue by tobiasdiez** [sagemath/sage#37293]
### Steps To Reproduce

https://github.com/sagemath/sage/actions/runs/7635126339/job/20800039628?pr=36960#step:10:8417

### Expected Behavior

Test pass

### Actual Behavior

```
sage -t --random-seed=47305490746967553648694173593624918461 src/sage/schemes/elliptic_curves/ell_rational_field.py
**********************************************************************
File "src/sage/schemes/elliptic_curves/ell_rational_field.py", line 3606, in sage.schemes.elliptic_curves.ell_rational_field.EllipticCurve_rational_field.lseries_gross_zagier
Failed example:
    L(2) + E.lseries_gross_zagier(A^2)(2)
Exception raised:
    Traceback (most recent call last):
      File "/Users/runner/work/sage/sage/src/sage/doctest/forker.py", line 712, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/Users/runner/work/sage/sage/src/sage/doctest/forker.py", line 1147, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.schemes.elliptic_curves.ell_rational_field.EllipticCurve_rational_field.lseries_gross_zagier[6]>", line 1, in <module>
        L(Integer(2)) + E.lseries_gross_zagier(A**Integer(2))(Integer(2))
      File "/Users/runner/work/sage/sage/src/sage/modular/modform/l_series_gross_zagier.py", line 88, in __call__
        return self._dokchister(s, der)
      File "/Users/runner/work/sage/sage/src/sage/lfunctions/dokchitser.py", line 525, in __call__
        raise RuntimeError
    RuntimeError
```

### Environment

```markdown
macos?
```

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

**Comment by tobiasdiez** [comment]
```
src/bin/sage -t --warn-long 5.0 --random-seed=32646845553424535681593623245336765186 src/sage/schemes/elliptic_curves/ell_rational_field.py
**********************************************************************
Error: Failed example:: Exception raised:
Traceback (most recent call last):
  File "/Users/runner/miniconda3/envs/sage-dev/lib/python3.13/site-packages/sage/doctest/forker.py", line 734, in _run
    self.compile_and_execute(example, compiler, test.globs)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/runner/miniconda3/envs/sage-dev/lib/python3.13/site-packages/sage/doctest/forker.py", line 1158, in compile_and_execute
    exec(compiled, globs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "<doctest sage.schemes.elliptic_curves.ell_rational_field.EllipticCurve_rational_field.lseries_gross_zagier[6]>", line 1, in <module>
    L(Integer(2)) + E.lseries_gross_zagier(A**Integer(2))(Integer(2))
    ~^^^^^^^^^^^^
  File "/Users/runner/miniconda3/envs/sage-dev/lib/python3.13/site-packages/sage/modular/modform/l_series_gross_zagier.py", line 93, in __call__
    return self._dokchister.derivative(s, der)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/Users/runner/miniconda3/envs/sage-dev/lib/python3.13/site-packages/sage/lfunctions/dokchitser.py", line 575, in derivative
    return self.__CC(z[i:])
           ~~~~~~~~~^^^^^^^
  File "sage/rings/complex_mpfr.pyx", line 478, in sage.rings.complex_mpfr.ComplexField_class.__call__
    return Parent.__call__(self, x)
  File "sage/structure/parent.pyx", line 899, in sage.structure.parent.Parent.__call__
    return mor._call_(x)
  File "sage/structure/coerce_maps.pyx", line 92, in sage.structure.coerce_maps.DefaultConvertMap_unique._call_
    raise
  File "sage/structure/coerce_maps.pyx", line 87, in sage.structure.coerce_maps.DefaultConvertMap_unique._call_
    return C._element_constructor(x)
  File "sage/rings/complex_mpfr.pyx", line 532, in sage.rings.complex_mpfr.ComplexField_class._element_constructor_
    raise ValueError(f'given string {x!r} is not a complex number')
ValueError: given string '\n-0.6130020461228941721' is not a complex number

    L(2) + E.lseries_gross_zagier(A^2)(2)
Exception raised:
    Traceback (most recent call last):
      File "/Users/runner/miniconda3/envs/sage-dev/lib/python3.13/site-packages/sage/doctest/forker.py", line 734, in _run
        self.compile_and_execute(example, compiler, test.globs)
        ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/runner/miniconda3/envs/sage-dev/lib/python3.13/site-packages/sage/doctest/forker.py", line 1158, in compile_and_execute
        exec(compiled, globs)
        ~~~~^^^^^^^^^^^^^^^^^
      File "<doctest sage.schemes.elliptic_curves.ell_rational_field.EllipticCurve_rational_field.lseries_gross_zagier[6]>", line 1, in <module>
        L(Integer(2)) + E.lseries_gross_zagier(A**Integer(2))(Integer(2))
        ~^^^^^^^^^^^^
      File "/Users/runner/miniconda3/envs/sage-dev/lib/python3.13/site-packages/sage/modular/modform/l_series_gross_zagier.py", line 93, in __call__
        return self._dokchister.derivative(s, der)
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
      File "/Users/runner/miniconda3/envs/sage-dev/lib/python3.13/site-packages/sage/lfunctions/dokchitser.py", line 575, in derivative
        return self.__CC(z[i:])
               ~~~~~~~~~^^^^^^^
      File "sage/rings/complex_mpfr.pyx", line 478, in sage.rings.complex_mpfr.ComplexField_class.__call__
        return Parent.__call__(self, x)
      File "sage/structure/parent.pyx", line 899, in sage.structure.parent.Parent.__call__
        return mor._call_(x)
      File "sage/structure/coerce_maps.pyx", line 92, in sage.structure.coerce_maps.DefaultConvertMap_unique._call_
        raise
      File "sage/structure/coerce_maps.pyx", line 87, in sage.structure.coerce_maps.DefaultConvertMap_unique._call_
        return C._element_constructor(x)
      File "sage/rings/complex_mpfr.pyx", line 532, in sage.rings.complex_mpfr.ComplexField_class._element_constructor_
        raise ValueError(f'given string {x!r} is not a complex number')
    ValueError: given string '\n-0.6130020461228941721' is not a complex number
**********************************************************************
```
https://github.com/sagemath/sage/actions/runs/18863292042/job/53826049927

**Comment by cxzhong** [comment]
Seems I do not see this again.
