### ISSUE TITLE
Doctest failure in `File "src/sage/repl/interpreter.py", line 77, in sage.repl.interpreter`

### ISSUE THREAD

**Issue by tornaria** [sagemath/sage#37307]
This arises when installing a beta of sagelib in a venv (10.3.beta7) with a different version installed in the system (10.2).  Here I have sagelib installed in a venv using the command `venv-sagelib/bin/pip install --no-build-isolation --no-deps -e -v ./src` for an editable build, but I also tried without `-e` and is the same.

To run sage in the venv I use `venv-sagelib/bin/sage`; all doctests pass except this one:
```
sage -t --random-seed=33905513055388896759428798195483723617 src/sage/repl/interpreter.py
**********************************************************************
File "src/sage/repl/interpreter.py", line 77, in sage.repl.interpreter
Failed example:
    print("dummy line"); shell.run_cell('1/0') # see #25320 for the reason of the `...` and the dummy line in this test
Expected:
    dummy line
    ...
    ZeroDivisionError...Traceback (most recent call last)
    ...
    ----> 1 Integer(1)/Integer(0)
    .../sage/rings/integer.pyx... in sage.rings.integer.Integer...div...
    ...
    -> ...                  raise ZeroDivisionError("rational division by zero")
       ...            x = <Rational> Rational.__new__(Rational)
       ...            mpq_div_zz(x.value, ....value, (<Integer>right).value)
    <BLANKLINE>
    ZeroDivisionError: rational division by zero
Got:
    dummy line
    ---------------------------------------------------------------------------
    ZeroDivisionError                         Traceback (most recent call last)
    Cell In[1], line 1
    ----> 1 Integer(1)/Integer(0)
    <BLANKLINE>
    File /usr/lib/python3.12/site-packages/sage/rings/integer.pyx:2018, in sage.rings.integer.Integer.__truediv__()
       2016 if mpz_sgn((<Integer>right).value) == 0:
       2017     raise ZeroDivisionError("rational division by zero")
    -> 2018 x = <Rational> Rational.__new__(Rational)
       2019 mpq_div_zz(x.value, (<Integer>left).value, (<Integer>right).value)
       2020 return x
    <BLANKLINE>
    ZeroDivisionError: rational division by zero
**********************************************************************
```

The problem here is that the traceback printout is showing the file from the system site-packages instead of the correct file. The line 2018 is the correct one, it's just that the old version is shifted by one:
```
$ cat -n src/sage/rings/integer.pyx | grep -C2 '^\s*2018\s'
  2016          if type(left) is type(right):
  2017              if mpz_sgn((<Integer>right).value) == 0:
  2018                  raise ZeroDivisionError("rational division by zero")
  2019              x = <Rational> Rational.__new__(Rational)
  2020              mpq_div_zz(x.value, (<Integer>left).value, (<Integer>right).value)
```
```
$ cat -n /usr/lib/python3.12/site-packages/sage/rings/integer.pyx | grep -C2 '^\s*2018\s'
  2016              if mpz_sgn((<Integer>right).value) == 0:
  2017                  raise ZeroDivisionError("rational division by zero")
  2018              x = <Rational> Rational.__new__(Rational)
  2019              mpq_div_zz(x.value, (<Integer>left).value, (<Integer>right).value)
  2020              return x
```

Here's how to reproduce this directly:
```
$ venv-sagelib/bin/sage
┌────────────────────────────────────────────────────────────────────┐
│ SageMath version 10.3.beta7, Release Date: 2024-02-02              │
│ Using Python 3.12.1. Type "help()" for help.                       │
└────────────────────────────────────────────────────────────────────┘
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Warning: this is a prerelease version, and it may be unstable.     ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
sage: 1/0
---------------------------------------------------------------------------
ZeroDivisionError                         Traceback (most recent call last)
Cell In[1], line 1
----> 1 Integer(1)/Integer(0)

File /usr/lib/python3.12/site-packages/sage/rings/integer.pyx:2018, in sage.rings.integer.Integer.__truediv__()
   2016 if mpz_sgn((<Integer>right).value) == 0:
   2017     raise ZeroDivisionError("rational division by zero")
-> 2018 x = <Rational> Rational.__new__(Rational)
   2019 mpq_div_zz(x.value, (<Integer>left).value, (<Integer>right).value)
   2020 return x

ZeroDivisionError: rational division by zero
```

**Comment by mkoeppe** [comment]
It would be worth checking who exactly is printing this traceback. Is it IPython or core CPython code?
