### ISSUE TITLE
ubuntu-24.04 (`--enable-system-site-packages`): Error installing sagemath_doc_html

### ISSUE THREAD

**Issue by YijunYuan** [sagemath/sage#37936]
### Environment

```markdown
- **OS**: Ubuntu 24.04 (WSL2)
- **Sage Version**: 10.3
```

### Steps To Reproduce

```bash
./configure --enable-system-site-packages
make -j16
```
```bash
sagemath_doc_html-none
====================================================
Setting up build directory for sagemath_doc_html-none
****************************************************
Host system:
Linux YijunYuan-PC 5.15.146.1-microsoft-standard-WSL2 #1 SMP Thu Jan 11 04:09:03 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
****************************************************
C compiler: gcc
C compiler version:
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-linux-gnu/13/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:amdgcn-amdhsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 13.2.0-23ubuntu4' --with-bugurl=file:///usr/share/doc/gcc-13/README.Bugs --enable-languages=c,ada,c++,go,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-13 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/libexec --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-libstdcxx-backtrace --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --enable-cet --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-13-uJ7kn6/gcc-13-13.2.0/debian/tmp-nvptx/usr,amdgcn-amdhsa=/build/gcc-13-uJ7kn6/gcc-13-13.2.0/debian/tmp-gcn/usr --enable-offload-defaulted --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 13.2.0 (Ubuntu 13.2.0-23ubuntu4) 
****************************************************
Package 'sagemath_doc_html' is currently not installed
No legacy uninstaller found for 'sagemath_doc_html'; nothing to do
mkdir -p en/reference/repl
sage -advanced > en/reference/repl/options.txt
make doc-inventory--reference-references
sage --docbuild --no-pdf-links reference/references inventory 
[reference] building [inventory]: targets for 1 source files that are out of date
[reference] updating environment: [new config] 1 added, 0 changed, 0 removed
[reference] Exception occurred:
[reference]   File "/usr/local/lib/python3.12/dist-packages/sphinx/config.py", line 466, in __getstate__
[reference]     self._options[name] = opt = _Opt(*opt)
[reference]                                 ^^^^^^^^^^
[reference] TypeError: _Opt.__init__() missing 1 required positional argument: 'valid_types'
[reference] The full traceback has been saved in /tmp/sphinx-err-3y93ywlt.log, if you want to report the issue to the developers.
[reference] Please also report this if it was a user error, so that a better error message can be provided next time.
[reference] A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
Error building the documentation.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/yijunyuan/sage-10.3/src/sage_docbuild/__main__.py", line 509, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/yijunyuan/sage-10.3/src/sage_docbuild/__main__.py", line 505, in main
    builder()
  File "/home/yijunyuan/sage-10.3/src/sage_docbuild/builders.py", line 823, in _wrapper
    getattr(DocBuilder, build_type)(self, *args, **kwds)
  File "/home/yijunyuan/sage-10.3/src/sage_docbuild/builders.py", line 163, in f
    runsphinx()
  File "/home/yijunyuan/sage-10.3/src/sage_docbuild/sphinxbuild.py", line 319, in runsphinx
    sys.stderr.raise_errors()
  File "/home/yijunyuan/sage-10.3/src/sage_docbuild/sphinxbuild.py", line 255, in raise_errors
    raise OSError(self._error)
OSError: Exception occurred:
make[6]: *** [Makefile:28: doc-inventory--reference-references] Error 1
make[5]: *** [Makefile:44: doc-inventory-reference] Error 2

real	0m4.073s
user	0m3.653s
sys	0m0.256s
************************************************************************
Error installing package sagemath_doc_html-none
************************************************************************
Please email sage-devel (http://groups.google.com/group/sage-devel)
explaining the problem and including the log files
  /home/yijunyuan/sage-10.3/logs/pkgs/sagemath_doc_html-none.log
and
  /home/yijunyuan/sage-10.3/config.log
Describe your computer, operating system, etc.
If you want to try to fix the problem yourself, *don't* just cd to
/home/yijunyuan/sage-10.3/local/var/tmp/sage/build/sagemath_doc_html-none and type 'make' or whatever is appropriate.
Instead, the following commands setup all environment variables
correctly and load a subshell for you to debug the error:
  (cd '/home/yijunyuan/sage-10.3/local/var/tmp/sage/build/sagemath_doc_html-none' && '/home/yijunyuan/sage-10.3/sage' --buildsh)
When you are done debugging, you can type "exit" to leave the subshell.
************************************************************************
sagemath_doc_html-none
====================================================
Setting up build directory for sagemath_doc_html-none
****************************************************
Host system:
Linux YijunYuan-PC 5.15.146.1-microsoft-standard-WSL2 #1 SMP Thu Jan 11 04:09:03 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
****************************************************
C compiler: gcc
C compiler version:
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-linux-gnu/13/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:amdgcn-amdhsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 13.2.0-23ubuntu4' --with-bugurl=file:///usr/share/doc/gcc-13/README.Bugs --enable-languages=c,ada,c++,go,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-13 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/libexec --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-libstdcxx-backtrace --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --enable-cet --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-13-uJ7kn6/gcc-13-13.2.0/debian/tmp-nvptx/usr,amdgcn-amdhsa=/build/gcc-13-uJ7kn6/gcc-13-13.2.0/debian/tmp-gcn/usr --enable-offload-defaulted --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 13.2.0 (Ubuntu 13.2.0-23ubuntu4) 
****************************************************
Package 'sagemath_doc_html' is currently not installed
No legacy uninstaller found for 'sagemath_doc_html'; nothing to do
mkdir -p en/reference/repl
sage -advanced > en/reference/repl/options.txt
make doc-inventory--reference-references
sage --docbuild --no-pdf-links reference/references inventory 
[reference] building [inventory]: targets for 1 source files that are out of date
[reference] updating environment: [new config] 1 added, 0 changed, 0 removed
[reference] Exception occurred:
[reference]   File "/usr/local/lib/python3.12/dist-packages/sphinx/config.py", line 466, in __getstate__
[reference]     self._options[name] = opt = _Opt(*opt)
[reference]                                 ^^^^^^^^^^
[reference] TypeError: _Opt.__init__() missing 1 required positional argument: 'valid_types'
[reference] The full traceback has been saved in /tmp/sphinx-err-hviglwll.log, if you want to report the issue to the developers.
[reference] Please also report this if it was a user error, so that a better error message can be provided next time.
[reference] A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
Error building the documentation.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/yijunyuan/sage-10.3/src/sage_docbuild/__main__.py", line 509, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/yijunyuan/sage-10.3/src/sage_docbuild/__main__.py", line 505, in main
    builder()
  File "/home/yijunyuan/sage-10.3/src/sage_docbuild/builders.py", line 823, in _wrapper
    getattr(DocBuilder, build_type)(self, *args, **kwds)
  File "/home/yijunyuan/sage-10.3/src/sage_docbuild/builders.py", line 163, in f
    runsphinx()
  File "/home/yijunyuan/sage-10.3/src/sage_docbuild/sphinxbuild.py", line 319, in runsphinx
    sys.stderr.raise_errors()
  File "/home/yijunyuan/sage-10.3/src/sage_docbuild/sphinxbuild.py", line 255, in raise_errors
    raise OSError(self._error)
OSError: Exception occurred:

    Note: incremental documentation builds sometimes cause spurious
    error messages. To be certain that these are real errors, run
    "make doc-clean doc-uninstall" first and try again.
make[6]: *** [Makefile:28: doc-inventory--reference-references] Error 1
make[5]: *** [Makefile:44: doc-inventory-reference] Error 2

real	0m2.596s
user	0m2.349s
sys	0m0.144s
************************************************************************
Error installing package sagemath_doc_html-none
************************************************************************
Please email sage-devel (http://groups.google.com/group/sage-devel)
explaining the problem and including the log files
  /home/yijunyuan/sage-10.3/logs/pkgs/sagemath_doc_html-none.log
and
  /home/yijunyuan/sage-10.3/config.log
Describe your computer, operating system, etc.
If you want to try to fix the problem yourself, *don't* just cd to
/home/yijunyuan/sage-10.3/local/var/tmp/sage/build/sagemath_doc_html-none and type 'make' or whatever is appropriate.
Instead, the following commands setup all environment variables
correctly and load a subshell for you to debug the error:
  (cd '/home/yijunyuan/sage-10.3/local/var/tmp/sage/build/sagemath_doc_html-none' && '/home/yijunyuan/sage-10.3/sage' --buildsh)
When you are done debugging, you can type "exit" to leave the subshell.
************************************************************************
sagemath_doc_html-none
====================================================
Setting up build directory for sagemath_doc_html-none
****************************************************
Host system:
Linux YijunYuan-PC 5.15.146.1-microsoft-standard-WSL2 #1 SMP Thu Jan 11 04:09:03 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
****************************************************
C compiler: gcc
C compiler version:
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-linux-gnu/13/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:amdgcn-amdhsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 13.2.0-23ubuntu4' --with-bugurl=file:///usr/share/doc/gcc-13/README.Bugs --enable-languages=c,ada,c++,go,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-13 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/libexec --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-libstdcxx-backtrace --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --enable-cet --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-13-uJ7kn6/gcc-13-13.2.0/debian/tmp-nvptx/usr,amdgcn-amdhsa=/build/gcc-13-uJ7kn6/gcc-13-13.2.0/debian/tmp-gcn/usr --enable-offload-defaulted --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 13.2.0 (Ubuntu 13.2.0-23ubuntu4) 
****************************************************
Package 'sagemath_doc_html' is currently not installed
No legacy uninstaller found for 'sagemath_doc_html'; nothing to do
mkdir -p en/reference/repl
sage -advanced > en/reference/repl/options.txt
make doc-inventory--reference-references
sage --docbuild --no-pdf-links reference/references inventory 
[reference] building [inventory]: targets for 1 source files that are out of date
[reference] updating environment: [new config] 1 added, 0 changed, 0 removed
[reference] Exception occurred:
[reference]   File "/usr/local/lib/python3.12/dist-packages/sphinx/config.py", line 466, in __getstate__
[reference]     self._options[name] = opt = _Opt(*opt)
[reference]                                 ^^^^^^^^^^
[reference] TypeError: _Opt.__init__() missing 1 required positional argument: 'valid_types'
[reference] The full traceback has been saved in /tmp/sphinx-err-1msge_u1.log, if you want to report the issue to the developers.
[reference] Please also report this if it was a user error, so that a better error message can be provided next time.
[reference] A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
Error building the documentation.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/yijunyuan/sage-10.3/src/sage_docbuild/__main__.py", line 509, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/yijunyuan/sage-10.3/src/sage_docbuild/__main__.py", line 505, in main
    builder()
  File "/home/yijunyuan/sage-10.3/src/sage_docbuild/builders.py", line 823, in _wrapper
    getattr(DocBuilder, build_type)(self, *args, **kwds)
  File "/home/yijunyuan/sage-10.3/src/sage_docbuild/builders.py", line 163, in f
    runsphinx()
  File "/home/yijunyuan/sage-10.3/src/sage_docbuild/sphinxbuild.py", line 319, in runsphinx
    sys.stderr.raise_errors()
  File "/home/yijunyuan/sage-10.3/src/sage_docbuild/sphinxbuild.py", line 255, in raise_errors
    raise OSError(self._error)
OSError: Exception occurred:

    Note: incremental documentation builds sometimes cause spurious
    error messages. To be certain that these are real errors, run
    "make doc-clean doc-uninstall" first and try again.
make[6]: *** [Makefile:28: doc-inventory--reference-references] Error 1
make[5]: *** [Makefile:44: doc-inventory-reference] Error 2

real	0m2.714s
user	0m2.255s
sys	0m0.201s
************************************************************************
Error installing package sagemath_doc_html-none
************************************************************************
Please email sage-devel (http://groups.google.com/group/sage-devel)
explaining the problem and including the log files
  /home/yijunyuan/sage-10.3/logs/pkgs/sagemath_doc_html-none.log
and
  /home/yijunyuan/sage-10.3/config.log
Describe your computer, operating system, etc.
If you want to try to fix the problem yourself, *don't* just cd to
/home/yijunyuan/sage-10.3/local/var/tmp/sage/build/sagemath_doc_html-none and type 'make' or whatever is appropriate.
Instead, the following commands setup all environment variables
correctly and load a subshell for you to debug the error:
  (cd '/home/yijunyuan/sage-10.3/local/var/tmp/sage/build/sagemath_doc_html-none' && '/home/yijunyuan/sage-10.3/sage' --buildsh)
When you are done debugging, you can type "exit" to leave the subshell.
************************************************************************

```

### Config log

https://pastebin.com/N0mYPNGt

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

**Comment by collares** [comment]
Sphinx 7.3 doesn't like the two lines at https://github.com/sagemath/sage/blob/develop/src/sage_docbuild/conf.py#L840-L841. They conflict with a workaround added in https://github.com/sphinx-doc/sphinx/commit/0c06a502227279d3b62c63252da9d12050e07618.

**Comment by collares** [comment]
This and #37996 are the same bug, I think.

**Comment by kiwifb** [comment]
> This and #37996 are the same bug, I think.

It is the same error, I just reported against 10.4.beta5 and 10.3. And it is a good point that it will affect it too while we are working on fixing the future 10.4.
