### ISSUE TITLE
using numpy 2.0

### ISSUE THREAD

**Issue by dimpase** [sagemath/sage#38242]
### Problem Description

it's released, and used by scipy

### Proposed Solution

various things to be done. The 1st is due to flint headers, which use `I` in function declarations, and if you include `complex.h`, you get problems. Fix is easy, and proposed in https://github.com/flintlib/flint/pull/2027

There are also deprecations to be dealt with, e.g.
```
File "src/sage/rings/polynomial/polynomial_element.pyx", line 4639, in sage.rings.polynomial.polynomial_element.Polynomial.factor
Failed example:
    (-2*x^2 - 1).factor()
Expected:
    (-2.0) * (x^2 + 0.5000000000000001)
Got:
    doctest:warning
      File "<doctest sage.rings.polynomial.polynomial_element.Polynomial.factor[44]>", line 1, in <module>
        (-Integer(2)*x**Integer(2) - Integer(1)).factor()
      File "/usr/lib/python3.12/site-packages/numpy/linalg/linalg.py", line 8, in __getattr__
        warnings.warn(
      File "/usr/lib/python3.12/warnings.py", line 112, in _showwarnmsg
        sw(msg.message, msg.category, msg.filename, msg.lineno,
    :
    DeprecationWarning: The numpy.linalg.linalg has been made private and renamed to numpy.linalg._linalg. All public functions exported by it are available from numpy.linalg. Please use numpy.linalg.LinAlgError instead.
    (-2.0) * (x^2 + 0.5000000000000001)
```

### Alternatives Considered

n/a

### Is there an existing issue for this?

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.

**Comment by dimpase** [comment]
here is one more numpy 2.0 issue to be fixed, in `src/sage/plot/complex_plot.pyx:    delta = rgb.ptp(-1)`
- there no ptp method any more, there is a function instead to call
```
[sagemath_doc_html-none] [spkg-install] [plotting ] Traceback (most recent call last):
[sagemath_doc_html-none] [spkg-install] [plotting ]   File "/usr/lib/python3.12/site-packages/matplotlib/sphinxext/plot_directive.py", line 552, in _run_code
[sagemath_doc_html-none] [spkg-install] [plotting ]     exec(code, ns)
[sagemath_doc_html-none] [spkg-install] [plotting ]   File "<string>", line 2, in <module>
[sagemath_doc_html-none] [spkg-install] [plotting ]   File "sage/misc/lazy_import.pyx", line 410, in sage.misc.lazy_import.LazyImport.__call__
[sagemath_doc_html-none] [spkg-install] [plotting ]     return self.get_object()(*args, **kwds)
[sagemath_doc_html-none] [spkg-install] [plotting ]   File "/mnt/opt/Sage/sage-clang/src/sage/misc/decorators.py", line 497, in wrapper
[sagemath_doc_html-none] [spkg-install] [plotting ]     return func(*args, **options)
[sagemath_doc_html-none] [spkg-install] [plotting ]            ^^^^^^^^^^^^^^^^^^^^^^
[sagemath_doc_html-none] [spkg-install] [plotting ]   File "sage/plot/complex_plot.pyx", line 1221, in sage.plot.complex_plot.complex_plot
[sagemath_doc_html-none] [spkg-install] [plotting ]     rgbs = complex_to_cmap_rgb(
[sagemath_doc_html-none] [spkg-install] [plotting ]   File "sage/plot/complex_plot.pyx", line 623, in sage.plot.complex_plot.complex_to_cmap_rgb
[sagemath_doc_html-none] [spkg-install] [plotting ]     rgbs = add_contours_to_rgb(normalized_colors, lightdeltas, dark_rate=dark_rate)
[sagemath_doc_html-none] [spkg-install] [plotting ]   File "sage/plot/complex_plot.pyx", line 760, in sage.plot.complex_plot.add_contours_to_rgb
[sagemath_doc_html-none] [spkg-install] [plotting ]     hls = rgb_to_hls(rgb)
[sagemath_doc_html-none] [spkg-install] [plotting ]   File "sage/plot/complex_plot.pyx", line 1293, in sage.plot.complex_plot.rgb_to_hls
[sagemath_doc_html-none] [spkg-install] [plotting ]     delta = rgb.ptp(-1)
[sagemath_doc_html-none] [spkg-install] [plotting ] AttributeError: `ptp` was removed from the ndarray class in NumPy 2.0. Use np.ptp(arr, ...) instead.
```
