### ISSUE TITLE
 More than 4096 characters with Qepcad causes an error

### ISSUE THREAD

**Issue by anirjoshi** [sagemath/sage#38327]
### Steps To Reproduce

1. I installed Sage-Math 10.3 for my Mac M2 from [https://github.com/3-manifolds/Sage_macOS/releases/](https://github.com/sagemath/sage/issues/link)
2. I tried running a program containing QEPCAD. The link for the program: 
[tmp_sage_ani_git_issue.txt](https://github.com/user-attachments/files/16065741/tmp_sage_ani_git_issue.txt)

3. I used the following commands to execute sage: 
```
       mv tmp_sage_ani_git_issue.txt program.sage
       sage program.sage
 ```

### Expected Behavior

It should output the constraints after quantifier elimination.

### Actual Behavior

Gives the following error:
```
Traceback (most recent call last):
  File "some_path/tmp_sage_ani_git_issue.sage.py", line 3221, in <module>
    print(qepcad(qf.exists(bdeltaAT2,F3063) ,memcells='10000000 +L5000'))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "sage/misc/lazy_import.pyx", line 409, in sage.misc.lazy_import.LazyImport.__call__ (build/cythonized/sage/misc/lazy_import.c:6260)
  File "some_other_path/lib/sage/venv-python3.11.8/lib/python3.11/site-packages/sage/interfaces/qepcad.py", line 1640, in qepcad
    qe = Qepcad(formula, vars=vars, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "some_other_path2/sage-10.3-current/local/var/lib/sage/venv-python3.11.8/lib/python3.11/site-packages/sage/interfaces/qepcad.py", line 887, in __init__
    qex.eval(formula + '.')
  File "some_other_path2/sage-10.3-current/local/var/lib/sage/venv-python3.11.8/lib/python3.11/site-packages/sage/interfaces/expect.py", line 1414, in eval
    return '\n'.join(self._eval_line(L, allow_use_file=allow_use_file, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "some_other_path2/sage-10.3-current/local/var/lib/sage/venv-python3.11.8/lib/python3.11/site-packages/sage/interfaces/expect.py", line 1414, in <genexpr>
    return '\n'.join(self._eval_line(L, allow_use_file=allow_use_file, **kwds)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "some_other_path2/sage-10.3-current/local/var/lib/sage/venv-python3.11.8/lib/python3.11/site-packages/sage/interfaces/expect.py", line 996, in _eval_line
    raise RuntimeError("Sending more than 4096 characters with %s on a line may cause a hang and you're sending %s characters" % (self, len(line)))
RuntimeError: Sending more than 4096 characters with Qepcad on a line may cause a hang and you're sending 65042 characters
```

### Environment

```markdown
- **OS**: Mac M2 Ventura 13.4
- **Sage Version**: 10.3
```

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

**Comment by dimpase** [comment]
You can apply the following patch (or edit the file manually):
```diff
--- a/src/sage/interfaces/expect.py
+++ b/src/sage/interfaces/expect.py
@@ -988,7 +988,7 @@ If this all works, you can then make calls like:
                 self._start()
             E = self._expect
             try:
-                if len(line) >= 4096:
+                if len(line) >= 409600:
                     raise RuntimeError("Sending more than 4096 characters with %s on a line may cause a hang and you're sending %s characters" % (self, len(line)))
                 E.sendline(line)
                 if not wait_for_prompt:
```

probably this should allow it to run. However it might be necessary to write the formula to a file and read it from there directly into QEPCAD.
