### ISSUE TITLE
doctest failure in schemes/elliptic_curves/ell_rational_field.py

### ISSUE THREAD

**Issue by mantepse** [sagemath/sage#38813]
### Steps To Reproduce

```
sage -t --random-seed=91390048253425197917505296851335255685 src/sage/schemes/elliptic_curves/ell_rational_field.py
**********************************************************************
File "src/sage/schemes/elliptic_curves/ell_rational_field.py", line 2389, in sage.schemes.elliptic_curves.ell_rational_field.EllipticCurve_rational_field.?
Failed example:
    E.gens(use_database=False, algorithm='pari',pari_effort=4)   # random
Exception raised:
    Traceback (most recent call last):
      File "/home/martin/sage/src/sage/doctest/forker.py", line 714, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/home/martin/sage/src/sage/doctest/forker.py", line 1144, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.schemes.elliptic_curves.ell_rational_field.EllipticCurve_rational_field.?[4]>", line 1, in <module>
        E.gens(use_database=False, algorithm='pari',pari_effort=Integer(4))   # random
      File "/home/martin/sage/src/sage/schemes/elliptic_curves/ell_rational_field.py", line 2350, in gens
        gens, proved = self._compute_gens(proof, **kwds)
      File "/home/martin/sage/src/sage/schemes/elliptic_curves/ell_rational_field.py", line 2464, in _compute_gens
        raise RuntimeError(f"generators could not be determined. So far we found {ge}. Hint: increase pari_effort.")
    RuntimeError: generators could not be determined. So far we found []. Hint: increase pari_effort.
**********************************************************************
1 item had failures:
   1 of  95 in sage.schemes.elliptic_curves.ell_rational_field.EllipticCurve_rational_field.?
    [884 tests, 1 failure, 24.83 s]
----------------------------------------------------------------------
sage -t --random-seed=91390048253425197917505296851335255685 src/sage/schemes/elliptic_curves/ell_rational_field.py  # 1 doctest failed
----------------------------------------------------------------------
Total time for all tests: 30.0 seconds
    cpu time: 18.2 seconds
    cumulative wall time: 24.8 seconds
Features detected for doctesting: sage.plot,sage.rings.number_field
```

### Expected Behavior

Test should pass

### Actual Behavior

Test fails with specific seed

### Additional Information

 #37293 might be related

### Environment

- **OS**: Ubuntu 22.04.5 LTS"
- **Sage Version**: SageMath version 10.5.beta7, Release Date: 2024-10-12

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

**Comment by S17A05** [comment]
Increasing `pari_effort` to 5 in line 2389 fixes the issue, but might be too ad-hoc of a solution; also, I guess the test should be marked as a long test.

**Comment by S17A05** [comment]
> Increasing `pari_effort` to 5 in line 2389 fixes the issue, but might be too ad-hoc of a solution; also, I guess the test should be marked as a long test.

Update on this: Turning this into a long test also solves the issue (and would be necessary either way, as increasing `pari_effort` makes the test run a bit longer IIIRC) - I'll open a PR for the fix.
