### ISSUE TITLE
Test failure with elliptic point addition

### ISSUE THREAD

**Issue by user202729** [sagemath/sage#39191]
CI: https://github.com/sagemath/sage/actions/runs/12462007486/job/34782318635

```
sage -t --warn-long 5.0 --random-seed=48801491517978841838174003125576793861 src/sage/schemes/elliptic_curves/ell_point.py
**********************************************************************
File "src/sage/schemes/elliptic_curves/ell_point.py", line 277, in sage.schemes.elliptic_curves.ell_point.?._add_
Failed example:
    for d in N.divisors():
        if d > 1:
            assert R.change_ring(Zmod(d)) == P.change_ring(Zmod(d)) + Q.change_ring(Zmod(d))
Exception raised:
    Traceback (most recent call last):
      File "/home/runner/work/sage/sage/src/sage/doctest/forker.py", line 716, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/home/runner/work/sage/sage/src/sage/doctest/forker.py", line 1137, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.schemes.elliptic_curves.ell_point.?._add_[14]>", line 3, in <module>
        assert R.change_ring(Zmod(d)) == P.change_ring(Zmod(d)) + Q.change_ring(Zmod(d))
    AssertionError
**********************************************************************
1 item had failures:
   1 of  34 in sage.schemes.elliptic_curves.ell_point.?._add_
    [1025 tests, 1 failure, 16.38s wall]

```

Looks like it's in the code touched by https://github.com/sagemath/sage/pull/39036 . @yyyyx4 ?

### Environment

- **OS**: CI
- **Sage Version**: latest develop

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

**Comment by S17A05** [comment]
Here is a simplified version of what fails:

```
sage: E = EllipticCurve(Zmod(4), [2, 2, 3, 3, 3])
sage: P = E(2,1,0)
sage: Q = E(0,1,0)
sage: R = P + Q
sage: R == P
False
```

**Comment by vincentmacri** [comment]
> Here is a simplified version of what fails (simplified from the same failure for `random_seed = 312749927201941374195931348514437892724`):
> 
> ```
> sage: E = EllipticCurve(Zmod(4), [2, 2, 3, 3, 3])
> sage: P = E(2,1,0)
> sage: Q = E(0,1,0)
> sage: R = P + Q
> sage: R == P
> False
> ```

This also gives `False` in Sage 10.5, which released before #39036 was merged into the develop branch. So I don't *think* #39036 broke anything, but it may have touched code that already had a bug or maybe added tests that cover this case.

**Comment by S17A05** [comment]
> > Here is a simplified version of what fails (simplified from the same failure for `random_seed = 312749927201941374195931348514437892724`):
> > ```
> > sage: E = EllipticCurve(Zmod(4), [2, 2, 3, 3, 3])
> > sage: P = E(2,1,0)
> > sage: Q = E(0,1,0)
> > sage: R = P + Q
> > sage: R == P
> > False
> > ```
> 
> This also gives `False` in Sage 10.5, which released before [#39036](https://github.com/sagemath/sage/pull/39036) was merged into the develop branch. So I don't _think_ [#39036](https://github.com/sagemath/sage/pull/39036) broke anything, but it may have touched code that already had a bug or maybe added tests that cover this case.

Interesting, thanks for checking. The issue is, however, that the (newly added) test line
```
assert R.change_ring(Zmod(d)) == P.change_ring(Zmod(d)) + Q.change_ring(Zmod(d))
```
wants the above to return `True` (when tracing back the issue from the mentioned seed) - so it might be that this check should be allowed to fail in some situations, but I don't know enough about elliptic curves over rings with zero divisors to make a more precise statement.

**Comment by vincentmacri** [comment]
@yyyyx4 any ideas?

**Comment by user202729** [comment]
Also related (somewhat)

```
sage -t --warn-long 5.0 --random-seed=164819888551818326056171460306830109013 src/sage/schemes/elliptic_curves/ell_point.py
**********************************************************************
Error: Failed example:: Exception raised:
Traceback (most recent call last):
  File "/home/runner/miniconda3/envs/sage-dev/lib/python3.11/site-packages/sage/doctest/forker.py", line 729, in _run
    self.compile_and_execute(example, compiler, test.globs)
  File "/home/runner/miniconda3/envs/sage-dev/lib/python3.11/site-packages/sage/doctest/forker.py", line 1153, in compile_and_execute
    exec(compiled, globs)
  File "<doctest sage.schemes.elliptic_curves.ell_point.?._add_[13]>", line 1, in <module>
    R = P + Q
        ~~^~~
  File "element.pyx", line 1219, in sage.structure.element.Element.__add__
  File "element.pyx", line 2376, in sage.structure.element.ModuleElement._add_
  File "/home/runner/miniconda3/envs/sage-dev/lib/python3.11/site-packages/sage/schemes/elliptic_curves/ell_point.py", line 343, in _add_
    pt = CRT_vectors([pt, [x2.lift(), y2.lift(), z2.lift()]], [mod, mod_2nd])
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/miniconda3/envs/sage-dev/lib/python3.11/site-packages/sage/arith/misc.py", line 3718, in CRT_vectors
    a = CRT_basis(moduli)
        ^^^^^^^^^^^^^^^^^
  File "/home/runner/miniconda3/envs/sage-dev/lib/python3.11/site-packages/sage/arith/misc.py", line 3683, in CRT_basis
    raise ValueError('moduli must be coprime')
ValueError: moduli must be coprime

    R = P + Q
Exception raised:
    Traceback (most recent call last):
      File "/home/runner/miniconda3/envs/sage-dev/lib/python3.11/site-packages/sage/doctest/forker.py", line 729, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/home/runner/miniconda3/envs/sage-dev/lib/python3.11/site-packages/sage/doctest/forker.py", line 1153, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.schemes.elliptic_curves.ell_point.?._add_[13]>", line 1, in <module>
        R = P + Q
            ~~^~~
      File "element.pyx", line 1219, in sage.structure.element.Element.__add__
      File "element.pyx", line 2376, in sage.structure.element.ModuleElement._add_
      File "/home/runner/miniconda3/envs/sage-dev/lib/python3.11/site-packages/sage/schemes/elliptic_curves/ell_point.py", line 343, in _add_
        pt = CRT_vectors([pt, [x2.lift(), y2.lift(), z2.lift()]], [mod, mod_2nd])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/runner/miniconda3/envs/sage-dev/lib/python3.11/site-packages/sage/arith/misc.py", line 3718, in CRT_vectors
        a = CRT_basis(moduli)
            ^^^^^^^^^^^^^^^^^
      File "/home/runner/miniconda3/envs/sage-dev/lib/python3.11/site-packages/sage/arith/misc.py", line 3683, in CRT_basis
        raise ValueError('moduli must be coprime')
    ValueError: moduli must be coprime
**********************************************************************
```

https://github.com/sagemath/sage/actions/runs/13756984151/job/38465894008#step:11:7938

Related?: https://github.com/sagemath/sage/issues/39158

**Comment by yyyyx4** [comment]
For future reference, here's the example from the failing test:
```
N = 46048
E = EllipticCurve(Zmod(N), [22594, 31874, 29311, 12265, 31881])
P = E(27244, 18143, 64)
Q = E(2788, 41887, 32)
R = P + Q
d = 16
assert d.divides(N)
print(E.change_ring(Zmod(d)))
print(R.change_ring(Zmod(d)))
print(P.change_ring(Zmod(d)) + Q.change_ring(Zmod(d)))
```

One way to get this particular test to work is to remove the `.is_zero()` special cases at the beginning of the `EllipticCurvePoint._add_()` method. However, the real issue seems to run deeper: With the current formulas, on this curve (modulo 16), the point $S=(4:1:0)$ is distinct from the neutral element $(0:1:0)$, yet satisfies $S+S=S$, which cannot happen in a group. [Lenstra](https://cr.yp.to/bib/1987/lenstra-ecnta.pdf) in §3 writes that 6 should be a unit in the base ring for things to work. It seems reasonable to assume that this is the root cause of the failure, but I don't understand the theory enough to figure out if this is fixable, and how. Perhaps @JohnCremona does?

**Comment by JohnCremona** [comment]
Is there any use in working with "elliptic curves over Z/NZ" other than in the ecm, where failure means success?

**Comment by yyyyx4** [comment]
The main algorithmic application for non-field base rings seem to be ECM and Schoof-style extensions, indeed. One way to fix it would be to simply restrict the implementation to rings where 6 is a unit, but I had hoped to get it to work in full generality. Alas, it is unclear to me what that "full" generality means mathematically...

**Comment by yyyyx4** [comment]
Since I don't know how to fundamentally resolve the issue, I created a patch to make it at least fail in a clean way. See #41055.
