### ISSUE TITLE
Programming tutorial page seems incorrect

### ISSUE THREAD

**Issue by 11394631-b9c1-43d7-9a17-7970e8e3904d** [sagemath/sage#8478]
<div id="comment:0"></div>

The section Standalone !Python/Sage Scripts at http://www.sagemath.org/doc/tutorial/programming.html#section-loadattach seems to have two problems (profuse apologies if these are actually user errors).

1. __`#!/usr/bin/env sage -python`__ doesn't work in linux since a shebang line can only handle a single argument ('sage' in this case). One workaround is to use __`#!/path/to/sage -python`__ -- I have since verified, however, that simply using __`#!/usr/bin/env sage`__ **does** work with sage 5.8.
2. The script itself seems broken.  When testing it using sage 4.3.3 (and 5.8), running __`./factor 2006`__ works as expected, but __`./factor "32*x^5-1"`__ gives:

```
Traceback (most recent call last):
  File "./factor", line 11, in <module>
    print factor(sage_eval(sys.argv[1]))
  File "/opt/sage-4.3.3-linux-32bit-ubuntu_9.10-i686-Linux/local/lib/python2.6/site-packages/sage/misc/sage_eval.py", line 199, in sage_eval
    return eval(source, sage.all.__dict__, locals)
  File "<string>", line 1, in <module>
NameError: name 'x' is not defined
```

To correct this, see the comment attached to this ticket which provides a new version of the 'factor' script.

Component: **documentation**

_Issue created by migration from https://trac.sagemath.org/ticket/8478_

**Comment by e048caef-d912-466d-8599-c9170ef95588** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1,13 +1,9 @@
-The section Standalone Python/Sage Scripts at http://www.sagemath.org/doc/tutorial/programming.html#section-loadattach seems to have two problems (profuse apologies if these are actually user errors).
+The section Standalone !Python/Sage Scripts at http://www.sagemath.org/doc/tutorial/programming.html#section-loadattach seems to have two problems (profuse apologies if these are actually user errors).
 
-1) #!/usr/bin/env sage -python   doesn't work in linux as shebang can't take two arguments. One simple workaround is to use #!/path_to_sage -python
-2) The script itself seems broken. Testing it using sage 4.3.3
+1. __`#!/usr/bin/env sage -python`__ doesn't work in linux since a shebang line can only handle a single argument ('sage' in this case). One workaround is to use __`#!/path/to/sage -python`__ -- I have since verified, however, that simply using __`#!/usr/bin/env sage`__ **does** work with sage 5.8.
+2. The script itself seems broken.  When testing it using sage 4.3.3 (and 5.8), running __`./factor 2006`__ works as expected, but __`./factor "32*x^5-1"`__ gives:
 
-./factor 2006
-
-works as expected.
-
-But ./factor "32*x^5-1"  gives
+```
 Traceback (most recent call last):
   File "./factor", line 11, in <module>
     print factor(sage_eval(sys.argv[1]))
@@ -15,4 +11,6 @@
     return eval(source, sage.all.__dict__, locals)
   File "<string>", line 1, in <module>
 NameError: name 'x' is not defined
+```
 
+To correct this, see the comment attached to this ticket which provides a new version of the 'factor' script.
``````
